batmat::matrix::View
batch_view_type batmat::matrix::View< T, I, S, D, L, O >::batch(index_type b) const
Access a batch of batch_size() layers, starting at batch index b (i.e.
starting at layer b * batch_size()).
Referenced by batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::batch, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::batch, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::operator+=.
View< T, I, S, I, L, O > batmat::matrix::View< T, I, S, D, L, O >::batch_dyn(index_type b) const
Same as batch(), but returns a view with a dynamic batch size.
If the total depth is not a multiple of the batch size, the last batch will have a smaller size.
Referenced by batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::batch_dyn, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::batch_dyn.
View< T, I, S, N, L, O > batmat::matrix::View< T, I, S, D, L, O >::first_layers(N n) const
Get a view of the first n layers. Note that n can be a compile-time constant.
View< T, I, S, N, L, O > batmat::matrix::View< T, I, S, D, L, O >::middle_layers(index_type l, N n) const
Get a view of n layers starting at layer l.
Note that n can be a compile-time constant. l % batch_size() == 0 (i.e. the starting layer must be at the start of a batch).
T * batmat::matrix::View< T, I, S, D, L, O >::data() const
Get a pointer to the first element of the first layer.
Referenced by batmat::matrix::data, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::data, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::data, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::operator+=.
linear_iterator batmat::matrix::View< T, I, S, D, L, O >::begin() const
Iterate linearly (in storage order) over all elements of the view.
has_full_outer_stride() (i.e. no padding within layers). has_full_layer_stride() (i.e. no padding between batches).
Referenced by batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::begin, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::begin.
std::default_sentinel_t batmat::matrix::View< T, I, S, D, L, O >::end() const
Sentinel for begin().
Referenced by batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::end, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::end.
index_type batmat::matrix::View< T, I, S, D, L, O >::size() const
Total number of elements in the view (excluding padding).
Referenced by batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::size.
index_type batmat::matrix::View< T, I, S, D, L, O >::padded_size() const
Total number of elements in the view (including all padding).
Referenced by batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::padded_size.
depth_type batmat::matrix::View< T, I, S, D, L, O >::depth() const
Number of layers in the view (i.e. depth).
Referenced by batmat::matrix::depth, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::depth.
index_type batmat::matrix::View< T, I, S, D, L, O >::ceil_depth() const
The depth rounded up to a multiple of the batch size.
Referenced by batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::ceil_depth.
index_type batmat::matrix::View< T, I, S, D, L, O >::num_batches() const
Number of batches in the view, i.e. ceil_depth() / batch_size().
Referenced by batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::num_batches.
index_type batmat::matrix::View< T, I, S, D, L, O >::rows() const
Number of rows of the matrices.
Referenced by batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::operator+=, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::rows, batmat::matrix::rows.
index_type batmat::matrix::View< T, I, S, D, L, O >::cols() const
Number of columns of the matrices.
Referenced by batmat::matrix::cols, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::cols, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::operator+=.
index_type batmat::matrix::View< T, I, S, D, L, O >::outer_stride() const
Outer stride of the matrices (leading dimension in BLAS parlance).
Should be multiplied by the batch size to get the actual number of elements.
Referenced by batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::operator+=, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::outer_stride, batmat::matrix::outer_stride.
index_type batmat::matrix::View< T, I, S, D, L, O >::outer_size() const
The size of the outer dimension, i.e.
the number of columns for column-major storage, or the number of rows for row-major storage.
index_type batmat::matrix::View< T, I, S, D, L, O >::inner_size() const
The size of the inner dimension, i.e.
the number of rows for column-major storage, or the number of columns for row-major storage.
index_type batmat::matrix::View< T, I, S, D, L, O >::inner_stride() const
The inner stride of the matrices.
Should be multiplied by the batch size to get the actual number of elements.
batch_size_type batmat::matrix::View< T, I, S, D, L, O >::batch_size() const
The batch size, i.e. the number of layers in each batch. Equals the inner stride.
Referenced by batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::batch_size, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::operator+=.
index_type batmat::matrix::View< T, I, S, D, L, O >::layer_stride() const
The layer stride, i.e.
the distance between the first layer of one batch and the first layer of the next batch. Should be multiplied by the batch size to get the actual number of elements.
bool batmat::matrix::View< T, I, S, D, L, O >::has_full_layer_stride() const
Whether the layer_stride() == outer_stride() * outer_size().
bool batmat::matrix::View< T, I, S, D, L, O >::has_full_outer_stride() const
Whether the outer_stride() == inner_stride() * inner_size().
bool batmat::matrix::View< T, I, S, D, L, O >::has_full_inner_stride() const
Whether the inner_stride() == 1. Always true.
general_slice_view_type batmat::matrix::View< T, I, S, D, L, O >::reshaped(index_type rows, index_type cols) const
Reshape the view to the given dimensions. The total size should not change.
Referenced by batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::reshaped, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::reshaped.
row_slice_view_type batmat::matrix::View< T, I, S, D, L, O >::top_rows(index_type n) const
Get a view of the first n rows.
Referenced by batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::top_rows, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::top_rows.
col_slice_view_type batmat::matrix::View< T, I, S, D, L, O >::left_cols(index_type n) const
Get a view of the first n columns.
Referenced by batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::left_cols, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::left_cols.
row_slice_view_type batmat::matrix::View< T, I, S, D, L, O >::bottom_rows(index_type n) const
Get a view of the last n rows.
Referenced by batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::bottom_rows, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::bottom_rows.
col_slice_view_type batmat::matrix::View< T, I, S, D, L, O >::right_cols(index_type n) const
Get a view of the last n columns.
Referenced by batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::right_cols, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::right_cols.
row_slice_view_type batmat::matrix::View< T, I, S, D, L, O >::middle_rows(index_type r, index_type n) const
Get a view of n rows starting at row r.
Referenced by batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::middle_rows, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::middle_rows.
col_slice_view_type batmat::matrix::View< T, I, S, D, L, O >::middle_cols(index_type c, index_type n) const
Get a view of n columns starting at column c.
Referenced by batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::middle_cols, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::middle_cols.
general_slice_view_type batmat::matrix::View< T, I, S, D, L, O >::top_left(index_type nr, index_type nc) const
Get a view of the top-left nr by nc block of the matrices.
Referenced by batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::top_left, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::top_left.
general_slice_view_type batmat::matrix::View< T, I, S, D, L, O >::top_right(index_type nr, index_type nc) const
Get a view of the top-right nr by nc block of the matrices.
Referenced by batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::top_right, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::top_right.
general_slice_view_type batmat::matrix::View< T, I, S, D, L, O >::bottom_left(index_type nr, index_type nc) const
Get a view of the bottom-left nr by nc block of the matrices.
Referenced by batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::bottom_left, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::bottom_left.
general_slice_view_type batmat::matrix::View< T, I, S, D, L, O >::bottom_right(index_type nr, index_type nc) const
Get a view of the bottom-right nr by nc block of the matrices.
Referenced by batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::bottom_right, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::bottom_right.
general_slice_view_type batmat::matrix::View< T, I, S, D, L, O >::block(index_type r, index_type c, index_type nr, index_type nc) const
Get a view of the nr by nc block of the matrices starting at row r and column c.
Referenced by batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::block, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::block.
auto batmat::matrix::View< T, I, S, D, L, O >::transposed() const
Get a transposed view of the matrices.
Note that the data itself is not modified, the returned view simply accesses the same data with rows and column indices swapped.
Referenced by batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::transposed, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::transposed.
static View batmat::matrix::View< T, I, S, D, L, O >::as_column(std::span< T > v)
Get a view of the given span as a column vector.
void batmat::matrix::View< T, I, S, D, L, O >::add_to_diagonal(const value_type &t)
void batmat::matrix::View< T, I, S, D, L, O >::set_constant(value_type t)
Referenced by batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::set_constant.
void batmat::matrix::View< T, I, S, D, L, O >::negate()
void batmat::matrix::View< T, I, S, D, L, O >::copy_values(const Other &other) const
Referenced by batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::Matrix, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::operator=.
View & batmat::matrix::View< T, I, S, D, L, O >::operator=(const View &other)
Copy assignment copies the values from another view with the same layout to this view.
View & batmat::matrix::View< T, I, S, D, L, O >::operator=(View< U, J, R, E, M, O > other)
Copy values from another view with a compatible value type and the same layout to this view.
View & batmat::matrix::View< T, I, S, D, L, O >::operator+=(View< U, J, R, E, M, O > other)
using batmat::matrix::View< T, I, S, D, L, O >::layout_type = Layout<I, S, D, L, O>
using batmat::matrix::View< T, I, S, D, L, O >::value_type = T
using batmat::matrix::View< T, I, S, D, L, O >::index_type = typename layout_type::index_type
using batmat::matrix::View< T, I, S, D, L, O >::batch_size_type = typename layout_type::batch_size_type
using batmat::matrix::View< T, I, S, D, L, O >::depth_type = typename layout_type::depth_type
using batmat::matrix::View< T, I, S, D, L, O >::layer_stride_type = typename layout_type::layer_stride_type
using batmat::matrix::View< T, I, S, D, L, O >::standard_stride_type = typename layout_type::standard_stride_type
using batmat::matrix::View< T, I, S, D, L, O >::const_view_type = View<const T, I, S, D, L, O>
using batmat::matrix::View< T, I, S, D, L, O >::batch_view_type = View<T, I, S, S, DefaultStride, O>
When extracing a single batch, the depth equals the batch size, and the layer stride is no longer relevant.
using batmat::matrix::View< T, I, S, D, L, O >::general_slice_view_type = std::conditional_t<has_single_batch_at_compile_time, View, View<T, I, S, D, I, O>>
When slicing along the outer dimension, the layer stride stays the same, but the outer size may be smaller, which means that even if the original view has a default layer stride, the sliced view may require a dynamic layer stride.
For a single batch, the layer stride is not relevant, so it is preserved.
using batmat::matrix::View< T, I, S, D, L, O >::col_slice_view_type = std::conditional_t<is_row_major, View, general_slice_view_type>
View with the correct layer stride when slicing along the column dimension.
For row-major storage, slicing along columns does not change the outer size, in which case the layer stride is still correct. For column-major storage, slicing along columns does change the outer size, in which case we need a dynamic layer stride.
using batmat::matrix::View< T, I, S, D, L, O >::row_slice_view_type = std::conditional_t<is_column_major, View, general_slice_view_type>
View with the correct layer stride when slicing along the row dimension.
col_slice_view_type
StorageOrder batmat::matrix::View< T, I, S, D, L, O >::storage_order
bool batmat::matrix::View< T, I, S, D, L, O >::is_column_major
bool batmat::matrix::View< T, I, S, D, L, O >::is_row_major
bool batmat::matrix::View< T, I, S, D, L, O >::has_single_batch_at_compile_time
True if batch_size() and depth() are compile-time constants and are equal.
Views with dynamic batch size and depth may still have a single batch at runtime, but this cannot be statically asserted.
bool batmat::matrix::View< T, I, S, D, L, O >::has_single_layer_at_compile_time
True if depth() is a compile-time constant and is equal to one.
value_type* batmat::matrix::View< T, I, S, D, L, O >::data_ptr
Pointer to the first element of the first layer.
Referenced by batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::reassign.
layout_type batmat::matrix::View< T, I, S, D, L, O >::layout
Layout describing the dimensions and strides of the view.
Referenced by batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::reassign.
batmat::matrix::View< T, I, S, D, L, O >::View(PlainBatchedMatrixView p={})
Create a new view.
It is recommended to use designated initializers for the arguments to avoid mistakes.
batmat::matrix::View< T, I, S, D, L, O >::View(std::span< T > data, layout_type layout)
Create a new view with the given layout, using the given buffer.
batmat::matrix::View< T, I, S, D, L, O >::View(value_type *data, layout_type layout)
Create a new view with the given layout, using the given buffer.
batmat::matrix::View< T, I, S, D, L, O >::View(const View &)=default
Copy a view. No data is copied.
batmat::matrix::View< T, I, S, D, L, O >::operator const_view_type() const
Non-const views implicitly convert to const views.
const_view_type batmat::matrix::View< T, I, S, D, L, O >::as_const() const
Explicit conversion to a const view.
batmat::matrix::View< T, I, S, D, L, O >::operator guanaqo::MatrixView< T, I, standard_stride_type, O >() const
If we have a single layer at compile time, we can implicitly convert to a non-batched view.
guanaqo::MatrixView< T, I, standard_stride_type, O > batmat::matrix::View< T, I, S, D, L, O >::operator()(index_type l) const
Access a single layer l as a non-batched view.
The inner stride of the returned view is equal to the batch size of this view, so it cannot be used directly with functions that require unit inner stride (e.g. BLAS).
value_type & batmat::matrix::View< T, I, S, D, L, O >::operator()(index_type l, index_type r, index_type c) const
Access a single element at layer l, row r and column c.
View & batmat::matrix::View< T, I, S, D, L, O >::reassign(View other)
Reassign the buffer and layout of this view to those of another view. No data is copied.
batmat::matrix::View< T, I, S, D, L, O >::operator View< T, I, S, integral_value_type_t< D >, L, O >() const
Implicit conversion to a view with a dynamic depth.
batmat::matrix::View< T, I, S, D, L, O >::operator View< const T, I, S, integral_value_type_t< D >, L, O >() const
Implicit conversion to a view with a dynamic depth, going from non-const to const.
batmat::matrix::View< T, I, S, D, L, O >::operator View< T, I, S, D, I, O >() const
Implicit conversion to a view with a dynamic layer stride.
batmat::matrix::View< T, I, S, D, L, O >::operator View< const T, I, S, D, I, O >() const
Implicit conversion to a view with a dynamic layer stride, going from non-const to const.
auto batmat::matrix::View< T, I, S, D, L, O >::get_layer_stride_for() const