batmat::linalg::uview
using batmat::linalg::uview< T, Abi, Order >::value_type = T
using batmat::linalg::uview< T, Abi, Order >::types = simd_view_types<std::remove_const_t<T>, Abi>
using batmat::linalg::uview< T, Abi, Order >::view = types::template view<T, Order>
using batmat::linalg::uview< T, Abi, Order >::mut_view = types::template view<std::remove_const_t<T>, Order>
using batmat::linalg::uview< T, Abi, Order >::mut_uview = uview<std::remove_const_t<T>, Abi, Order>
using batmat::linalg::uview< T, Abi, Order >::simd = typename types::simd
value_type* batmat::linalg::uview< T, Abi, Order >::data
index_t batmat::linalg::uview< T, Abi, Order >::outer_stride
ptrdiff_t batmat::linalg::uview< T, Abi, Order >::inner_stride
value_type * batmat::linalg::uview< T, Abi, Order >::get(index_t r, index_t c) const noexcept
Referenced by batmat::linalg::uview< std::remove_const_t< T >, Abi, Order >::load, batmat::linalg::uview< std::remove_const_t< T >, Abi, Order >::operator(), batmat::linalg::uview< std::remove_const_t< T >, Abi, Order >::store.
value_type & batmat::linalg::uview< T, Abi, Order >::operator()(index_t r, index_t c) const noexcept
simd batmat::linalg::uview< T, Abi, Order >::load(index_t r, index_t c) const noexcept
Referenced by batmat::linalg::detail::symm.
void batmat::linalg::uview< T, Abi, Order >::store(simd x, index_t r, index_t c) const noexcept
Referenced by batmat::linalg::micro_kernels::gemm_diag::gemm_diag_copy_register, batmat::linalg::detail::symm.
Self batmat::linalg::uview< T, Abi, Order >::block(this const Self &self, index_t r, index_t c) noexcept
Referenced by batmat::linalg::micro_kernels::gemm::gemm_copy_register, batmat::linalg::micro_kernels::gemm_diag::gemm_diag_copy_register, batmat::linalg::micro_kernels::hyhound::hyhound_diag_register, batmat::linalg::micro_kernels::potrf::potrf_copy_register, batmat::linalg::micro_kernels::symv::symv_copy_register, batmat::linalg::micro_kernels::trsm::trsm_copy_register, batmat::linalg::micro_kernels::trtri::trtri_copy_register.
Self batmat::linalg::uview< T, Abi, Order >::middle_rows(this const Self &self, index_t r) noexcept
Referenced by batmat::linalg::micro_kernels::gemm::gemm_copy_register, batmat::linalg::micro_kernels::gemm_diag::gemm_diag_copy_register, batmat::linalg::micro_kernels::hyhound::hyhound_diag_register, batmat::linalg::micro_kernels::potrf::potrf_copy_register, batmat::linalg::micro_kernels::symv::symv_copy_register, batmat::linalg::micro_kernels::trsm::trsm_copy_register.
Self batmat::linalg::uview< T, Abi, Order >::middle_cols(this const Self &self, index_t c) noexcept
Referenced by batmat::linalg::micro_kernels::gemm::gemm_copy_register, batmat::linalg::micro_kernels::gemm_diag::gemm_diag_copy_register, batmat::linalg::micro_kernels::syomv::syomv_register, batmat::linalg::micro_kernels::trsm::trsm_copy_register.
batmat::linalg::uview< T, Abi, Order >::uview(value_type *data, index_t outer_stride) noexcept
batmat::linalg::uview< T, Abi, Order >::uview(const mut_view &v) noexcept
batmat::linalg::uview< T, Abi, Order >::uview(const view &v) noexcept
batmat::linalg::uview< T, Abi, Order >::uview(const mut_uview &o) noexcept
batmat::linalg::uview< T, Abi, Order >::uview(const uview &o)=default