function(codegen_compact_microkernels tgt)

    add_library(${tgt}-microkernels INTERFACE)
    set(OUT_DIR "${CMAKE_CURRENT_BINARY_DIR}/${tgt}/codegen")
    set(TPP_DIR "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../../include/koqkatoo/linalg-compact/compact-new/micro-kernels")
    foreach(op "xgemm" "xgemm-diag" "xgemm-diag-mask" "xgemmt" "xtrsm" "xpotrf")
        add_library(${tgt}-microkernels-${op} OBJECT)
        target_link_libraries(${tgt}-microkernels-${op} PRIVATE ${tgt})
        target_precompile_headers(${tgt}-microkernels-${op} PRIVATE "${TPP_DIR}/${op}.tpp")
        target_link_libraries(${tgt}-microkernels INTERFACE $<TARGET_OBJECTS:${tgt}-microkernels-${op}>)
        foreach(I 1 2 4 8)
            set(simd_abi "deduce_t<real_t, ${I}>")
            if (I EQUAL 1)
                set(simd_abi "scalar")
            endif()
            configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/${op}.cpp.in" "${OUT_DIR}/${op}-${I}.cpp" @ONLY)
            target_sources(${tgt}-microkernels-${op} PRIVATE "${OUT_DIR}/${op}-${I}.cpp")
        endforeach()
    endforeach()

endfunction()
