function(codegen_compact_microkernels tgt headers)

    add_library(${tgt}-microkernels INTERFACE)
    list(APPEND KOQKATOO_CODEGEN_TARGETS ${tgt}-microkernels)
    set(OUT_DIR "${CMAKE_CURRENT_BINARY_DIR}/${tgt}/codegen")
    set(TPP_DIR "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../../include/koqkatoo/linalg-compact/compact/micro-kernels")
    foreach(op "xgemm" "xgemm-diag" "xgemm-diag-mask" "xgemmt" "xgemmt-diag" "xgemmt-diag-mask" "xtrmm" "xtrsm" "xpotrf" "xpntrf" "xtrtri" "xshh" "xshhud" "xshhud-diag")
        add_library(${tgt}-microkernels-${op} STATIC)
        target_link_libraries(${tgt}-microkernels-${op} PRIVATE ${headers} warnings)
        target_precompile_headers(${tgt}-microkernels-${op} PRIVATE "${TPP_DIR}/${op}.tpp")
        target_link_libraries(${tgt}-microkernels INTERFACE ${tgt}-microkernels-${op})
        list(APPEND KOQKATOO_CODEGEN_TARGETS ${tgt}-microkernels-${op})
        foreach(I 1 2 4 8 16)
            set(simd_abi "deduce_t<real_t, ${I}>")
            if (I EQUAL 1)
                set(simd_abi "scalar")
            endif()
            configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/${op}.cpp.in" "${OUT_DIR}/${op}-${I}.cpp" @ONLY)
            target_sources(${tgt}-microkernels-${op} PRIVATE "${OUT_DIR}/${op}-${I}.cpp")
        endforeach()
    endforeach()
    target_link_libraries(${tgt}-microkernels-xgemmt PRIVATE ${tgt}-microkernels-xgemm)
    target_link_libraries(${tgt}-microkernels-xgemmt-diag PRIVATE ${tgt}-microkernels-xgemm-diag)
    target_link_libraries(${tgt}-microkernels-xgemmt-diag-mask PRIVATE ${tgt}-microkernels-xgemm-diag-mask)

    set(KOQKATOO_CODEGEN_TARGETS ${KOQKATOO_CODEGEN_TARGETS} PARENT_SCOPE)
endfunction()
