topic-low-level-ops
T batmat::ops::detail::cneg(T x, T signs)
Conditionally negates the sign bit of x, depending on signs, which should contain only ±0 (i.e.
only the sign bit of an IEEE-754 floating point number).
T batmat::ops::detail::cneg(T x, T signs)
Conditionally negates the sign bit of x, depending on signs, which should contain only ±0 (i.e.
only the sign bit of an IEEE-754 floating point number).
References BATMAT_ASSUME.
datapar::simd< T, Abi > batmat::ops::detail::cneg(datapar::simd< T, Abi > x, datapar::simd< T, Abi > signs)
Conditionally negates the sign bit of x, depending on signs, which should contain only ±0 (i.e.
only the sign bit of an IEEE-754 floating point number).
References BATMAT_ASSUME.
datapar::simd< T, AbiT > batmat::ops::gather(const T *p, datapar::simd< I, AbiI > idx, M mask)
Gathers elements from memory at the addresses specified by idx, which should be an integer SIMD vector, and returns them in a SIMD vector of type datapar::simd<T, AbiT>.
The elements are gathered relative to the base address p. The gathering is masked by mask,
References batmat::ops::detail::convert_mask, batmat::ops::detail::gather.
Referenced by batmat::linalg::detail::compress_masks_impl.
datapar::simd< F, Abi > batmat::ops::rotl(datapar::simd< F, Abi > x)
Rotates the elements of x by s positions to the left.
For example, rotl<1>([x0, x1, x2, x3]) == [x1, x2, x3, x0] and rotl<-1>([x0, x1, x2, x3]) == [x3, x0, x1, x2].
References batmat::ops::detail::rotl, batmat::ops::detail::rotr.
Referenced by batmat::linalg::detail::copy::copy.
datapar::simd< F, Abi > batmat::ops::rotr(datapar::simd< F, Abi > x)
Rotate the elements of x to the right by S positions.
For example, rotr<1>([x0, x1, x2, x3]) == [x3, x0, x1, x2] and rotr<-1>([x0, x1, x2, x3]) == [x1, x2, x3, x0].
References batmat::ops::detail::rotl, batmat::ops::detail::rotr.
Referenced by batmat::linalg::detail::copy::copy, batmat::linalg::micro_kernels::hyhound::detail::rotate.
datapar::simd< F, Abi > batmat::ops::shiftl(datapar::simd< F, Abi > x)
Shift the elements of x to the left by S positions, shifting in zeros.
For example, shiftl<1>([x0, x1, x2, x3]) == [x1, x2, x3, 0] and shiftl<-1>([x0, x1, x2, x3]) == [0, x0, x1, x2].
References batmat::ops::detail::shiftl, batmat::ops::detail::shiftr.
Referenced by batmat::linalg::micro_kernels::syomv::syomv_microkernel.
datapar::simd< F, Abi > batmat::ops::shiftr(datapar::simd< F, Abi > x)
Shift the elements of x to the right by S positions, shifting in zeros.
For example, shiftr<1>([x0, x1, x2, x3]) == [0, x0, x1, x2] and shiftr<-1>([x0, x1, x2, x3]) == [x1, x2, x3, 0].
References batmat::ops::detail::shiftl, batmat::ops::detail::shiftr.
Referenced by batmat::linalg::micro_kernels::syomv::syomv_microkernel.
datapar::simd< F, Abi > batmat::ops::detail::rot(datapar::simd< F, Abi > x, int s)
Rotate the elements of x to the right by s positions.
For example, rotr<1>([x0, x1, x2, x3]) == [x3, x0, x1, x2] and rotr<-1>([x0, x1, x2, x3]) == [x1, x2, x3, x0].
Referenced by batmat::linalg::micro_kernels::hyhound::detail::rotate.
T batmat::ops::rsqrt(T x)
Inverse square root.
Referenced by batmat::linalg::micro_kernels::potrf::potrf_copy_microkernel, batmat::linalg::micro_kernels::potrf::trsm_copy_microkernel.
datapar::simd< T, Abi > batmat::ops::rsqrt(datapar::simd< T, Abi > x)
Inverse square root.
May be implemented using an rsqrt instruction followed by Newton iterations for better performance, depending on the SIMD ABI. This allows it to be performed in parallel with a normal square root instruction, enabling better performance of the Cholesky micro-kernels.
void batmat::ops::transpose_dyn(const T *pa, index_t lda, T *pb, index_t ldb, index_t d=R)
Transposes the R × C matrix at pa with leading dimension lda, writing the result to pb with leading dimension ldb, writing only the d first columns of the result.
References BATMAT_ASSUME, BATMAT_FULLY_UNROLLED_FOR.
Referenced by batmat::ops::transpose.
void batmat::ops::transpose(const T *pa, index_t lda, T *pb, index_t ldb)
Transposes the R × C matrix at pa with leading dimension lda, writing the result to pb with leading dimension ldb.
References batmat::ops::transpose_dyn.
Referenced by batmat::linalg::detail::copy::copy.