topic-linalg-flops
FlopCount batmat::linalg::flops::operator+(FlopCount a, FlopCount b)
Combine two flop counts by summing the counts of each operation type.
References batmat::linalg::flops::FlopCount::add, batmat::linalg::flops::FlopCount::div, batmat::linalg::flops::FlopCount::fma, batmat::linalg::flops::FlopCount::mul, batmat::linalg::flops::FlopCount::sqrt.
index_t batmat::linalg::flops::total(FlopCount c)
Compute the total number of floating point operations by summing the counts of all operation types.
References batmat::linalg::flops::FlopCount::add, batmat::linalg::flops::FlopCount::div, batmat::linalg::flops::FlopCount::fma, batmat::linalg::flops::FlopCount::mul, batmat::linalg::flops::FlopCount::sqrt.
FlopCount batmat::linalg::flops::gemm(index_t m, index_t n, index_t k)
Matrix-matrix multiplication of m×k and k×n matrices.
Implementation:constexprFlopCountgemm(index_tm,index_tn,index_tk){return{.fma=m*k*n};}
FlopCount batmat::linalg::flops::trmm(index_t m, index_t n, index_t k, MatrixStructure sA, MatrixStructure sB, MatrixStructure sC)
Matrix-matrix multiplication of m×k and k×n matrices where one or more of the matrices are triangular or trapezoidal.
Implementation:constexprFlopCounttrmm(index_tm,index_tn,index_tk,MatrixStructuresA,MatrixStructuresB, MatrixStructuresC){ usingenumMatrixStructure; if(sB==General&&sC==General){ if(sA==LowerTriangular||sA==UpperTriangular){//trapezoidalA if(m>=k)//tallA //xxxxxxxxxxxx //xxxxxxxxxxxxx //xxxxxxxxxxxxxx //xxxxx //xxxx return{.fma=k*(k+1)/2*n+(m-k)*k*n}; else//wideA //xxxxxxxxxxxxxx //xxxxxxxxxxxxxx //xxxxxxxxxxxxxx //xxxxxx //xxxxxx return{.fma=m*(m+1)/2*n+(k-m)*(k-m)*n}; }elseif(sA==General){ return{.fma=m*k*n}; }else{ BATMAT_ASSUME(!"invalidstructure"); } }elseif(sA==General&&sC==General){ if(sB==LowerTriangular||sB==UpperTriangular){//trapezoidalB if(n>=k)//wideB return{.fma=k*(k+1)/2*m+(n-k)*k*m}; else//tallB return{.fma=n*(n+1)/2*m+(k-n)*(k-n)*m}; }else{ BATMAT_ASSUME(!"invalidstructure"); } }elseif(sA==General&&sB==General){ if(sC==LowerTriangular||sC==UpperTriangular){ BATMAT_ASSUME(m==n); return{.fma=m*(m+1)/2*k}; }else{ BATMAT_ASSUME(!"invalidstructure"); } }elseif(sC==LowerTriangular||sC==UpperTriangular){ if(sA==transpose(sB)){ BATMAT_ASSUME(m==n); BATMAT_ASSUME(m==k); return{.fma=m*(m+1)*(m+2)/6}; }else{ BATMAT_ASSUME(!"invalidstructure"); } }else{ BATMAT_ASSUME(!"unsupportedstructure"); } return{}; }
References BATMAT_ASSUME, batmat::linalg::General, batmat::linalg::LowerTriangular, batmat::linalg::transpose, batmat::linalg::UpperTriangular.
Referenced by batmat::linalg::detail::gemmt, batmat::linalg::flops::gemmt, batmat::linalg::flops::gemmt_diag, batmat::linalg::detail::trmm.
FlopCount batmat::linalg::flops::gemmt(index_t m, index_t n, index_t k, MatrixStructure sA, MatrixStructure sB, MatrixStructure sC)
Matrix-matrix multiplication of m×k and k×n matrices where the result is symmetric.
Implementation:constexprFlopCountgemmt(index_tm,index_tn,index_tk,MatrixStructuresA,MatrixStructuresB, MatrixStructuresC){ returntrmm(m,n,k,sA,sB,sC); }
References batmat::linalg::flops::trmm.
Referenced by batmat::linalg::flops::syrk.
FlopCount batmat::linalg::flops::syrk(index_t n, index_t k)
Symmetric rank-k update of n×n matrices.
Implementation:constexprFlopCountsyrk(index_tn,index_tk){ returngemmt(n,n,k,MatrixStructure::General,MatrixStructure::General, MatrixStructure::LowerTriangular); }
References batmat::linalg::flops::gemmt, batmat::linalg::General, batmat::linalg::LowerTriangular.
FlopCount batmat::linalg::flops::gemmt_diag(index_t m, index_t n, index_t k, MatrixStructure sC)
Matrix-matrix multiplication of m×k and k×n matrices with a diagonal k×k matrix in the middle, where the result is symmetric.
Implementation:constexprFlopCountgemmt_diag(index_tm,index_tn,index_tk,MatrixStructuresC){ constexprautosA=MatrixStructure::General,sB=sA; returntrmm(m,n,k,sA,sB,sC)+FlopCount{.mul=std::min(m,n)*k}; }
References batmat::linalg::General, batmat::linalg::flops::trmm.
Referenced by batmat::linalg::detail::gemm_diag::gemm_diag.
FlopCount batmat::linalg::flops::potrf(index_t m, index_t n)
Cholesky factorization and triangular solve for an m×n matrix with m≥n.
Implementation:constexprFlopCountpotrf(index_tm,index_tn){ BATMAT_ASSUME(m>=n); return{ .fma=(n+1)*n*(n-1)/6//Schurcomplement(square) +(m-n)*n*(n-1)/2,//(bottom) .mul=n*(n-1)/2//multiplicationbyinversepivot(square) +(m-n)*n,//(bottom) .div=n,//invertingpivot .sqrt=n,//squarerootpivot }; }
References BATMAT_ASSUME.
Referenced by batmat::linalg::flops::syrk_potrf.
FlopCount batmat::linalg::flops::hyh_square(index_t n, index_t k)
Hyperbolic Householder factorization update with L n×n and A nr×k.
Implementation:constexprFlopCounthyh_square(index_tn,index_tk){ return{ .fma=k*n*n+2*n, .mul=k*n+(n+1)*n/2+n, .add=(n+1)*n/2+n, .div=2*n, .sqrt=n, }; }
Referenced by batmat::linalg::flops::hyh.
FlopCount batmat::linalg::flops::hyh_apply(index_t nr, index_t nc, index_t k)
Hyperbolic Householder factorization application to L2 nr×nc and A2 nr×k.
Implementation:constexprFlopCounthyh_apply(index_tnr,index_tnc,index_tk){ return{ .fma=2*nr*k*nc, .mul=nr*nc, .add=nr*nc, }; }
Referenced by batmat::linalg::flops::hyh, batmat::linalg::detail::hyhound_diag_apply.
FlopCount batmat::linalg::flops::hyh(index_t nr, index_t nc, index_t k)
Hyperbolic Householder factorization update with L nr×nc and A nr×k.
Implementation:constexprFlopCounthyh(index_tnr,index_tnc,index_tk){ BATMAT_ASSUME(nr>=nc); returnhyh_square(nc,k)+hyh_apply(nr-nc,nc,k); }
References BATMAT_ASSUME, batmat::linalg::flops::hyh_apply, batmat::linalg::flops::hyh_square.
Referenced by batmat::linalg::detail::hyhound_diag, batmat::linalg::detail::hyhound_diag, batmat::linalg::detail::hyhound_diag_2, batmat::linalg::detail::hyhound_diag_cyclic, batmat::linalg::detail::hyhound_diag_riccati.
FlopCount batmat::linalg::flops::syrk_potrf(index_t m, index_t n, index_t k)
Fused symmetric rank-k update and Cholesky factorization of an m×n matrix with m≥n.
Implementation:constexprFlopCountsyrk_potrf(index_tm,index_tn,index_tk){ BATMAT_ASSUME(m>=n); returnpotrf(m,n)+FlopCount{.fma=n*(n+1)*k/2+(m-n)*n*k}; }
References BATMAT_ASSUME, batmat::linalg::flops::potrf.
FlopCount batmat::linalg::flops::trsm(index_t m, index_t n)
Triangular solve of m×n matrices.
Implementation:constexprFlopCounttrsm(index_tm,index_tn){ return{.fma=m*(m-1)*n/2,.mul=m*n,.div=m}; }
Referenced by batmat::linalg::detail::trsm.
FlopCount batmat::linalg::flops::trtri(index_t m)
Triangular inversion of an m×m matrix.
Implementation:constexprFlopCounttrtri(index_tm){ return{.fma=(m+1)*m*(m-1)/6,.div=m};//TODO }
Referenced by batmat::linalg::detail::trtri.