batmat::ops
index_t batmat::ops::RowsRegTranspose
Referenced by batmat::linalg::detail::copy::copy.
index_t batmat::ops::ColsRegTranspose
Referenced by batmat::linalg::detail::copy::copy.
index_t batmat::ops::RowsRegTranspose< double >
index_t batmat::ops::ColsRegTranspose< double >
T batmat::ops::detail::cneg(T x, T signs)
Conditionally negates the sign bit of x, depending on signs, which should contain only ±0 (i.e.
only the sign bit of an IEEE-754 floating point number).
Referenced by batmat::linalg::micro_kernels::potrf::apply_diag, batmat::linalg::micro_kernels::hyhound::hyhound_diag_diag_microkernel, batmat::linalg::micro_kernels::hyhound::hyhound_diag_full_microkernel, batmat::linalg::micro_kernels::hyhound::hyhound_diag_tail_microkernel.