batmat::linalg::micro_kernels::potrf
using batmat::linalg::micro_kernels::potrf::diag_uview_type = std::conditional_t<Conf.with_diag(), uview_vec<T, Abi>, std::false_type>
using batmat::linalg::micro_kernels::potrf::diag_view_type = std::conditional_t<Conf.with_diag(), view<T, Abi>, std::false_type>
index_t batmat::linalg::micro_kernels::potrf::ColsReg
Referenced by potrf_copy_register, trsm_copy_microkernel.
const constinit auto batmat::linalg::micro_kernels::potrf::potrf_copy_lut
Referenced by potrf_copy_register.
const constinit auto batmat::linalg::micro_kernels::potrf::trsm_copy_lut
Referenced by potrf_copy_register.
index_t batmat::linalg::micro_kernels::gemm::RowsReg
Register block size of the matrix-matrix multiplication micro-kernels.
AVX-512 has 32 vector registers, we use 25 registers for a 5×5 accumulator block of matrix C (leaving some registers for loading A and B): AVX2 has 16 vector registers, we use 9 registers for a 3×3 accumulator block of matrix C (leaving some registers for loading A and B): A block size of 4×4 is slightly faster than 3×3 for large matrices, because the even block size results in full cache lines being consumed. For small matrices, 3×3 is faster because it does not spill any registers in the micro-kernels. 2×2 is slower than 3×3 for both small and large matrices (tested using GCC 15.1 on an i7-10750H). Assumes that the platform has at least 16 vector registers, we use 9 registers for a 3×3 accumulator block of matrix C (leaving some registers for loading A and B): NEON has 32 vector registers, we use 16 registers for a 4×4 accumulator block of matrix C (leaving plenty of registers for loading A and B):
Referenced by potrf_copy_microkernel, potrf_copy_register, trsm_copy_microkernel.
void batmat::linalg::micro_kernels::potrf::potrf_copy_microkernel(uview< const T, Abi, O1 > A1, uview< const T, Abi, O2 > A2, uview< const T, Abi, O2 > C, uview< T, Abi, O2 > D, T *invD, index_t k1, index_t k2, T regularization, diag_uview_type< const T, Abi, Conf > diag) noexcept
A1 RowsReg×k1. A2 RowsReg×k2. C RowsReg×RowsReg. D RowsReg×RowsReg. invD Inverse diagonal of D. k1 Number of columns in A1. k2 Number of columns in A2. regularization Regularization added to the diagonal of C before factorization.
References batmat::datapar::aligned_store, apply_diag, load_diag, batmat::linalg::LowerTriangular, RowsReg, batmat::ops::rsqrt, UNROLL_FOR, batmat::linalg::with_cached_access.
void batmat::linalg::micro_kernels::potrf::trsm_copy_microkernel(uview< const T, Abi, O1 > A1, uview< const T, Abi, O1 > B1, uview< const T, Abi, O2 > A2, uview< const T, Abi, O2 > B2, uview< const T, Abi, O2 > L, const T *invL, uview< const T, Abi, O2 > C, uview< T, Abi, O2 > D, index_t k1, index_t k2, diag_uview_type< const T, Abi, Conf > diag) noexcept
A1 RowsReg×k1. B1 ColsReg×k1. A2 RowsReg×k2. B2 ColsReg×k2. L ColsReg×ColsReg. invL ColsReg (inverted diagonal of L). C RowsReg×ColsReg. D RowsReg×ColsReg. k1 Number of columns in A1 and B1. k2 Number of columns in A2 and B2.
References batmat::datapar::aligned_load, apply_diag, ColsReg, load_diag, batmat::linalg::LowerTriangular, RowsReg, batmat::ops::rsqrt, UNROLL_FOR, batmat::linalg::with_cached_access.
void batmat::linalg::micro_kernels::potrf::potrf_copy_register(view< const T, Abi, OA > A, view< const T, Abi, OCD > C, view< T, Abi, OCD > D, T regularization, diag_view_type< const T, Abi, Conf > diag) noexcept
References BATMAT_ASSUME, batmat::linalg::uview< T, Abi, Order >::block, ColsReg, batmat::foreach_chunked_merged, batmat::linalg::LowerTriangular, batmat::linalg::uview< T, Abi, Order >::middle_rows, potrf_copy_lut, RowsReg, trsm_copy_lut.
auto batmat::linalg::micro_kernels::potrf::load_diag(auto diag, index_t l) noexcept
Referenced by potrf_copy_microkernel, trsm_copy_microkernel.
auto batmat::linalg::micro_kernels::potrf::apply_diag(auto x, auto d) noexcept
References batmat::ops::cneg.
Referenced by potrf_copy_microkernel, trsm_copy_microkernel.