batmat::linalg::micro_kernels::hyhound
Structure
index_t batmat::linalg::micro_kernels::hyhound::SizeR
Referenced by hyhound_diag_diag_microkernel, hyhound_diag_tail_microkernel.
index_t batmat::linalg::micro_kernels::hyhound::SizeS
const constinit auto batmat::linalg::micro_kernels::hyhound::microkernel_diag_lut
Referenced by hyhound_diag_register.
const constinit auto batmat::linalg::micro_kernels::hyhound::microkernel_full_lut
Referenced by hyhound_diag_register.
const constinit auto batmat::linalg::micro_kernels::hyhound::microkernel_tail_lut
const constinit auto batmat::linalg::micro_kernels::hyhound::microkernel_tail_lut_2
void batmat::linalg::micro_kernels::hyhound::hyhound_diag_diag_microkernel(index_t kA, triangular_accessor< T, Abi, SizeR< T, Abi > > W, uview< T, Abi, OL > L, uview< T, Abi, OA > A, uview< const T, Abi, StorageOrder::ColMajor > diag) noexcept
References BATMAT_ASSUME, batmat::ops::cneg, SizeR, UNROLL_FOR, batmat::linalg::with_cached_access.
void batmat::linalg::micro_kernels::hyhound::hyhound_diag_full_microkernel(index_t kA, uview< T, Abi, OL > L, uview< T, Abi, OA > A, uview< const T, Abi, StorageOrder::ColMajor > diag) noexcept
References BATMAT_ASSUME, batmat::ops::cneg, UNROLL_FOR, batmat::linalg::with_cached_access.
void batmat::linalg::micro_kernels::hyhound::hyhound_diag_tail_microkernel(index_t kA_in_offset, index_t kA_in, index_t k, triangular_accessor< const T, Abi, SizeR< T, Abi > > W, uview< T, Abi, OL > L, uview< const T, Abi, OA > A_in, uview< T, Abi, OA > A_out, uview< const T, Abi, OB > B, uview< const T, Abi, StorageOrder::ColMajor > diag, Structure struc_L, int rotate_A) noexcept
References BATMAT_ASSUME, batmat::ops::cneg, General, batmat::linalg::micro_kernels::hyhound::detail::rotate, SizeR, UNROLL_FOR, Upper, batmat::linalg::with_cached_access, Zero.
std::pair< index_t, index_t > batmat::linalg::micro_kernels::hyhound::hyhound_W_size(view< T, Abi, OL > L)
Referenced by hyhound_diag_apply_register, hyhound_diag_register, batmat::linalg::hyhound_size_W.
void batmat::linalg::micro_kernels::hyhound::hyhound_diag_register(const view< T, Abi, OL > L, const view< T, Abi, OA > A, const view< const T, Abi > D) noexcept
Block hyperbolic Householder factorization update using register blocking.
This variant does not store the Householder representation W.
References batmat::Backward, BATMAT_ASSUME, batmat::linalg::uview< T, Abi, Order >::block, batmat::foreach_chunked, microkernel_full_lut, batmat::linalg::uview< T, Abi, Order >::middle_rows.
Referenced by batmat::linalg::detail::hyhound_diag, hyhound_diag_register.
void batmat::linalg::micro_kernels::hyhound::hyhound_diag_register(const view< T, Abi, OL > L, const view< T, Abi, OA > A, const view< const T, Abi > D, const view< T, Abi > W) noexcept
Block hyperbolic Householder factorization update using register blocking.
This variant stores the Householder representation W.
References batmat::Backward, BATMAT_ASSUME, batmat::foreach_chunked_merged, hyhound_diag_register, hyhound_W_size, microkernel_diag_lut.
void batmat::linalg::micro_kernels::hyhound::hyhound_diag_apply_register(const view< T, Abi, OL > L, const view< const T, Abi, OA > Ain, const view< T, Abi, OA > Aout, const view< const T, Abi, OA > B, const view< const T, Abi > D, const view< const T, Abi > W, index_t kA_in_offset) noexcept
Apply a block hyperbolic Householder transformation.
References batmat::Backward, BATMAT_ASSUME, batmat::foreach_chunked_merged, hyhound_diag_apply_register, hyhound_W_size.
Referenced by hyhound_diag_apply_register.
void batmat::linalg::micro_kernels::hyhound::hyhound_diag_2_register(const view< T, Abi, OL1 > L11, const view< T, Abi, OA1 > A1, const view< T, Abi, OL2 > L21, const view< T, Abi, OA2 > A2, const view< const T, Abi > D) noexcept
Same as hyhound_diag_register but for two block rows at once.
References batmat::Backward, BATMAT_ASSUME, batmat::foreach_chunked_merged, hyhound_diag_2_register.
Referenced by batmat::linalg::detail::hyhound_diag_2, hyhound_diag_2_register.
void batmat::linalg::micro_kernels::hyhound::hyhound_diag_cyclic_register(const view< T, Abi, OL > L11, const view< T, Abi, OW > A1, const view< T, Abi, OY > L21, const view< const T, Abi, OW > A22, const view< T, Abi, OW > A2_out, const view< T, Abi, OU > L31, const view< const T, Abi, OW > A31, const view< T, Abi, OW > A3_out, const view< const T, Abi > D) noexcept
Performs a factorization update of the following matrix:
[ A11 A12 | L11 ] [ 0 0 | L11 ] [ 0 A22 | L21 ] Q = [ 21 22 | L21 ] [ A31 0 | L31 ] [ 31 32 | L31 ]
References batmat::Backward, BATMAT_ASSUME, batmat::foreach_chunked_merged, hyhound_diag_cyclic_register.
Referenced by batmat::linalg::detail::hyhound_diag_cyclic, hyhound_diag_cyclic_register.
void batmat::linalg::micro_kernels::hyhound::hyhound_diag_riccati_register(const view< T, Abi, OL > L11, const view< T, Abi, OA > A1, const view< T, Abi, OL > L21, const view< const T, Abi, OA > A2, const view< T, Abi, OA > A2_out, const view< T, Abi, OLu > Lu1, const view< T, Abi, OAu > Au_out, const view< const T, Abi > D, bool shift_A_out) noexcept
Performs a factorization update of the following matrix:
[ A1 | L11 ] [ 0 | L11 ] [ A2 | L21 ] Q = [ 2 | L21 ] [ 0 | Lu1 ] [ u | Lu1 ] where Lu1 and Lu1 are upper triangular
References batmat::Backward, BATMAT_ASSUME, batmat::foreach_chunked_merged, hyhound_diag_riccati_register.
Referenced by batmat::linalg::detail::hyhound_diag_riccati, hyhound_diag_riccati_register.