batmat::linalg::detail::syomv
void batmat::linalg::detail::syomv::syomv(view< const T, Abi, OA > A, view< const T, Abi, OB > B, view< T, Abi, OD > D)
References BATMAT_ASSERT, syomv, batmat::linalg::micro_kernels::syomv::syomv_register.
Referenced by syomv, batmat::linalg::syomv, batmat::linalg::syomv_neg.