batmat::datapar
using batmat::datapar::simd = stdx::simd<Tp, Abi>
using batmat::datapar::deduced_abi = stdx::simd_abi::deduce_t<Tp, Np>
using batmat::datapar::deduced_simd = simd<Tp, deduced_abi<Tp, Np>>
using batmat::datapar::simd_size = stdx::simd_size<Tp, Abi>
using batmat::datapar::simd_align = stdx::memory_alignment<simd<Tp, Abi>>
using batmat::datapar::rebind_simd_t = stdx::rebind_simd_t<T, V>
using batmat::datapar::scalar_abi = deduced_abi<Tp, 1>
V batmat::datapar::unaligned_load(const typename V::value_type *p)
V batmat::datapar::aligned_load(const typename V::value_type *p)
Referenced by batmat::linalg::template view< T, Order >::aligned_load, from_values, batmat::linalg::micro_kernels::hyhound::triangular_accessor< T, Abi, R >::load, batmat::linalg::micro_kernels::potrf::trsm_copy_microkernel.
void batmat::datapar::unaligned_store(V v, typename V::value_type *p)
void batmat::datapar::aligned_store(V v, typename V::value_type *p)
Referenced by batmat::linalg::template view< T, Order >::aligned_store, batmat::linalg::detail::compress_masks, batmat::linalg::micro_kernels::potrf::potrf_copy_microkernel, batmat::linalg::micro_kernels::hyhound::triangular_accessor< T, Abi, R >::store.
void batmat::datapar::masked_aligned_store(V v, typename V::mask_type m, typename V::value_type *p)
Referenced by batmat::linalg::template view< T, Order >::aligned_store.
auto batmat::datapar::to_intrin(V v)
V batmat::datapar::from_values(auto... values)
References aligned_load.