batmat::linalg::Structured
MatrixStructure batmat::linalg::Structured< M, S >::structure
M batmat::linalg::Structured< M, S >::value
Referenced by batmat::linalg::Structured< M, S >::Structured, batmat::linalg::copy, batmat::linalg::fill, batmat::linalg::hyhound_diag, batmat::linalg::hyhound_diag, batmat::linalg::hyhound_diag_2, batmat::linalg::hyhound_diag_cyclic, batmat::linalg::hyhound_diag_riccati, batmat::linalg::hyhound_sign, batmat::linalg::hyhound_size_W, batmat::linalg::potrf, batmat::linalg::potrf, batmat::linalg::Structured< M, S >::ref, batmat::linalg::symm_add, batmat::linalg::symv, batmat::linalg::symv_add, batmat::linalg::symv_neg, batmat::linalg::symv_sub, batmat::linalg::syomv, batmat::linalg::syomv_neg, batmat::linalg::syrk, batmat::linalg::syrk, batmat::linalg::syrk_add, batmat::linalg::syrk_add_potrf, batmat::linalg::syrk_diag_add, batmat::linalg::syrk_diag_add_potrf, batmat::linalg::syrk_neg, batmat::linalg::syrk_neg, batmat::linalg::syrk_sub, batmat::linalg::syrk_sub_potrf, batmat::linalg::Structured< M, S >::transposed, batmat::linalg::Structured< M, S >::transposed, batmat::linalg::trmm, batmat::linalg::trmm_add, batmat::linalg::trmm_neg, batmat::linalg::trmm_sub, batmat::linalg::trtri, batmat::linalg::trtri.
batmat::linalg::Structured< M, S >::Structured(M &&m)
References batmat::linalg::General, batmat::linalg::Structured< M, S >::value.
Referenced by batmat::linalg::Structured< M, S >::Structured, batmat::linalg::Structured< M, S >::Structured, batmat::linalg::Structured< M, S >::ref.
batmat::linalg::Structured< M, S >::Structured(const Structured &)=default
References batmat::linalg::Structured< M, S >::Structured.
batmat::linalg::Structured< M, S >::Structured(Structured &&)=default
References batmat::linalg::Structured< M, S >::Structured.
auto batmat::linalg::Structured< M, S >::transposed() const &
References batmat::linalg::Structured< M, S >::value.
Referenced by batmat::linalg::trtri, batmat::linalg::trtri.
auto batmat::linalg::Structured< M, S >::transposed() &&
References batmat::linalg::Structured< M, S >::value.
auto batmat::linalg::Structured< M, S >::ref()
References batmat::linalg::Structured< M, S >::Structured, batmat::linalg::Structured< M, S >::value.
Referenced by batmat::linalg::symm_add, batmat::linalg::symv_add, batmat::linalg::symv_sub, batmat::linalg::syrk_add, batmat::linalg::syrk_add_potrf, batmat::linalg::syrk_diag_add_potrf, batmat::linalg::syrk_sub, batmat::linalg::syrk_sub_potrf, batmat::linalg::trmm, batmat::linalg::trmm.