topic-linalg
index_t batmat::linalg::compress_masks(VA &&Ain, VS &&Sin, VAo &&Aout, VSo &&Sout)
References batmat::linalg::detail::compress_masks, batmat::linalg::simdify.
index_t batmat::linalg::compress_masks_count(VS &&Sin)
References batmat::linalg::detail::compress_masks_count, batmat::linalg::simdify.
index_t batmat::linalg::compress_masks_sqrt(VA &&Ain, VS &&Sin, VAo &&Aout)
References batmat::linalg::detail::compress_masks_sqrt, batmat::linalg::simdify.
index_t batmat::linalg::compress_masks_sqrt(VA &&Ain, VS &&Sin, VAo &&Aout, VSo &&Sout)
References batmat::linalg::detail::compress_masks_sqrt, batmat::linalg::simdify.
void batmat::linalg::copy(VA &&A, VB &&B, Opts... opts)
B = A.
References batmat::linalg::detail::copy::apply_options, batmat::linalg::copy, batmat::linalg::detail::copy::copy, batmat::linalg::simdify.
Referenced by batmat::linalg::copy, batmat::linalg::copy.
void batmat::linalg::copy(Structured< VA, S > A, Structured< VB, S > B, Opts... opts)
B = A.
References batmat::linalg::detail::copy::apply_options, batmat::linalg::copy, batmat::linalg::detail::copy::copy, batmat::linalg::simdify, batmat::linalg::Structured< M, S >::value.
void batmat::linalg::fill(simdified_value_t< VB > a, VB &&B)
B = a.
References batmat::linalg::detail::copy::fill, batmat::linalg::fill, batmat::linalg::simdify.
Referenced by batmat::linalg::fill, batmat::linalg::fill, main.
void batmat::linalg::fill(simdified_value_t< VB > a, Structured< VB, S > B)
B = a.
References batmat::linalg::detail::copy::fill, batmat::linalg::fill, batmat::linalg::simdify, batmat::linalg::Structured< M, S >::value.
void batmat::linalg::scale(T alpha, Vx &&x, Vz &&z)
Multiply a vector by a scalar z = αx.
References batmat::linalg::simdify.
void batmat::linalg::scale(T alpha, Vx &&x)
Multiply a vector by a scalar x = αx.
References batmat::linalg::simdify.
void batmat::linalg::hadamard(Vx &&x, Vy &&y, Vz &&z)
Compute the Hadamard (elementwise) product of two vectors z = x ⊙ y.
References batmat::linalg::simdify.
void batmat::linalg::hadamard(Vx &&x, Vy &&y)
Compute the Hadamard (elementwise) product of two vectors x = x ⊙ y.
References batmat::linalg::simdify.
void batmat::linalg::clamp(Vx &&x, Vlo &&lo, Vhi &&hi, Vz &&z)
Elementwise clamping z = max(lo, min(x, hi)).
References batmat::linalg::simdify.
void batmat::linalg::clamp_resid(Vx &&x, Vlo &&lo, Vhi &&hi, Vz &&z)
Elementwise clamping residual z = x - max(lo, min(x, hi)).
References batmat::linalg::simdify.
void batmat::linalg::clamp(Vx &&x, simdified_simd_t< Vx > lo, simdified_simd_t< Vx > hi, Vz &&z)
Elementwise clamping z = max(lo, min(x, hi)), with scalar lo and hi.
References batmat::linalg::simdify.
void batmat::linalg::axpby(Ta alpha, Vx &&x, Tb beta, Vy &&y, Vz &&z)
Add scaled vector z = αx + βy.
References batmat::linalg::simdify.
Referenced by batmat::linalg::axpy.
void batmat::linalg::axpby(Ta alpha, Vx &&x, Tb beta, Vy &&y)
Add scaled vector y = αx + βy.
References batmat::linalg::simdify.
void batmat::linalg::axpy(Vy &&y, const std::array< simdified_simd_t< Vy >, sizeof...(Vx)> &alphas, Vx &&...x)
Add scaled vector y = ∑ᵢ αᵢxᵢ + βy.
References batmat::linalg::simdify.
void batmat::linalg::axpy(Ta alpha, Vx &&x, Vy &&y, Vz &&z)
Add scaled vector z = αx + y.
References batmat::linalg::axpby.
void batmat::linalg::axpy(Ta alpha, Vx &&x, Vy &&y)
Add scaled vector y = αx + βy (where β is a compile-time constant).
References batmat::linalg::simdify.
void batmat::linalg::negate(VA &&A, VB &&B, with_rotate_t< Rotate >={})
Negate a matrix or vector B = -A.
void batmat::linalg::negate(VA &&A, with_rotate_t< Rotate >={})
Negate a matrix or vector A = -A.
void batmat::linalg::sub(VA &&A, VB &&B, VC &&C, with_rotate_t< Rotate >={})
Subtract two matrices or vectors C = A - B. Rotate affects B.
void batmat::linalg::sub(VA &&A, VB &&B, with_rotate_t< Rotate >={})
Subtract two matrices or vectors A = A - B. Rotate affects B.
void batmat::linalg::add(VA &&A, VB &&B, VC &&C, with_rotate_t< Rotate >={})
Add two matrices or vectors C = A + B. Rotate affects B.
Referenced by batmat::linalg::flops::hyh_square.
void batmat::linalg::add(VA &&A, VB &&B, with_rotate_t< Rotate >={})
Add two matrices or vectors A = A + B. Rotate affects B.
void batmat::linalg::for_each_elementwise(F &&fun, VA &&A, VAs &&...As)
Apply a function to all elements of the given matrices or vectors.
References batmat::linalg::simdify.
void batmat::linalg::transform_elementwise(F &&fun, VA &&A, VAs &&...As)
Apply a function to all elements of the given matrices or vectors, storing the result in the first argument.
References batmat::linalg::simdify.
void batmat::linalg::transform2_elementwise(F &&fun, VA &&A, VB &&B, VAs &&...As)
Apply a function to all elements of the given matrices or vectors, storing the results in the first two arguments.
References batmat::linalg::simdify.
void batmat::linalg::transform_n_elementwise(F &&fun, std::tuple< VAs... > As, VBs &&...Bs)
Apply a function to all elements of the given matrices or vectors, storing the results in the tuple of matrices given as the first argument.
References batmat::linalg::simdify.
void batmat::linalg::transform_n_diag(F &&fun, std::tuple< VAs... > As, VBs &&...Bs)
Apply a function to all elements of the given vectors and the diagonal elements of the given square matrices, storing the results in the tuple of vectors or matrices given as the first argument.
Most efficient if only the first argument contains matrices, and all other arguments are column vectors.
References BATMAT_ASSERT, batmat::linalg::simdify.
void batmat::linalg::copy_diag(VA &&A, VB &&B)
Copy the diagonal elements of a matrix.
The arguments A and B must either be square matrices or vectors. This function supports setting the diagonal of a matrix to the values of a vector, copying the diagonal of one matrix to the diagonal of another, or copying the diagonal elements of a matrix to a vector.
References BATMAT_ASSERT, batmat::linalg::simdify.
void batmat::linalg::add_diag(VA &&A, VB &&b, VC &&C)
C = A + diag(b).
References BATMAT_ASSERT, batmat::linalg::simdify.
Referenced by batmat::linalg::add_diag.
void batmat::linalg::add_diag(VA &&A, VB &&b)
A += diag(b).
References batmat::linalg::add_diag.
void batmat::linalg::multi::scale(T alpha, Vx &&x, Vz &&z)
Multiply a vector by a scalar z = αx.
void batmat::linalg::multi::scale(T alpha, Vx &&x)
Multiply a vector by a scalar x = αx.
void batmat::linalg::multi::hadamard(Vx &&x, Vy &&y, Vz &&z)
Compute the Hadamard (elementwise) product of two vectors z = x ⊙ y.
void batmat::linalg::multi::hadamard(Vx &&x, Vy &&y)
Compute the Hadamard (elementwise) product of two vectors x = x ⊙ y.
void batmat::linalg::multi::clamp(Vx &&x, Vlo &&lo, Vhi &&hi, Vz &&z)
Elementwise clamping z = max(lo, min(x, hi)).
void batmat::linalg::multi::clamp_resid(Vx &&x, Vlo &&lo, Vhi &&hi, Vz &&z)
Elementwise clamping residual z = x - max(lo, min(x, hi)).
void batmat::linalg::multi::clamp(Vx &&x, simdified_simd_t< Vx > lo, simdified_simd_t< Vx > hi, Vz &&z)
Elementwise clamping z = max(lo, min(x, hi)), with scalar lo and hi.
void batmat::linalg::multi::axpby(Ta alpha, Vx &&x, Tb beta, Vy &&y, Vz &&z)
Add scaled vector z = αx + βy.
void batmat::linalg::multi::axpby(Ta alpha, Vx &&x, Tb beta, Vy &&y)
Add scaled vector y = αx + βy.
void batmat::linalg::multi::axpy(Vy &&y, const std::array< simdified_simd_t< Vy >, sizeof...(Vx)> &alphas, Vx &&...x)
Add scaled vector y = ∑ᵢ αᵢxᵢ + βy.
void batmat::linalg::multi::axpy(Ta alpha, Vx &&x, Vy &&y, Vz &&z)
Add scaled vector z = αx + y.
void batmat::linalg::multi::axpy(Ta alpha, Vx &&x, Vy &&y)
Add scaled vector y = αx + βy (where β is a compile-time constant).
void batmat::linalg::multi::negate(VA &&A, VB &&B, with_rotate_t< Rotate > rot={})
Negate a matrix or vector B = -A.
void batmat::linalg::multi::negate(VA &&A, with_rotate_t< Rotate > rot={})
Negate a matrix or vector A = -A.
void batmat::linalg::multi::sub(VA &&A, VB &&B, VC &&C, with_rotate_t< Rotate > rot={})
Subtract two matrices or vectors C = A - B. Rotate affects B.
void batmat::linalg::multi::sub(VA &&A, VB &&B, with_rotate_t< Rotate > rot={})
Subtract two matrices or vectors A = A - B. Rotate affects B.
void batmat::linalg::multi::add(VA &&A, VB &&B, VC &&C, with_rotate_t< Rotate > rot={})
Add two matrices or vectors C = A + B. Rotate affects B.
void batmat::linalg::multi::add(VA &&A, VB &&B, with_rotate_t< Rotate > rot={})
Add two matrices or vectors A = A + B. Rotate affects B.
void batmat::linalg::multi::for_each_elementwise(F &&fun, VA &&A, VAs &&...As)
Apply a function to all elements of the given matrices or vectors.
void batmat::linalg::multi::transform_elementwise(F &&fun, VA &&A, VAs &&...As)
Apply a function to all elements of the given matrices or vectors, storing the result in the first argument.
void batmat::linalg::multi::transform2_elementwise(F &&fun, VA &&A, VB &&B, VAs &&...As)
Apply a function to all elements of the given matrices or vectors, storing the results in the first two arguments.
void batmat::linalg::multi::transform_n_elementwise(F &&fun, std::tuple< VAs... > As, VBs &&...Bs)
Apply a function to all elements of the given matrices or vectors, storing the results in the tuple of matrices given as the first argument.
void batmat::linalg::gemm_diag(VA &&A, VB &&B, VD &&D, Vd &&d, Opts... opts)
D = A diag(d) B.
References batmat::linalg::detail::gemm_diag::apply_options, batmat::linalg::detail::gemm_diag::gemm_diag, batmat::linalg::simdify.
void batmat::linalg::gemm_diag_add(VA &&A, VB &&B, VC &&C, VD &&D, Vd &&d, Opts... opts)
D = C + A diag(d) B.
References batmat::linalg::detail::gemm_diag::apply_options, batmat::linalg::detail::gemm_diag::gemm_diag, batmat::linalg::simdify.
Referenced by batmat::linalg::gemm_diag_add.
void batmat::linalg::gemm_diag_add(VA &&A, VB &&B, VD &&D, Vd &&d, Opts... opts)
D += A diag(d) B.
References batmat::linalg::gemm_diag_add.
void batmat::linalg::gemm_diag_sub(VA &&A, VB &&B, VC &&C, VD &&D, Vd &&d, Opts... opts)
D = C - A diag(d) B.
References batmat::linalg::detail::gemm_diag::apply_options, batmat::linalg::detail::gemm_diag::gemm_diag, batmat::linalg::simdify.
Referenced by batmat::linalg::gemm_diag_sub.
void batmat::linalg::gemm_diag_sub(VA &&A, VB &&B, VD &&D, Vd &&d, Opts... opts)
D -= A diag(d) B.
References batmat::linalg::gemm_diag_sub.
void batmat::linalg::syrk_diag(VA &&A, Structured< VD, SC > D, Vd &&d, Opts... opts)
D = A diag(d) Aᵀ with D symmetric.
References batmat::linalg::detail::gemm_diag::apply_options, batmat::linalg::detail::gemm_diag::gemm_diag, batmat::linalg::General, batmat::linalg::simdify, batmat::linalg::Structured< M, S >::value.
void batmat::linalg::syrk_diag_add(VA &&A, Structured< VC, SC > C, Structured< VD, SC > D, Vd &&d, Opts... opts)
D = C + A diag(d) Aᵀ with C, D symmetric.
References batmat::linalg::detail::gemm_diag::apply_options, batmat::linalg::detail::gemm_diag::gemm_diag, batmat::linalg::General, batmat::linalg::simdify, batmat::linalg::Structured< M, S >::value.
Referenced by batmat::linalg::syrk_diag_add.
void batmat::linalg::syrk_diag_add(VA &&A, Structured< VD, SC > D, Vd &&d, Opts... opts)
D += A diag(d) Aᵀ with D symmetric.
References batmat::linalg::syrk_diag_add.
void batmat::linalg::syrk_diag_sub(VA &&A, Structured< VC, SC > C, Structured< VD, SC > D, Vd &&d, Opts... opts)
D = C - A diag(d) Aᵀ with C, D symmetric.
References batmat::linalg::detail::gemm_diag::apply_options, batmat::linalg::detail::gemm_diag::gemm_diag, batmat::linalg::General, batmat::linalg::simdify, batmat::linalg::Structured< M, S >::value.
Referenced by batmat::linalg::syrk_diag_sub.
void batmat::linalg::syrk_diag_sub(VA &&A, Structured< VD, SC > D, Vd &&d, Opts... opts)
D -= A diag(d) Aᵀ with D symmetric.
References batmat::linalg::syrk_diag_sub.
void batmat::linalg::gemm(VA &&A, VB &&B, VD &&D, TilingOptions packing={}, Opts... opts)
D = A B.
void batmat::linalg::gemm_neg(VA &&A, VB &&B, VD &&D, TilingOptions packing={}, Opts... opts)
D = -A B.
void batmat::linalg::gemm_add(VA &&A, VB &&B, VC &&C, VD &&D, TilingOptions packing={}, Opts... opts)
D = C + A B.
void batmat::linalg::gemm_add(VA &&A, VB &&B, VD &&D, TilingOptions packing={}, Opts... opts)
D += A B.
void batmat::linalg::gemm_sub(VA &&A, VB &&B, VC &&C, VD &&D, TilingOptions packing={}, Opts... opts)
D = C - A B.
void batmat::linalg::gemm_sub(VA &&A, VB &&B, VD &&D, TilingOptions packing={}, Opts... opts)
D -= A B.
void batmat::linalg::syrk(Structured< VA, SA > A, Structured< VD, SD > D, Opts... opts)
D = A Aᵀ with D symmetric.
References batmat::linalg::detail::apply_gemm_options, batmat::linalg::detail::gemmt, batmat::linalg::General, batmat::linalg::simdify, batmat::linalg::transpose, batmat::linalg::Structured< M, S >::value.
Referenced by main, batmat::linalg::syrk.
void batmat::linalg::syrk(TA &&A, Structured< VD, SD > D, Opts... opts)
D = A Aᵀ with D symmetric.
References batmat::linalg::syrk.
void batmat::linalg::syrk(Structured< VD, SD > D, Opts... opts)
D = D Dᵀ with D triangular on input and symmetric on output.
References batmat::linalg::detail::apply_gemm_options, batmat::linalg::detail::gemmt, batmat::linalg::General, batmat::linalg::simdify, batmat::linalg::transpose, batmat::linalg::Structured< M, S >::value.
void batmat::linalg::syrk_neg(Structured< VA, SA > A, Structured< VD, SD > D, Opts... opts)
D = -A Aᵀ with D symmetric.
References batmat::linalg::detail::apply_gemm_options, batmat::linalg::detail::gemmt, batmat::linalg::General, batmat::linalg::simdify, batmat::linalg::transpose, batmat::linalg::Structured< M, S >::value.
Referenced by batmat::linalg::syrk_neg.
void batmat::linalg::syrk_neg(TA &&A, Structured< VD, SD > D, Opts... opts)
D = A Aᵀ with D symmetric.
References batmat::linalg::syrk_neg.
void batmat::linalg::syrk_neg(Structured< VD, SD > D, Opts... opts)
D = -D Dᵀ with D triangular on input and symmetric on output.
References batmat::linalg::detail::apply_gemm_options, batmat::linalg::detail::gemmt, batmat::linalg::General, batmat::linalg::simdify, batmat::linalg::transpose, batmat::linalg::Structured< M, S >::value.
void batmat::linalg::syrk_add(VA &&A, Structured< VC, SD > C, Structured< VD, SD > D, Opts... opts)
D = C + A Aᵀ with C, D symmetric.
References batmat::linalg::detail::apply_gemm_options, batmat::linalg::detail::gemmt, batmat::linalg::General, batmat::linalg::simdify, batmat::linalg::Structured< M, S >::value.
Referenced by batmat::linalg::syrk_add.
void batmat::linalg::syrk_add(VA &&A, Structured< VD, SD > D, Opts... opts)
D += A Aᵀ with D symmetric.
References batmat::linalg::Structured< M, S >::ref, batmat::linalg::syrk_add.
void batmat::linalg::syrk_sub(VA &&A, Structured< VC, SD > C, Structured< VD, SD > D, Opts... opts)
D = C - A Aᵀ with C, D symmetric.
References batmat::linalg::detail::apply_gemm_options, batmat::linalg::detail::gemmt, batmat::linalg::General, batmat::linalg::simdify, batmat::linalg::Structured< M, S >::value.
Referenced by batmat::linalg::syrk_sub.
void batmat::linalg::syrk_sub(VA &&A, Structured< VD, SD > D, Opts... opts)
D -= A Aᵀ with D symmetric.
References batmat::linalg::Structured< M, S >::ref, batmat::linalg::syrk_sub.
void batmat::linalg::trmm(Structured< VA, SA > A, Structured< VB, SB > B, Structured< VD, SD > D, Opts... opts)
D = A B with A and/or B triangular.
References batmat::linalg::detail::apply_gemm_options, batmat::linalg::simdify, batmat::linalg::detail::trmm, batmat::linalg::Structured< M, S >::value.
Referenced by batmat::linalg::trmm, batmat::linalg::trmm, batmat::linalg::trmm.
void batmat::linalg::trmm(TA &&A, TB &&B, TD &&D, Opts... opts)
D = A B with A and/or B triangular.
References batmat::linalg::trmm.
void batmat::linalg::trmm(Structured< VA, SA > A, VD &&D, Opts... opts)
D = A D with A triangular.
References batmat::linalg::Structured< M, S >::ref, batmat::linalg::trmm.
void batmat::linalg::trmm(VD &&D, Structured< VB, SB > B, Opts... opts)
D = D B with B triangular.
References batmat::linalg::Structured< M, S >::ref, batmat::linalg::trmm.
void batmat::linalg::trmm_neg(Structured< VA, SA > A, Structured< VB, SB > B, Structured< VD, SD > D, Opts... opts)
D = -A B with A and/or B triangular.
References batmat::linalg::detail::apply_gemm_options, batmat::linalg::simdify, batmat::linalg::detail::trmm, batmat::linalg::Structured< M, S >::value.
Referenced by batmat::linalg::trmm_neg.
void batmat::linalg::trmm_neg(TA &&A, TB &&B, TD &&D, Opts... opts)
D = -A B with A and/or B triangular.
References batmat::linalg::trmm_neg.
void batmat::linalg::trmm_add(Structured< VA, SA > A, Structured< VB, SB > B, Structured< VC, SD > C, Structured< VD, SD > D, Opts... opts)
D = C + A B with A and/or B triangular.
References batmat::linalg::detail::apply_gemm_options, batmat::linalg::simdify, batmat::linalg::detail::trmm, batmat::linalg::Structured< M, S >::value.
Referenced by batmat::linalg::trmm_add.
void batmat::linalg::trmm_add(TA &&A, TB &&B, TC &&C, TD &&D, Opts... opts)
D = C + A B with A and/or B triangular.
References batmat::linalg::trmm_add.
void batmat::linalg::trmm_sub(Structured< VA, SA > A, Structured< VB, SB > B, Structured< VC, SD > C, Structured< VD, SD > D, Opts... opts)
D = C - A B with A and/or B triangular.
References batmat::linalg::detail::apply_gemm_options, batmat::linalg::simdify, batmat::linalg::detail::trmm, batmat::linalg::Structured< M, S >::value.
Referenced by batmat::linalg::trmm_sub.
void batmat::linalg::trmm_sub(TA &&A, TB &&B, TC &&C, TD &&D, Opts... opts)
D = C - A B with A and/or B triangular.
References batmat::linalg::trmm_sub.
void batmat::linalg::gemv(VA &&A, VB &&B, VD &&D, Opts... opts)
d = A b
References batmat::linalg::detail::apply_gemv_options, batmat::linalg::detail::gemv, batmat::linalg::simdify.
void batmat::linalg::gemv_neg(VA &&A, VB &&B, VD &&D, Opts... opts)
d = -A b
References batmat::linalg::detail::apply_gemv_options, batmat::linalg::detail::gemv, batmat::linalg::simdify.
void batmat::linalg::gemv_add(VA &&A, VB &&B, VC &&C, VD &&D, Opts... opts)
d = c + A b
References batmat::linalg::detail::apply_gemv_options, batmat::linalg::detail::gemv, batmat::linalg::simdify.
Referenced by batmat::linalg::gemv_add.
void batmat::linalg::gemv_add(VA &&A, VB &&B, VD &&D, Opts... opts)
d = d + A b
References batmat::linalg::gemv_add.
void batmat::linalg::gemv_sub(VA &&A, VB &&B, VC &&C, VD &&D, Opts... opts)
d = c - A b
References batmat::linalg::detail::apply_gemv_options, batmat::linalg::detail::gemv, batmat::linalg::simdify.
Referenced by batmat::linalg::gemv_sub.
void batmat::linalg::gemv_sub(VA &&A, VB &&B, VD &&D, Opts... opts)
d = d - A b
References batmat::linalg::gemv_sub.
void batmat::linalg::hyhound_diag(Structured< VL, SL > L, VA &&A, Vd &&d)
Update Cholesky factor L using low-rank term A diag(d) Aᵀ.
References batmat::linalg::detail::hyhound_diag, batmat::linalg::LowerTriangular, batmat::linalg::simdify, batmat::linalg::Structured< M, S >::value.
void batmat::linalg::hyhound_diag(Structured< VL, SL > L, VA &&A, Vd &&d, VW &&W)
Update Cholesky factor L using low-rank term A diag(d) Aᵀ, with full Householder representation.
References batmat::linalg::detail::hyhound_diag, batmat::linalg::LowerTriangular, batmat::linalg::simdify, batmat::linalg::Structured< M, S >::value.
auto batmat::linalg::hyhound_size_W(Structured< VL, SL > L)
Get the size of the storage for the matrix W returned by hyhound_diag(Structured<VL,SL>, VA&&, Vd&&, VW&&).
References batmat::linalg::micro_kernels::hyhound::hyhound_W_size, batmat::linalg::simdify, batmat::linalg::Structured< M, S >::value.
void batmat::linalg::hyhound_diag_apply(VL &&L, VA &&A, VD &&D, VB &&B, Vd &&d, VW &&W, index_t kA_in_offset=0)
Apply Householder transformation generated by hyhound_diag, computing (L̃, D) = (L, A) Q̆.
L Part of the Cholesky factor to be updated (rectangular). Overwritten by L̃. A Update matrix (rectangular). D Updated update matrix (rectangular). B Householder reflector vectors returned by hyhound_diag. d Diagonal update matrix. W Householder representation returned by hyhound_diag. kA_in_offset If A is smaller than D, A is implicitly padded with zero columns: the offset of the nonzero part of A in the padded matrix can be specified using kA_in_offset.
References batmat::linalg::detail::hyhound_diag_apply, batmat::linalg::simdify.
void batmat::linalg::hyhound_diag_apply(VL &&L, VA &&A, VB &&B, Vd &&d, VW &&W)
Apply Householder transformation generated by hyhound_diag, computing (L̃, Ã) = (L, A) Q̆.
L Part of the Cholesky factor to be updated (rectangular). Overwritten by L̃. A Update matrix (rectangular). Overwritten by Ã. B Householder reflector vectors returned by hyhound_diag. d Diagonal update matrix. W Householder representation returned by hyhound_diag.
References batmat::linalg::detail::hyhound_diag_apply, batmat::linalg::simdify.
void batmat::linalg::hyhound_sign(Structured< VL, SL > L, VA &&A, Vd &&d)
Update Cholesky factor L using low-rank term A diag(copysign(1, d)) Aᵀ, where d contains only ±0 values.
References batmat::linalg::detail::hyhound_diag, batmat::linalg::simdify, batmat::linalg::Structured< M, S >::value.
void batmat::linalg::hyhound_diag_2(Structured< VL1, SL > L1, VA1 &&A1, VL2 &&L2, VA2 &&A2, Vd &&d)
Update Cholesky factor L using low-rank term A diag(d) Aᵀ, where L and A are stored as two separate block rows.
\[ L = \begin{pmatrix} L_{11} \\ L_{21} \end{pmatrix}, \quad A = \begin{pmatrix} A_{1} \\ A_{2} \end{pmatrix}. \]
References batmat::linalg::detail::hyhound_diag_2, batmat::linalg::simdify, batmat::linalg::Structured< M, S >::value.
void batmat::linalg::hyhound_diag_cyclic(Structured< VL11, SL > L11, VA1 &&A1, VL21 &&L21, VA2 &&A22, VA2o &&A2_out, VU &&L31, VA3 &&A31, VA3o &&A3_out, Vd &&d)
Update structured Cholesky factor L using structured low-rank term A diag(d) Aᵀ,.
\[ L = \begin{pmatrix} L_{11} \\ L_{21} \\ L_{31} \end{pmatrix}, \quad A = \begin{pmatrix} A_{11} & A_{12} \\ 0 & A_{22} \\ A_{31} & 0 \end{pmatrix}, \quad \tilde A = \begin{pmatrix} 0 \\ \tilde A_{2} \\ \tilde A_{3} \end{pmatrix}. \]
References batmat::linalg::detail::hyhound_diag_cyclic, batmat::linalg::simdify, batmat::linalg::Structured< M, S >::value.
void batmat::linalg::hyhound_diag_riccati(Structured< VL11, SL > L11, VA1 &&A1, VL21 &&L21, VA2 &&A2, VA2o &&A2_out, VLu1 &&Lu1, VAuo &&Au_out, Vd &&d, bool shift_A_out=false)
Update structured Cholesky factor L using structured low-rank term A diag(d) Aᵀ,.
\[ L = \begin{pmatrix} L_{11} \\ L_{21} \\ L_{u} \end{pmatrix}, \quad A = \begin{pmatrix} A_{1} \\ A_{2} \\ 0 \end{pmatrix}, \quad \tilde A = \begin{pmatrix} 0 \\ \tilde A_{2} \\ \tilde A_{u} \end{pmatrix}. \] The shift_A_out parameter indicates whether the output matrix A2_out should be shifted along the batch dimension. This is used in the Cyqlone solver.
References batmat::linalg::detail::hyhound_diag_riccati, batmat::linalg::simdify, batmat::linalg::Structured< M, S >::value.
void batmat::linalg::syrk_add_potrf(VA &&A, Structured< VC, SC > C, Structured< VD, SC > D, simdified_value_t< VA > regularization=0)
D = chol(C + AAᵀ) with C symmetric, D triangular.
References batmat::linalg::detail::potrf, batmat::linalg::simdify, batmat::linalg::Structured< M, S >::value.
Referenced by batmat::linalg::syrk_add_potrf.
void batmat::linalg::syrk_add_potrf(VA &&A, Structured< VD, SC > D)
D = chol(D + AAᵀ) with D symmetric/triangular.
References batmat::linalg::Structured< M, S >::ref, batmat::linalg::syrk_add_potrf.
void batmat::linalg::syrk_sub_potrf(VA &&A, Structured< VC, SC > C, Structured< VD, SC > D, simdified_value_t< VA > regularization=0)
D = chol(C - AAᵀ) with C symmetric, D triangular.
References batmat::linalg::detail::potrf, batmat::linalg::simdify, batmat::linalg::Structured< M, S >::value.
Referenced by batmat::linalg::syrk_sub_potrf.
void batmat::linalg::syrk_sub_potrf(VA &&A, Structured< VD, SC > D, simdified_value_t< VA > regularization=0)
D = chol(D - AAᵀ) with D symmetric/triangular.
References batmat::linalg::Structured< M, S >::ref, batmat::linalg::syrk_sub_potrf.
void batmat::linalg::syrk_diag_add_potrf(VA &&A, Structured< VC, SC > C, Structured< VD, SC > D, Vd &&d, simdified_value_t< VA > regularization=0)
D = chol(C + A diag(d) Aᵀ) with C symmetric, D triangular.
References batmat::linalg::detail::potrf, batmat::linalg::simdify, batmat::linalg::Structured< M, S >::value.
Referenced by batmat::linalg::syrk_diag_add_potrf.
void batmat::linalg::syrk_diag_add_potrf(VA &&A, Structured< VD, SC > D, Vd &&d)
D = chol(D + A diag(d) Aᵀ) with D symmetric/triangular.
References batmat::linalg::Structured< M, S >::ref, batmat::linalg::syrk_diag_add_potrf.
void batmat::linalg::potrf(Structured< VC, SC > C, Structured< VD, SC > D, simdified_value_t< VC > regularization=0)
D = chol(C) with C symmetric, D triangular.
References batmat::linalg::detail::potrf, batmat::linalg::simdify, batmat::linalg::Structured< M, S >::value.
Referenced by main.
void batmat::linalg::potrf(Structured< VD, SD > D, simdified_value_t< VD > regularization=0)
D = chol(D) with D symmetric/triangular.
References batmat::linalg::detail::potrf, batmat::linalg::simdify, batmat::linalg::Structured< M, S >::value.
norms< simdified_value_t< Vx >, simdified_simd_t< Vx > >::result_simd batmat::linalg::vnorms_all(Vx &&x)
Compute the lane-wise norms (max, 1-norm, and 2-norm) of a batch of vectors.
References batmat::linalg::simdify.
Referenced by batmat::linalg::vnorm_1, batmat::linalg::vnorm_inf.
norms< simdified_value_t< Vx > >::result batmat::linalg::norms_all(Vx &&x)
Compute the norms (max, 1-norm, and 2-norm) of a vector.
References batmat::linalg::simdify.
Referenced by batmat::linalg::norm_1, batmat::linalg::norm_inf.
simdified_simd_t< Vx > batmat::linalg::vnorm_inf(Vx &&x)
Compute the lane-wise infinity norms of a batch of vectors.
References batmat::linalg::vnorms_all.
simdified_value_t< Vx > batmat::linalg::norm_inf(Vx &&x)
Compute the infinity norm of a vector.
References batmat::linalg::norms_all.
simdified_simd_t< Vx > batmat::linalg::vnorm_1(Vx &&x)
Compute the lane-wise 1-norms of a batch of vectors.
References batmat::linalg::vnorms_all.
simdified_value_t< Vx > batmat::linalg::norm_1(Vx &&x)
Compute the 1-norm of a vector.
References batmat::linalg::norms_all.
simdified_simd_t< Vx > batmat::linalg::vnorm_2_squared(Vx &&x)
Compute the lane-wise squared 2-norms of a batch of vectors.
References batmat::linalg::simdify.
Referenced by batmat::linalg::vnorm_2.
simdified_value_t< Vx > batmat::linalg::norm_2_squared(Vx &&x)
Compute the squared 2-norm of a vector.
References batmat::linalg::simdify.
Referenced by batmat::linalg::norm_2.
simdified_simd_t< Vx > batmat::linalg::vnorm_2(Vx &&x)
Compute the lane-wise 2-norms of a batch of vectors.
References batmat::linalg::vnorm_2_squared.
simdified_value_t< Vx > batmat::linalg::norm_2(Vx &&x)
Compute the 2-norm of a vector.
References batmat::linalg::norm_2_squared.
simdified_simd_t< Vx > batmat::linalg::vdot(Vx &&x, Vy &&y)
Compute the lane-wise dot products of two batches of vectors.
References batmat::linalg::simdify.
simdified_value_t< Vx > batmat::linalg::dot(Vx &&x, Vy &&y)
Compute the dot product of two vectors.
References batmat::linalg::simdify.
simdified_simd_t< Vw > batmat::linalg::weighted_vnorm_sq(Vw &&w, Va &&a)
∑ wᵢ aᵢ² (lane-wise).
References batmat::linalg::simdify.
simdified_value_t< Vw > batmat::linalg::weighted_norm_sq(Vw &&w, Va &&a)
∑ wᵢ aᵢ².
References batmat::linalg::simdify.
simdified_simd_t< Vw > batmat::linalg::weighted_vnorm_sq_diff(Vw &&w, Va &&a, Vb &&b)
∑ wᵢ(aᵢ - bᵢ)² (lane-wise).
References batmat::linalg::simdify.
simdified_value_t< Vw > batmat::linalg::weighted_norm_sq_diff(Vw &&w, Va &&a, Vb &&b)
∑ wᵢ(aᵢ - bᵢ)².
References batmat::linalg::simdify.
norms< simdified_value_t< Vx > >::result batmat::linalg::multi::norms_all(Vx &&x)
Compute the norms (max, 1-norm, and 2-norm) of a vector.
simdified_value_t< Vx > batmat::linalg::multi::norm_inf(Vx &&x)
Compute the infinity norm of a vector.
simdified_value_t< Vx > batmat::linalg::multi::norm_1(Vx &&x)
Compute the 1-norm of a vector.
simdified_value_t< Vx > batmat::linalg::multi::norm_2_squared(Vx &&x)
Compute the squared 2-norm of a vector.
simdified_value_t< Vx > batmat::linalg::multi::norm_2(Vx &&x)
Compute the 2-norm of a vector.
simdified_value_t< Vx > batmat::linalg::multi::dot(Vx &&x, Vy &&y)
Compute the dot product of two vectors.
simdified_value_t< Vw > batmat::linalg::multi::weighted_norm_sq(Vw &&w, Vx &&x)
∑ wᵢ xᵢ².
simdified_value_t< Vw > batmat::linalg::multi::weighted_norm_sq_difference(Vw &&w, Vx &&x, Vy &&y)
∑ wᵢ(xᵢ - yᵢ)².
norms< simdified_value_t< Vx >, simdified_simd_t< Vx > >::result_simd batmat::linalg::multi::vnorms_all(Vx &&x)
Compute the lane-wise norms (max, 1-norm, and 2-norm) of a batch of vectors.
simdified_simd_t< Vx > batmat::linalg::multi::vnorm_inf(Vx &&x)
Compute the lane-wise infinity norms of a batch of vectors.
simdified_simd_t< Vx > batmat::linalg::multi::vnorm_1(Vx &&x)
Compute the lane-wise 1-norms of a batch of vectors.
simdified_simd_t< Vx > batmat::linalg::multi::vnorm_2_squared(Vx &&x)
Compute the lane-wise squared 2-norms of a batch of vectors.
simdified_simd_t< Vx > batmat::linalg::multi::vnorm_2(Vx &&x)
Compute the lane-wise 2-norms of a batch of vectors.
simdified_simd_t< Vx > batmat::linalg::multi::vdot(Vx &&x, Vy &&y)
Compute the lane-wise dot products of two batches of vectors.
simdified_simd_t< Vw > batmat::linalg::multi::weighted_vnorm_sq(Vw &&w, Vx &&x)
∑ wᵢ xᵢ² (lane-wise).
simdified_simd_t< Vw > batmat::linalg::multi::weighted_vnorm_sq_diff(Vw &&w, Vx &&x, Vy &&y)
∑ wᵢ(xᵢ - yᵢ)² (lane-wise).
void batmat::linalg::symm_add(Structured< VA, SA > A, VB &&B, VC &&C, VD &&D)
D = C + A B with A symmetric.
References batmat::linalg::simdify, batmat::linalg::detail::symm, batmat::linalg::Structured< M, S >::value.
Referenced by batmat::linalg::symm_add.
void batmat::linalg::symm_add(Structured< VA, SA > A, VB &&B, VD &&D)
D = D + A B with A symmetric.
References batmat::linalg::Structured< M, S >::ref, batmat::linalg::symm_add.
void batmat::linalg::symv(Structured< VA, SA > A, VB &&B, VD &&D)
d = A b where A is symmetric
References batmat::linalg::simdify, batmat::linalg::detail::symv, batmat::linalg::Structured< M, S >::value.
void batmat::linalg::symv_neg(Structured< VA, SA > A, VB &&B, VD &&D)
d = -A b where A is symmetric
References batmat::linalg::simdify, batmat::linalg::detail::symv, batmat::linalg::Structured< M, S >::value.
void batmat::linalg::symv_add(Structured< VA, SA > A, VB &&B, VC &&C, VD &&D)
d = c + A b where A is symmetric
References batmat::linalg::simdify, batmat::linalg::detail::symv, batmat::linalg::Structured< M, S >::value.
Referenced by batmat::linalg::symv_add.
void batmat::linalg::symv_add(Structured< VA, SA > A, VB &&B, VD &&D)
d = d + A b where A is symmetric
References batmat::linalg::Structured< M, S >::ref, batmat::linalg::symv_add.
void batmat::linalg::symv_sub(Structured< VA, SA > A, VB &&B, VC &&C, VD &&D)
d = c - A b where A is symmetric
References batmat::linalg::simdify, batmat::linalg::detail::symv, batmat::linalg::Structured< M, S >::value.
Referenced by batmat::linalg::symv_sub.
void batmat::linalg::symv_sub(Structured< VA, SA > A, VB &&B, VD &&D)
d = d - A b where A is symmetric
References batmat::linalg::Structured< M, S >::ref, batmat::linalg::symv_sub.
void batmat::linalg::syomv(Structured< VA, SA > A, VB &&B, VD &&D)
References batmat::linalg::simdify, batmat::linalg::detail::syomv::syomv, batmat::linalg::Structured< M, S >::value.
void batmat::linalg::syomv_neg(Structured< VA, SA > A, VB &&B, VD &&D)
References batmat::linalg::simdify, batmat::linalg::detail::syomv::syomv, batmat::linalg::Structured< M, S >::value.
auto batmat::linalg::tril(M &&m)
Lower-triangular view.
Referenced by main.
auto batmat::linalg::triu(M &&m)
Upper-triangular view.
Referenced by main.
auto batmat::linalg::make_structured(M &&m)
View with the given structure.
Referenced by batmat::linalg::copy, batmat::linalg::fill.
void batmat::linalg::trsm(Structured< VA, SA > A, VB &&B, VD &&D, with_rotate_B_t< RotB >={})
D = A⁻¹ B with A triangular.
void batmat::linalg::trsm(Structured< VA, SA > A, VD &&D, with_rotate_B_t< RotB > shift={})
D = A⁻¹ D with A triangular.
void batmat::linalg::trsm(VA &&A, Structured< VB, SB > B, VD &&D, with_rotate_A_t< RotA >={})
D = A B⁻¹ with B triangular.
void batmat::linalg::trsm(VD &&D, Structured< VB, SB > B, with_rotate_A_t< RotA > shift={})
D = D B⁻¹ with B triangular.
void batmat::linalg::trtri(Structured< VA, MatrixStructure::LowerTriangular > A, Structured< VD, MatrixStructure::LowerTriangular > D)
D = A⁻¹ with A, D lower triangular.
References batmat::linalg::LowerTriangular, batmat::linalg::simdify, batmat::linalg::detail::trtri, batmat::linalg::Structured< M, S >::value.
Referenced by batmat::linalg::trtri, batmat::linalg::trtri.
void batmat::linalg::trtri(Structured< VA, MatrixStructure::UpperTriangular > A, Structured< VD, MatrixStructure::UpperTriangular > D)
D = A⁻¹ with A, D upper triangular.
References batmat::linalg::Structured< M, S >::transposed, batmat::linalg::trtri.
void batmat::linalg::trtri(Structured< VD, MatrixStructure::LowerTriangular > D)
D = D⁻¹ with D lower triangular.
References batmat::linalg::LowerTriangular, batmat::linalg::simdify, batmat::linalg::detail::trtri, batmat::linalg::Structured< M, S >::value.
void batmat::linalg::trtri(Structured< VD, MatrixStructure::UpperTriangular > D)
D = D⁻¹ with D upper triangular.
References batmat::linalg::Structured< M, S >::transposed, batmat::linalg::trtri.
PackingSelector
Access the original matrices directly in the micro-kernels.
MatrixStructure
MatrixStructure batmat::linalg::transpose(MatrixStructure s)
References batmat::linalg::General, batmat::linalg::LowerTriangular, batmat::linalg::UpperTriangular.
Referenced by batmat::linalg::syrk, batmat::linalg::syrk, batmat::linalg::syrk_neg, batmat::linalg::syrk_neg, batmat::linalg::flops::trmm.
batmat::linalg::Structured(M &&) -> Structured< M >