batmat::matrix::Layout
using batmat::matrix::Layout< I, S, D, L, O >::index_type = I
using batmat::matrix::Layout< I, S, D, L, O >::batch_size_type = S
using batmat::matrix::Layout< I, S, D, L, O >::depth_type = D
using batmat::matrix::Layout< I, S, D, L, O >::layer_stride_type = L
using batmat::matrix::Layout< I, S, D, L, O >::standard_stride_type = std::conditional_t<requires { S::value; }, std::integral_constant<index_t, S::value>, index_t>
StorageOrder batmat::matrix::Layout< I, S, D, L, O >::storage_order
bool batmat::matrix::Layout< I, S, D, L, O >::is_column_major
bool batmat::matrix::Layout< I, S, D, L, O >::is_row_major
std::integral_constant<index_type, 1> batmat::matrix::Layout< I, S, D, L, O >::inner_stride
depth_type batmat::matrix::Layout< I, S, D, L, O >::depth
Referenced by batmat::matrix::Layout< I, S, D, L, O >::has_full_layer_stride.
index_type batmat::matrix::Layout< I, S, D, L, O >::rows
index_type batmat::matrix::Layout< I, S, D, L, O >::cols
index_type batmat::matrix::Layout< I, S, D, L, O >::outer_stride
batch_size_type batmat::matrix::Layout< I, S, D, L, O >::batch_size
layer_stride_type batmat::matrix::Layout< I, S, D, L, O >::layer_stride
batmat::matrix::Layout< I, S, D, L, O >::Layout(PlainLayout p={})
index_type batmat::matrix::Layout< I, S, D, L, O >::outer_size() const
Referenced by batmat::matrix::Layout< I, S, D, L, O >::get_layer_stride, batmat::matrix::Layout< I, S, D, L, O >::has_full_layer_stride, batmat::matrix::Layout< I, S, D, L, O >::has_full_outer_stride.
index_type batmat::matrix::Layout< I, S, D, L, O >::inner_size() const
Referenced by batmat::matrix::Layout< I, S, D, L, O >::has_full_outer_stride.
index_type batmat::matrix::Layout< I, S, D, L, O >::num_batches() const
auto batmat::matrix::Layout< I, S, D, L, O >::row_stride() const
The row stride of the matrices, i.e.
the distance between elements in consecutive rows in a given column. Should be multiplied by the batch size to get the actual number of elements.
auto batmat::matrix::Layout< I, S, D, L, O >::col_stride() const
The column stride of the matrices, i.e.
the distance between elements in consecutive columns in a given row. Should be multiplied by the batch size to get the actual number of elements.
index_type batmat::matrix::Layout< I, S, D, L, O >::ceil_depth(index_type n) const
Round up the given size n to a multiple of batch_size.
index_type batmat::matrix::Layout< I, S, D, L, O >::ceil_depth() const
Round up the depth to a multiple of batch_size.
Referenced by batmat::matrix::Layout< I, S, D, L, O >::ceil_depth, batmat::matrix::Layout< I, S, D, L, O >::layer_index, batmat::matrix::Layout< I, S, D, L, O >::padded_size.
index_type batmat::matrix::Layout< I, S, D, L, O >::floor_depth(index_type n) const
Round down the given size n to a multiple of batch_size.
index_type batmat::matrix::Layout< I, S, D, L, O >::floor_depth() const
Round down the depth to a multiple of batch_size.
Referenced by batmat::matrix::Layout< I, S, D, L, O >::floor_depth.
auto batmat::matrix::Layout< I, S, D, L, O >::get_layer_stride() const
Referenced by batmat::matrix::Layout< I, S, D, L, O >::has_full_layer_stride, batmat::matrix::Layout< I, S, D, L, O >::layer_index, batmat::matrix::Layout< I, S, D, L, O >::padded_size.
bool batmat::matrix::Layout< I, S, D, L, O >::has_full_layer_stride() const
bool batmat::matrix::Layout< I, S, D, L, O >::has_full_outer_stride() const
bool batmat::matrix::Layout< I, S, D, L, O >::has_full_inner_stride() const
index_type batmat::matrix::Layout< I, S, D, L, O >::layer_index(index_type l, index_type s) const
Referenced by batmat::matrix::Layout< I, S, D, L, O >::layer_index, batmat::matrix::Layout< I, S, D, L, O >::operator(), batmat::matrix::Layout< I, S, D, L, O >::operator().
index_type batmat::matrix::Layout< I, S, D, L, O >::layer_index(index_type l) const
guanaqo::MatrixView< T, I, standard_stride_type, storage_order > batmat::matrix::Layout< I, S, D, L, O >::operator()(T *data, index_type l) const
T & batmat::matrix::Layout< I, S, D, L, O >::operator()(T *data, index_type l, index_type r, index_type c) const
index_type batmat::matrix::Layout< I, S, D, L, O >::size() const
Total number of elements in the view (excluding padding).
index_type batmat::matrix::Layout< I, S, D, L, O >::padded_size() const
static standard_stride_type batmat::matrix::Layout< I, S, D, L, O >::convert_to_standard_stride(auto s)
Referenced by batmat::matrix::Layout< I, S, D, L, O >::operator().