batmat::ops::detail
using batmat::ops::detail::floating_point_to_int_t = typename floating_point_to_int<T>::type
using batmat::ops::detail::convert_int_t = decltype(convert_int(std::declval<I>()))
using batmat::ops::detail::mask_type_t = typename mask_type<T, AbiT>::type
datapar::simd< T, AbiT > batmat::ops::detail::gather(datapar::simd< T, AbiT > src, typename datapar::simd< T, AbiT >::mask_type mask, datapar::simd< I, AbiI > vindex, const T *base_addr)
Referenced by batmat::ops::gather.
auto batmat::ops::detail::convert_int(I i)
mask_type_t< T, AbiT > batmat::ops::detail::convert_mask(M mask)
Convert a SIMD mask to the appropriate intrinsic type.
If M is not a mask type, its values are compared to zero to create a mask.
Referenced by batmat::ops::gather.
auto batmat::ops::detail::compare_ge_0(datapar::simd< T, Abi > x)
datapar::simd< F, Abi > batmat::ops::detail::rot(datapar::simd< F, Abi > x, int s)
Rotate the elements of x to the right by s positions.
For example, rotr<1>([x0, x1, x2, x3]) == [x3, x0, x1, x2] and rotr<-1>([x0, x1, x2, x3]) == [x1, x2, x3, x0].
datapar::simd< F, Abi > batmat::ops::detail::rotl(datapar::simd< F, Abi > x)
Referenced by batmat::ops::rotl, batmat::ops::rotr.
datapar::simd< F, Abi > batmat::ops::detail::rotr(datapar::simd< F, Abi > x)
Referenced by batmat::ops::rotl, batmat::ops::rotr.
datapar::simd< F, Abi > batmat::ops::detail::shiftl(datapar::simd< F, Abi > x)
Referenced by batmat::ops::shiftl, batmat::ops::shiftr.
datapar::simd< F, Abi > batmat::ops::detail::shiftr(datapar::simd< F, Abi > x)
Referenced by batmat::ops::shiftl, batmat::ops::shiftr.
datapar::simd< T, Abi > batmat::ops::detail::rsqrt_1(datapar::simd< T, Abi > x)
rsqrt_0 with a single Newton iteration of refinement.
Referenced by rsqrt_2.
datapar::simd< T, Abi > batmat::ops::detail::rsqrt_2(datapar::simd< T, Abi > x)
rsqrt_0 with two Newton iterations of refinement.
References rsqrt_1.