topic-utils
LoopDir
void batmat::foreach_chunked(index_t i_begin, index_t i_end, auto chunk_size, auto func_chunk, auto func_rem, LoopDir dir=LoopDir::Forward)
Iterate over the range [i_begin, i_end) in chunks of size chunk_size, calling func_chunk for each full chunk and func_rem for the remaining elements (if any).
References batmat::Forward.
Referenced by batmat::linalg::micro_kernels::hyhound::hyhound_diag_register.
void batmat::foreach_chunked_merged(index_t i_begin, index_t i_end, auto chunk_size, auto func_chunk, LoopDir dir=LoopDir::Forward)
Iterate over the range [i_begin, i_end) in chunks of size chunk_size, calling func_chunk for each chunk (including the last chunk, which may be smaller than chunk_size).
References batmat::Forward.
Referenced by batmat::linalg::detail::copy::copy, batmat::linalg::micro_kernels::gemm::gemm_copy_register, batmat::linalg::micro_kernels::gemm_diag::gemm_diag_copy_register, batmat::linalg::micro_kernels::gemv::gemv_copy_register, batmat::linalg::micro_kernels::hyhound::hyhound_diag_2_register, batmat::linalg::micro_kernels::hyhound::hyhound_diag_apply_register, batmat::linalg::micro_kernels::hyhound::hyhound_diag_cyclic_register, batmat::linalg::micro_kernels::hyhound::hyhound_diag_register, batmat::linalg::micro_kernels::hyhound::hyhound_diag_riccati_register, batmat::linalg::micro_kernels::potrf::potrf_copy_register, batmat::linalg::micro_kernels::symv::symv_copy_register, batmat::linalg::micro_kernels::syomv::syomv_register, batmat::linalg::micro_kernels::trsm::trsm_copy_register, batmat::linalg::micro_kernels::trtri::trtri_copy_register.
auto batmat::make_2d_lut(F f)
Returns a 2D array of the form:
{{f(0,0),f(0,1),...,f(0,C-1)}, {f(1,0),f(1,1),...,f(1,C-1)}, {...,...,...,...}, {f(R-1,0),f(R-1,1)},...,f(R-1,C-1)}} The argument f should be a function (or callable) that accepts two arguments of type index_constant.
References guanaqo::make_2d_lut.
Referenced by batmat::linalg::detail::copy::copy.
auto batmat::make_1d_lut(F f)
Returns an array of the form:
{f(0),f(1),...,f(C-1)} The argument f should be a function (or callable) that accepts an argument of type index_constant.
References guanaqo::make_1d_lut.
void batmat::pool_set_num_threads(size_t num_threads)
Set the number of threads in the global thread pool.
References batmat::detail::pool, batmat::detail::pool_mtx.
void batmat::pool_sync_run_all(F &&f)
Run a function on all threads in the global thread pool, synchronously waiting for all threads.
References batmat::detail::pool, batmat::detail::pool_mtx.
Referenced by batmat::foreach_thread.
void batmat::pool_sync_run_n(I n, F &&f)
Run a function on the first n threads in the global thread pool, synchronously waiting for those threads.
If n is greater than the number of threads in the pool, the pool is expanded.
References batmat::detail::pool, batmat::detail::pool_mtx.
Referenced by batmat::foreach_thread.