batmat::thread_pool
std::vector<Signals> batmat::thread_pool::signals
Referenced by thread_pool, schedule, wait, work.
std::vector<std::function<void()> > batmat::thread_pool::funcs
Referenced by thread_pool, schedule, wait, work.
std::vector<std::exception_ptr> batmat::thread_pool::exceptions
Referenced by thread_pool, wait, work.
std::vector<std::jthread> batmat::thread_pool::threads
Referenced by thread_pool, size.
void batmat::thread_pool::work(std::stop_token stop, size_t i)
References exceptions, funcs, signals.
Referenced by thread_pool.
batmat::thread_pool::thread_pool(size_t num_threads=std::thread::hardware_concurrency())
References exceptions, funcs, signals, threads, work.
Referenced by thread_pool, thread_pool, operator=, operator=.
batmat::thread_pool::thread_pool(const thread_pool &)=delete
References thread_pool.
thread_pool & batmat::thread_pool::operator=(const thread_pool &)=delete
References thread_pool.
batmat::thread_pool::thread_pool(thread_pool &&)=default
References thread_pool.
thread_pool & batmat::thread_pool::operator=(thread_pool &&)=default
References thread_pool.
void batmat::thread_pool::schedule(size_t i, std::function< void()> func)
References funcs, signals.
Referenced by sync_run_all, sync_run_n.
void batmat::thread_pool::wait(size_t i)
References exceptions, funcs, signals.
Referenced by sync_run_n, wait_all.
void batmat::thread_pool::wait_all()
References size, wait.
Referenced by sync_run_all.
void batmat::thread_pool::sync_run_all(F &&f)
References schedule, size, wait_all.
void batmat::thread_pool::sync_run_n(I n, F &&f)
References schedule, size, wait.
size_t batmat::thread_pool::size() const
References threads.
Referenced by sync_run_all, sync_run_n, wait_all.