batmat::matrix
using batmat::matrix::integral_value_type_t = typename integral_value_type<T>::type
auto batmat::matrix::data(Matrix< T, I, S, D, O, A > &v)
References batmat::matrix::Matrix< T, I, S, D, O, A >::data.
Referenced by batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::batch, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::batch_dyn, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::begin, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::bottom_rows, data, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::first_layers, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::left_cols, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::middle_batches, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::middle_cols, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::middle_layers, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::middle_rows, batmat::matrix::View< S, index_t, one_t, index_t, index_t, O >::operator View< const S, index_t, one_t, index_t, index_t, O >, batmat::matrix::View< S, index_t, one_t, index_t, index_t, O >::operator View< const S, index_t, one_t, integral_value_type_t< index_t >, index_t, O >, batmat::matrix::View< S, index_t, one_t, index_t, index_t, O >::operator View< S, index_t, one_t, index_t, index_t, O >, batmat::matrix::View< S, index_t, one_t, index_t, index_t, O >::operator View< S, index_t, one_t, integral_value_type_t< index_t >, index_t, O >, batmat::matrix::Layout< I, S, D, L, O >::operator(), batmat::matrix::Layout< I, S, D, L, O >::operator(), batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::reshaped, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::right_cols, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::top_rows, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::transposed.
auto batmat::matrix::data(Matrix< T, I, S, D, O, A > &&v)=delete
auto batmat::matrix::data(const Matrix< T, I, S, D, O, A > &v)
References batmat::matrix::Matrix< T, I, S, D, O, A >::data.
auto batmat::matrix::rows(const Matrix< T, I, S, D, O, A > &v)
References batmat::matrix::Matrix< T, I, S, D, O, A >::rows.
Referenced by batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::add_to_diagonal, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::batch, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::batch_dyn, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::bottom_rows, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::first_layers, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::left_cols, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::middle_batches, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::middle_cols, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::middle_layers, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::middle_rows, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::middle_rows, batmat::matrix::View< S, index_t, one_t, index_t, index_t, O >::operator View< const S, index_t, one_t, index_t, index_t, O >, batmat::matrix::View< S, index_t, one_t, index_t, index_t, O >::operator View< const S, index_t, one_t, integral_value_type_t< index_t >, index_t, O >, batmat::matrix::View< S, index_t, one_t, index_t, index_t, O >::operator View< S, index_t, one_t, index_t, index_t, O >, batmat::matrix::View< S, index_t, one_t, index_t, index_t, O >::operator View< S, index_t, one_t, integral_value_type_t< index_t >, index_t, O >, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::reshaped, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::right_cols, rows, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::top_rows, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::transposed.
auto batmat::matrix::cols(const Matrix< T, I, S, D, O, A > &v)
References batmat::matrix::Matrix< T, I, S, D, O, A >::cols.
Referenced by batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::add_to_diagonal, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::batch, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::batch_dyn, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::bottom_rows, cols, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::first_layers, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::left_cols, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::middle_batches, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::middle_cols, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::middle_cols, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::middle_layers, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::middle_rows, batmat::matrix::View< S, index_t, one_t, index_t, index_t, O >::operator View< const S, index_t, one_t, index_t, index_t, O >, batmat::matrix::View< S, index_t, one_t, index_t, index_t, O >::operator View< const S, index_t, one_t, integral_value_type_t< index_t >, index_t, O >, batmat::matrix::View< S, index_t, one_t, index_t, index_t, O >::operator View< S, index_t, one_t, index_t, index_t, O >, batmat::matrix::View< S, index_t, one_t, index_t, index_t, O >::operator View< S, index_t, one_t, integral_value_type_t< index_t >, index_t, O >, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::reshaped, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::right_cols, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::top_rows, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::transposed.
auto batmat::matrix::outer_stride(const Matrix< T, I, S, D, O, A > &v)
References batmat::matrix::Matrix< T, I, S, D, O, A >::outer_stride.
Referenced by batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::add_to_diagonal, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::batch, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::batch_dyn, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::bottom_rows, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::copy_values, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::first_layers, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::left_cols, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::middle_batches, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::middle_cols, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::middle_layers, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::middle_rows, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::negate, batmat::matrix::View< S, index_t, one_t, index_t, index_t, O >::operator View< const S, index_t, one_t, index_t, index_t, O >, batmat::matrix::View< S, index_t, one_t, index_t, index_t, O >::operator View< const S, index_t, one_t, integral_value_type_t< index_t >, index_t, O >, batmat::matrix::View< S, index_t, one_t, index_t, index_t, O >::operator View< S, index_t, one_t, index_t, index_t, O >, batmat::matrix::View< S, index_t, one_t, index_t, index_t, O >::operator View< S, index_t, one_t, integral_value_type_t< index_t >, index_t, O >, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::operator+=, outer_stride, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::right_cols, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::set_constant, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::top_rows, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::transposed.
auto batmat::matrix::depth(const Matrix< T, I, S, D, O, A > &v)
References batmat::matrix::Matrix< T, I, S, D, O, A >::depth.
Referenced by batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::batch_dyn, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::bottom_rows, depth, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::first_layers, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::left_cols, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::middle_batches, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::middle_cols, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::middle_layers, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::middle_rows, batmat::matrix::View< S, index_t, one_t, index_t, index_t, O >::operator View< const S, index_t, one_t, index_t, index_t, O >, batmat::matrix::View< S, index_t, one_t, index_t, index_t, O >::operator View< const S, index_t, one_t, integral_value_type_t< index_t >, index_t, O >, batmat::matrix::View< S, index_t, one_t, index_t, index_t, O >::operator View< S, index_t, one_t, index_t, index_t, O >, batmat::matrix::View< S, index_t, one_t, index_t, index_t, O >::operator View< S, index_t, one_t, integral_value_type_t< index_t >, index_t, O >, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::reshaped, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::right_cols, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::top_rows, batmat::matrix::View< T, index_t, stride, stride, layer_stride, O >::transposed.
std::align_val_t batmat::matrix::as_align_val(A a)
Referenced by batmat::matrix::detail::make_aligned_unique_ptr, batmat::matrix::aligned_deleter< T, A >::operator(), batmat::matrix::aligned_deleter< void, A >::operator().
bool batmat::matrix::operator==(std::default_sentinel_t s, typename View< T, I, S, D, L, P >::linear_iterator i)
References operator==.
Referenced by operator==.
bool batmat::matrix::operator!=(std::default_sentinel_t s, typename View< T, I, S, D, L, P >::linear_iterator i)
References operator!=.
Referenced by operator!=, operator!=.
bool batmat::matrix::operator!=(typename View< T, I, S, D, L, P >::linear_iterator i, std::default_sentinel_t s)
References operator!=.
auto batmat::matrix::data(const View< T, I, S, D, L, O > &v)
References data, batmat::matrix::View< T, I, S, D, L, O >::data.
auto batmat::matrix::rows(const View< T, I, S, D, L, O > &v)
References rows, batmat::matrix::View< T, I, S, D, L, O >::rows.
auto batmat::matrix::cols(const View< T, I, S, D, L, O > &v)
References cols, batmat::matrix::View< T, I, S, D, L, O >::cols.
auto batmat::matrix::outer_stride(const View< T, I, S, D, L, O > &v)
References outer_stride, batmat::matrix::View< T, I, S, D, L, O >::outer_stride.
auto batmat::matrix::depth(const View< T, I, S, D, L, O > &v)
References depth, batmat::matrix::View< T, I, S, D, L, O >::depth.
StorageOrder