batmat::linalg::detail
index_t batmat::linalg::detail::compress_masks_impl(view< const T, Abi, OAi > A_in, view< const T, Abi > S_in, auto writeS, auto writeA)
References BATMAT_ASSERT, BATMAT_ASSUME, BATMAT_FULLY_UNROLLED_FOR, batmat::ops::gather.
Referenced by compress_masks.
index_t batmat::linalg::detail::compress_masks_count(view< const T, Abi > S_in)
References BATMAT_FULLY_UNROLLED_FOR.
Referenced by batmat::linalg::compress_masks_count.
index_t batmat::linalg::detail::compress_masks(view< const T, Abi, OAi > A_in, view< const T, Abi > S_in, view< T, Abi, OAo > A_out, view< T, Abi > S_out)
References batmat::datapar::aligned_store, BATMAT_ASSERT, compress_masks_impl.
Referenced by batmat::linalg::compress_masks.
index_t batmat::linalg::detail::compress_masks_sqrt(view< const T, Abi, OAi > A_in, view< const T, Abi > S_in, view< T, Abi, OAo > A_out, view< T, Abi > S_sign_out={})
Referenced by batmat::linalg::compress_masks_sqrt, batmat::linalg::compress_masks_sqrt.
void batmat::linalg::detail::gemm(view< const T, Abi, OA > A, view< const T, Abi, OB > B, std::optional< view< const T, Abi, OC > > C, view< T, Abi, OD > D, TilingOptions packing={})
void batmat::linalg::detail::gemmt(view< const T, Abi, OA > A, view< const T, Abi, OB > B, std::optional< view< const T, Abi, OC > > C, view< T, Abi, OD > D)
References BATMAT_ASSERT, batmat::linalg::detail::copy::copy, batmat::linalg::detail::copy::fill, batmat::linalg::micro_kernels::gemm::gemm_copy_register, batmat::linalg::General, batmat::linalg::flops::trmm.
Referenced by batmat::linalg::syrk, batmat::linalg::syrk, batmat::linalg::syrk_add, batmat::linalg::syrk_neg, batmat::linalg::syrk_neg, batmat::linalg::syrk_sub.
void batmat::linalg::detail::trmm(view< const T, Abi, OA > A, view< const T, Abi, OB > B, std::optional< view< const T, Abi, OC > > C, view< T, Abi, OD > D)
References BATMAT_ASSERT, batmat::linalg::detail::copy::copy, batmat::linalg::detail::copy::fill, batmat::linalg::micro_kernels::gemm::gemm_copy_register, batmat::linalg::General, batmat::linalg::flops::trmm.
Referenced by batmat::linalg::trmm, batmat::linalg::trmm_add, batmat::linalg::trmm_neg, batmat::linalg::trmm_sub.
micro_kernels::gemm::KernelConfig batmat::linalg::detail::apply_gemm_options(micro_kernels::gemm::KernelConfig conf, Opts...)
References batmat::linalg::mask_D, batmat::linalg::micro_kernels::gemm::KernelConfig::mask_D, batmat::linalg::micro_kernels::gemm::KernelConfig::rotate_B, batmat::linalg::rotate_B, batmat::linalg::micro_kernels::gemm::KernelConfig::rotate_C, batmat::linalg::rotate_C, batmat::linalg::micro_kernels::gemm::KernelConfig::rotate_D, batmat::linalg::rotate_D, batmat::linalg::micro_kernels::gemm::KernelConfig::shift_A, batmat::linalg::shift_A.
Referenced by batmat::linalg::syrk, batmat::linalg::syrk, batmat::linalg::syrk_add, batmat::linalg::syrk_neg, batmat::linalg::syrk_neg, batmat::linalg::syrk_sub, batmat::linalg::trmm, batmat::linalg::trmm_add, batmat::linalg::trmm_neg, batmat::linalg::trmm_sub.
void batmat::linalg::detail::gemv(view< const T, Abi, OA > A, view< const T, Abi > B, std::optional< view< const T, Abi > > C, view< T, Abi > D)
References BATMAT_ASSERT, batmat::linalg::detail::copy::copy, batmat::linalg::detail::copy::fill, batmat::linalg::micro_kernels::gemv::gemv_copy_register.
Referenced by batmat::linalg::gemv, batmat::linalg::gemv_add, batmat::linalg::gemv_neg, batmat::linalg::gemv_sub.
micro_kernels::gemv::KernelConfig batmat::linalg::detail::apply_gemv_options(micro_kernels::gemv::KernelConfig conf, Opts...)
References batmat::linalg::mask_D, batmat::linalg::micro_kernels::gemv::KernelConfig::mask_D, batmat::linalg::micro_kernels::gemv::KernelConfig::rotate_B, batmat::linalg::rotate_B, batmat::linalg::micro_kernels::gemv::KernelConfig::rotate_C, batmat::linalg::rotate_C, batmat::linalg::micro_kernels::gemv::KernelConfig::rotate_D, batmat::linalg::rotate_D, batmat::linalg::micro_kernels::gemv::KernelConfig::shift_A, batmat::linalg::shift_A.
Referenced by batmat::linalg::gemv, batmat::linalg::gemv_add, batmat::linalg::gemv_neg, batmat::linalg::gemv_sub.
void batmat::linalg::detail::hyhound_diag(view< T, Abi, OL > L, view< T, Abi, OA > A, view< const T, Abi > D)
References BATMAT_ASSERT, batmat::linalg::flops::hyh, batmat::linalg::micro_kernels::hyhound::hyhound_diag_register.
Referenced by batmat::linalg::hyhound_diag, batmat::linalg::hyhound_diag, batmat::linalg::hyhound_sign.
void batmat::linalg::detail::hyhound_diag(view< T, Abi, OL > L, view< T, Abi, OA > A, view< const T, Abi > D, view< T, Abi > W)
References BATMAT_ASSERT, batmat::linalg::flops::hyh.
void batmat::linalg::detail::hyhound_diag_apply(view< T, Abi, OL > L, view< const T, Abi, OA > Ain, view< T, Abi, OA > Aout, view< const T, Abi, OA > B, view< const T, Abi > D, view< const T, Abi > W, index_t kA_in_offset=0)
References BATMAT_ASSERT, batmat::linalg::flops::hyh_apply.
Referenced by batmat::linalg::hyhound_diag_apply, batmat::linalg::hyhound_diag_apply.
void batmat::linalg::detail::hyhound_diag_2(view< T, Abi, OL1 > L11, view< T, Abi, OA1 > A1, view< T, Abi, OL2 > L21, view< T, Abi, OA2 > A2, view< const T, Abi > D)
References BATMAT_ASSERT, batmat::linalg::flops::hyh, batmat::linalg::micro_kernels::hyhound::hyhound_diag_2_register.
Referenced by batmat::linalg::hyhound_diag_2.
void batmat::linalg::detail::hyhound_diag_cyclic(view< T, Abi, OL > L11, view< T, Abi, OW > A1, view< T, Abi, OY > L21, view< const T, Abi, OW > A22, view< T, Abi, OW > A2_out, view< T, Abi, OU > L31, view< const T, Abi, OW > A31, view< T, Abi, OW > A3_out, view< const T, Abi > D)
References BATMAT_ASSERT, batmat::linalg::flops::hyh, batmat::linalg::micro_kernels::hyhound::hyhound_diag_cyclic_register.
Referenced by batmat::linalg::hyhound_diag_cyclic.
void batmat::linalg::detail::hyhound_diag_riccati(view< T, Abi, OL > L11, view< T, Abi, OA > A1, view< T, Abi, OL > L21, view< const T, Abi, OA > A2, view< T, Abi, OA > A2_out, view< T, Abi, OLu > Lu1, view< T, Abi, OAu > Au_out, view< const T, Abi > D, bool shift_A_out)
References BATMAT_ASSERT, batmat::linalg::flops::hyh, batmat::linalg::micro_kernels::hyhound::hyhound_diag_riccati_register.
Referenced by batmat::linalg::hyhound_diag_riccati.
void batmat::linalg::detail::potrf(view< const T, Abi, OA > A, view< const T, Abi, OCD > C, view< T, Abi, OCD > D, T regularization, micro_kernels::potrf::diag_view_type< const T, Abi, Conf > d={}) noexcept
Referenced by batmat::linalg::potrf, batmat::linalg::potrf, batmat::linalg::syrk_add_potrf, batmat::linalg::syrk_diag_add_potrf, batmat::linalg::syrk_sub_potrf.
void batmat::linalg::detail::symm(view< const T, Abi, OA > A, view< const T, Abi > B, std::optional< view< const T, Abi > > C, view< T, Abi > D)
References BATMAT_ASSERT, BATMAT_UNROLLED_IVDEP_FOR, batmat::linalg::uview< T, Abi, Order >::load, batmat::linalg::uview< T, Abi, Order >::store.
Referenced by batmat::linalg::symm_add.
void batmat::linalg::detail::symv(view< const T, Abi, OA > A, view< const T, Abi > B, std::optional< view< const T, Abi > > C, view< T, Abi > D)
References BATMAT_ASSERT, batmat::linalg::LowerTriangular, batmat::linalg::micro_kernels::symv::symv_copy_register.
Referenced by batmat::linalg::symv, batmat::linalg::symv_add, batmat::linalg::symv_neg, batmat::linalg::symv_sub.
void batmat::linalg::detail::trsm(view< const T, Abi, OA > A, view< const T, Abi, OB > B, view< T, Abi, OD > D)
References BATMAT_ASSERT, batmat::linalg::flops::trsm, batmat::linalg::micro_kernels::trsm::trsm_copy_register.
void batmat::linalg::detail::trtri(view< const T, Abi, OA > A, view< T, Abi, OD > D)
References BATMAT_ASSERT, batmat::linalg::flops::trtri, batmat::linalg::micro_kernels::trtri::trtri_copy_register.
Referenced by batmat::linalg::trtri, batmat::linalg::trtri.