var hierarchy =
[
    [ "batmat::DefaultTimings", "namespacebatmat.html#structbatmat_1_1DefaultTimings", null ],
    [ "batmat::linalg::cached_uview&lt; Size, T, Abi, Order &gt;", "structbatmat_1_1linalg_1_1cached__uview.html", null ],
    [ "batmat::linalg::detail::copy::CopyConfig", "namespacebatmat_1_1linalg_1_1detail_1_1copy.html#structbatmat_1_1linalg_1_1detail_1_1copy_1_1CopyConfig", null ],
    [ "batmat::linalg::detail::copy::FillConfig", "namespacebatmat_1_1linalg_1_1detail_1_1copy.html#structbatmat_1_1linalg_1_1detail_1_1copy_1_1FillConfig", null ],
    [ "batmat::linalg::detail::simdified_abi&lt; class &gt;", "namespacebatmat_1_1linalg_1_1detail.html#structbatmat_1_1linalg_1_1detail_1_1simdified__abi", null ],
    [ "batmat::linalg::detail::simdified_abi&lt; V &gt;", "namespacebatmat_1_1linalg_1_1detail.html#structbatmat_1_1linalg_1_1detail_1_1simdified__abi_3_01V_01_4", null ],
    [ "batmat::linalg::detail::simdified_multi_view_type&lt; V &gt;", "namespacebatmat_1_1linalg_1_1detail.html#structbatmat_1_1linalg_1_1detail_1_1simdified__multi__view__type", null ],
    [ "batmat::linalg::detail::simdified_multi_view_type&lt; batmat::matrix::Matrix&lt; T, I, S, I, O, A &gt; &gt;", "namespacebatmat_1_1linalg_1_1detail.html#structbatmat_1_1linalg_1_1detail_1_1simdified__multi__view__type_3_01batmat_1_1matrix_1_1Matrix_a2d75434e5018f0cd47dbc6912dd16bf", null ],
    [ "batmat::linalg::detail::simdified_multi_view_type&lt; batmat::matrix::View&lt; T, index_t, S, index_t, L, O &gt; &gt;", "namespacebatmat_1_1linalg_1_1detail.html#structbatmat_1_1linalg_1_1detail_1_1simdified__multi__view__type_3_01batmat_1_1matrix_1_1View_3_22d8282ba65d154ec9580e6f7da6b8b5", null ],
    [ "batmat::linalg::detail::simdified_multi_view_type&lt; const batmat::matrix::Matrix&lt; T, I, S, I, O, A &gt; &gt;", "namespacebatmat_1_1linalg_1_1detail.html#structbatmat_1_1linalg_1_1detail_1_1simdified__multi__view__type_3_01const_01batmat_1_1matrix_1_68d714009fb08972c65f60674f881d94", null ],
    [ "batmat::linalg::detail::simdified_multi_view_type&lt; const batmat::matrix::View&lt; T, index_t, S, index_t, L, O &gt; &gt;", "namespacebatmat_1_1linalg_1_1detail.html#structbatmat_1_1linalg_1_1detail_1_1simdified__multi__view__type_3_01const_01batmat_1_1matrix_1_33bea5f89420c1479536e5641dd6559d", null ],
    [ "batmat::linalg::detail::simdified_value&lt; class &gt;", "namespacebatmat_1_1linalg_1_1detail.html#structbatmat_1_1linalg_1_1detail_1_1simdified__value", null ],
    [ "batmat::linalg::detail::simdified_value&lt; V &gt;", "namespacebatmat_1_1linalg_1_1detail.html#structbatmat_1_1linalg_1_1detail_1_1simdified__value_3_01V_01_4", null ],
    [ "batmat::linalg::detail::simdified_view_type&lt; V &gt;", "namespacebatmat_1_1linalg_1_1detail.html#structbatmat_1_1linalg_1_1detail_1_1simdified__view__type", null ],
    [ "batmat::linalg::detail::simdified_view_type&lt; batmat::matrix::Matrix&lt; T, I, S, S, O, A &gt; &gt;", "namespacebatmat_1_1linalg_1_1detail.html#structbatmat_1_1linalg_1_1detail_1_1simdified__view__type_3_01batmat_1_1matrix_1_1Matrix_3_01T_02011ca1015d066513d24349619a4283a", null ],
    [ "batmat::linalg::detail::simdified_view_type&lt; batmat::matrix::View&lt; T, index_t, S, S, L, O &gt; &gt;", "namespacebatmat_1_1linalg_1_1detail.html#structbatmat_1_1linalg_1_1detail_1_1simdified__view__type_3_01batmat_1_1matrix_1_1View_3_01T_00_6c276fa58d30c8a61a58492532979869", null ],
    [ "batmat::linalg::detail::simdified_view_type&lt; const batmat::matrix::Matrix&lt; T, I, S, S, O, A &gt; &gt;", "namespacebatmat_1_1linalg_1_1detail.html#structbatmat_1_1linalg_1_1detail_1_1simdified__view__type_3_01const_01batmat_1_1matrix_1_1Matrix2f013e9bf729f69bd71be2becf75521d", null ],
    [ "batmat::linalg::detail::simdified_view_type&lt; const batmat::matrix::View&lt; T, index_t, S, S, L, O &gt; &gt;", "namespacebatmat_1_1linalg_1_1detail.html#structbatmat_1_1linalg_1_1detail_1_1simdified__view__type_3_01const_01batmat_1_1matrix_1_1View_32dba1d643fdf8dda24f3695f783071e9", null ],
    [ "batmat::linalg::detail::simdified_view_type&lt; const guanaqo::MatrixView&lt; T, I, std::integral_constant&lt; I, 1 &gt;, O &gt; &gt;", "namespacebatmat_1_1linalg_1_1detail.html#structbatmat_1_1linalg_1_1detail_1_1simdified__view__type_3_01const_01guanaqo_1_1MatrixView_3_010856bf788b5ff2bc105d0749e18010ef", null ],
    [ "batmat::linalg::detail::simdified_view_type&lt; guanaqo::MatrixView&lt; T, I, std::integral_constant&lt; I, 1 &gt;, O &gt; &gt;", "namespacebatmat_1_1linalg_1_1detail.html#structbatmat_1_1linalg_1_1detail_1_1simdified__view__type_3_01guanaqo_1_1MatrixView_3_01T_00_01If7b43d4de87d72ee5b21d1b3c0074753", null ],
    [ "batmat::linalg::flops::FlopCount", "group__topic-linalg-flops.html#structbatmat_1_1linalg_1_1flops_1_1FlopCount", null ],
    [ "batmat::linalg::micro_kernels::gemm::KernelConfig", "namespacebatmat_1_1linalg_1_1micro__kernels_1_1gemm.html#structbatmat_1_1linalg_1_1micro__kernels_1_1gemm_1_1KernelConfig", null ],
    [ "batmat::linalg::micro_kernels::gemm_diag::KernelConfig", "namespacebatmat_1_1linalg_1_1micro__kernels_1_1gemm__diag.html#structbatmat_1_1linalg_1_1micro__kernels_1_1gemm__diag_1_1KernelConfig", null ],
    [ "batmat::linalg::micro_kernels::gemv::KernelConfig", "namespacebatmat_1_1linalg_1_1micro__kernels_1_1gemv.html#structbatmat_1_1linalg_1_1micro__kernels_1_1gemv_1_1KernelConfig", null ],
    [ "batmat::linalg::micro_kernels::hyhound::KernelConfig", "namespacebatmat_1_1linalg_1_1micro__kernels_1_1hyhound.html#structbatmat_1_1linalg_1_1micro__kernels_1_1hyhound_1_1KernelConfig", null ],
    [ "batmat::linalg::micro_kernels::hyhound::triangular_accessor&lt; T, Abi, R &gt;", "structbatmat_1_1linalg_1_1micro__kernels_1_1hyhound_1_1triangular__accessor.html", null ],
    [ "batmat::linalg::micro_kernels::potrf::KernelConfig", "structbatmat_1_1linalg_1_1micro__kernels_1_1potrf_1_1KernelConfig.html", null ],
    [ "batmat::linalg::micro_kernels::symv::KernelConfig", "namespacebatmat_1_1linalg_1_1micro__kernels_1_1symv.html#structbatmat_1_1linalg_1_1micro__kernels_1_1symv_1_1KernelConfig", null ],
    [ "batmat::linalg::micro_kernels::syomv::KernelConfig", "namespacebatmat_1_1linalg_1_1micro__kernels_1_1syomv.html#structbatmat_1_1linalg_1_1micro__kernels_1_1syomv_1_1KernelConfig", null ],
    [ "batmat::linalg::micro_kernels::trsm::KernelConfig", "namespacebatmat_1_1linalg_1_1micro__kernels_1_1trsm.html#structbatmat_1_1linalg_1_1micro__kernels_1_1trsm_1_1KernelConfig", null ],
    [ "batmat::linalg::micro_kernels::trtri::KernelConfig", "namespacebatmat_1_1linalg_1_1micro__kernels_1_1trtri.html#structbatmat_1_1linalg_1_1micro__kernels_1_1trtri_1_1KernelConfig", null ],
    [ "batmat::linalg::simd_view_types&lt; T, Abi &gt;", "structbatmat_1_1linalg_1_1simd__view__types.html", null ],
    [ "batmat::linalg::Structured&lt; M, S &gt;", "structbatmat_1_1linalg_1_1Structured.html", null ],
    [ "batmat::linalg::TilingOptions", "group__topic-linalg.html#structbatmat_1_1linalg_1_1TilingOptions", null ],
    [ "batmat::linalg::uview&lt; T, Abi, Order &gt;", "structbatmat_1_1linalg_1_1uview.html", null ],
    [ "batmat::linalg::uview_vec&lt; T, Abi &gt;", "structbatmat_1_1linalg_1_1uview__vec.html", null ],
    [ "batmat::matrix::aligned_deleter&lt; T, A &gt;", "structbatmat_1_1matrix_1_1aligned__deleter.html", null ],
    [ "batmat::matrix::aligned_deleter&lt; void, A &gt;", "structbatmat_1_1matrix_1_1aligned__deleter_3_01void_00_01A_01_4.html", null ],
    [ "batmat::matrix::DefaultStride", "structbatmat_1_1matrix_1_1DefaultStride.html", null ],
    [ "batmat::matrix::detail::default_alignment&lt; class, I, Stride &gt;", "namespacebatmat_1_1matrix_1_1detail.html#structbatmat_1_1matrix_1_1detail_1_1default__alignment", null ],
    [ "batmat::matrix::detail::default_alignment&lt; T, I, Stride &gt;", "namespacebatmat_1_1matrix_1_1detail.html#structbatmat_1_1matrix_1_1detail_1_1default__alignment_3_01T_00_01I_00_01Stride_01_4", null ],
    [ "batmat::matrix::integral_value_type&lt; T &gt;", "namespacebatmat_1_1matrix.html#structbatmat_1_1matrix_1_1integral__value__type", null ],
    [ "batmat::matrix::integral_value_type&lt; IntConst &gt;", "namespacebatmat_1_1matrix.html#structbatmat_1_1matrix_1_1integral__value__type_3_01IntConst_01_4", null ],
    [ "batmat::matrix::Layout&lt; I, S, D, L, O &gt;", "structbatmat_1_1matrix_1_1Layout.html", null ],
    [ "batmat::matrix::Layout&lt; I, S, D, L, O &gt;::PlainLayout", "structbatmat_1_1matrix_1_1Layout.html#structbatmat_1_1matrix_1_1Layout_1_1PlainLayout", null ],
    [ "batmat::matrix::Matrix&lt; T, I, S, D, O, A &gt;", "structbatmat_1_1matrix_1_1Matrix.html", null ],
    [ "batmat::matrix::uninitialized_t", "group__topic-matrix-utils.html#structbatmat_1_1matrix_1_1uninitialized__t", null ],
    [ "batmat::matrix::View&lt; T, I, S, D, L, O &gt;", "structbatmat_1_1matrix_1_1View.html", null ],
    [ "batmat::matrix::View&lt; T, I, S, D, L, O &gt;::linear_iterator", "structbatmat_1_1matrix_1_1View_1_1linear__iterator.html", null ],
    [ "batmat::matrix::View&lt; T, I, S, D, L, O &gt;::PlainBatchedMatrixView", "structbatmat_1_1matrix_1_1View.html#structbatmat_1_1matrix_1_1View_1_1PlainBatchedMatrixView", null ],
    [ "batmat::ops::detail::floating_point_to_int&lt; T &gt;", "namespacebatmat_1_1ops_1_1detail.html#structbatmat_1_1ops_1_1detail_1_1floating__point__to__int", null ],
    [ "batmat::ops::detail::floating_point_to_int&lt; double &gt;", "namespacebatmat_1_1ops_1_1detail.html#structbatmat_1_1ops_1_1detail_1_1floating__point__to__int_3_01double_01_4", null ],
    [ "batmat::ops::detail::floating_point_to_int&lt; float &gt;", "namespacebatmat_1_1ops_1_1detail.html#structbatmat_1_1ops_1_1detail_1_1floating__point__to__int_3_01float_01_4", null ],
    [ "batmat::ops::detail::mask_type&lt; T, Abi &gt;", "namespacebatmat_1_1ops_1_1detail.html#structbatmat_1_1ops_1_1detail_1_1mask__type", null ],
    [ "batmat::thread_pool", "classbatmat_1_1thread__pool.html", null ],
    [ "batmat::thread_pool::Signals", "classbatmat_1_1thread__pool.html#structbatmat_1_1thread__pool_1_1Signals", null ],
    [ "batmat::types::Concat&lt;... &gt;", "namespacebatmat_1_1types.html#structbatmat_1_1types_1_1Concat", null ],
    [ "batmat::types::Concat&lt; Types&lt; Ts... &gt; &gt;", "namespacebatmat_1_1types.html#structbatmat_1_1types_1_1Concat_3_01Types_3_01Ts_8_8_8_01_4_01_4", null ],
    [ "batmat::types::Concat&lt; Types&lt; Ts1... &gt;, Types&lt; Ts2... &gt;, Rest... &gt;", "namespacebatmat_1_1types.html#structbatmat_1_1types_1_1Concat_3_01Types_3_01Ts1_8_8_8_01_4_00_01Types_3_01Ts2_8_8_8_01_4_00_01Rest_8_8_8_01_4", null ],
    [ "batmat::types::Concat&lt;&gt;", "namespacebatmat_1_1types.html#structbatmat_1_1types_1_1Concat_3_4", null ],
    [ "batmat::types::DTypeIs&lt; DT &gt;", "namespacebatmat_1_1types.html#structbatmat_1_1types_1_1DTypeIs", null ],
    [ "batmat::types::DTypeVectorLength&lt; T, VL &gt;", "structbatmat_1_1types_1_1DTypeVectorLength.html", null ],
    [ "batmat::types::Filter&lt; Pred, class &gt;", "namespacebatmat_1_1types.html#structbatmat_1_1types_1_1Filter", null ],
    [ "batmat::types::Filter&lt; Pred, Types&lt; Ts... &gt; &gt;", "namespacebatmat_1_1types.html#structbatmat_1_1types_1_1Filter_3_01Pred_00_01Types_3_01Ts_8_8_8_01_4_01_4", null ],
    [ "batmat::types::FlatMap&lt; Func, class &gt;", "namespacebatmat_1_1types.html#structbatmat_1_1types_1_1FlatMap", null ],
    [ "batmat::types::FlatMap&lt; Func, Types&lt; Ts... &gt; &gt;", "namespacebatmat_1_1types.html#structbatmat_1_1types_1_1FlatMap_3_01Func_00_01Types_3_01Ts_8_8_8_01_4_01_4", null ],
    [ "batmat::types::Head&lt; class &gt;", "namespacebatmat_1_1types.html#structbatmat_1_1types_1_1Head", null ],
    [ "batmat::types::Head&lt; Types&lt; T, Ts... &gt; &gt;", "namespacebatmat_1_1types.html#structbatmat_1_1types_1_1Head_3_01Types_3_01T_00_01Ts_8_8_8_01_4_01_4", null ],
    [ "batmat::types::Map&lt; Func, class &gt;", "namespacebatmat_1_1types.html#structbatmat_1_1types_1_1Map", null ],
    [ "batmat::types::Map&lt; Func, Types&lt; Ts... &gt; &gt;", "namespacebatmat_1_1types.html#structbatmat_1_1types_1_1Map_3_01Func_00_01Types_3_01Ts_8_8_8_01_4_01_4", null ],
    [ "batmat::types::Tail&lt; class &gt;", "namespacebatmat_1_1types.html#structbatmat_1_1types_1_1Tail", null ],
    [ "batmat::types::Tail&lt; Types&lt; T, Ts... &gt; &gt;", "namespacebatmat_1_1types.html#structbatmat_1_1types_1_1Tail_3_01Types_3_01T_00_01Ts_8_8_8_01_4_01_4", null ],
    [ "batmat::types::Types&lt; Ts &gt;", "namespacebatmat_1_1types.html#structbatmat_1_1types_1_1Types", null ],
    [ "batmat::types::VectorLengthIs&lt; VL &gt;", "namespacebatmat_1_1types.html#structbatmat_1_1types_1_1VectorLengthIs", null ],
    [ "guanaqo::Timed&lt; batmat::DefaultTimings &gt;", "structguanaqo_1_1Timed_3_01batmat_1_1DefaultTimings_01_4.html", null ],
    [ "std::bool_constant", null, [
      [ "batmat::linalg::track_zeros_t< Z >", "structbatmat_1_1linalg_1_1track__zeros__t.html", null ]
    ] ],
    [ "std::integral_constant", null, [
      [ "batmat::linalg::with_mask_D_t< I >", "structbatmat_1_1linalg_1_1with__mask__D__t.html", null ],
      [ "batmat::linalg::with_mask_t< I >", "structbatmat_1_1linalg_1_1with__mask__t.html", null ],
      [ "batmat::linalg::with_rotate_A_t< I >", "structbatmat_1_1linalg_1_1with__rotate__A__t.html", null ],
      [ "batmat::linalg::with_rotate_B_t< I >", "structbatmat_1_1linalg_1_1with__rotate__B__t.html", null ],
      [ "batmat::linalg::with_rotate_C_t< I >", "structbatmat_1_1linalg_1_1with__rotate__C__t.html", null ],
      [ "batmat::linalg::with_rotate_D_t< I >", "structbatmat_1_1linalg_1_1with__rotate__D__t.html", null ],
      [ "batmat::linalg::with_rotate_t< I >", "structbatmat_1_1linalg_1_1with__rotate__t.html", null ],
      [ "batmat::linalg::with_shift_A_t< I >", "structbatmat_1_1linalg_1_1with__shift__A__t.html", null ]
    ] ]
];