batmat::linalg::detail::gemm_diag
std::optional<bool> batmat::linalg::detail::gemm_diag::get_track_zeros
Referenced by apply_options.
std::optional<bool> batmat::linalg::detail::gemm_diag::get_track_zeros< T, Ts... >
std::optional<bool> batmat::linalg::detail::gemm_diag::get_track_zeros< track_zeros_t< Z >, Ts... >
bool batmat::linalg::detail::gemm_diag::is_track_zeros_opt
bool batmat::linalg::detail::gemm_diag::is_track_zeros_opt< track_zeros_t< Z > >
void batmat::linalg::detail::gemm_diag::gemm_diag(view< const T, Abi, OA > A, view< const T, Abi, OB > B, std::optional< view< const T, Abi, OC > > C, view< T, Abi, OD > D, view< const T, Abi > d)
References BATMAT_ASSERT, batmat::linalg::detail::copy::copy, batmat::linalg::detail::copy::fill, gemm_diag, batmat::linalg::micro_kernels::gemm_diag::gemm_diag_copy_register, batmat::linalg::flops::gemmt_diag.
Referenced by gemm_diag, batmat::linalg::gemm_diag, batmat::linalg::gemm_diag_add, batmat::linalg::syrk_diag_add.
micro_kernels::gemm_diag::KernelConfig batmat::linalg::detail::gemm_diag::apply_options(micro_kernels::gemm_diag::KernelConfig conf, Opts...)
References get_track_zeros, batmat::linalg::micro_kernels::gemm_diag::KernelConfig::track_zeros.
Referenced by batmat::linalg::gemm_diag, batmat::linalg::gemm_diag_add, batmat::linalg::syrk_diag_add.