batmat::linalg::detail::copy
void batmat::linalg::detail::copy::fill(T a, view< T, Abi, OB > B)
References BATMAT_UNROLLED_IVDEP_FOR, batmat::linalg::General, batmat::linalg::LowerTriangular, batmat::linalg::UpperTriangular.
Referenced by batmat::linalg::fill, batmat::linalg::fill, batmat::linalg::detail::gemm_diag::gemm_diag, batmat::linalg::detail::gemmt, batmat::linalg::detail::gemv, batmat::linalg::detail::trmm.
void batmat::linalg::detail::copy::copy(view< const T, Abi, OA > A, view< T, Abi, OB > B)
References BATMAT_UNROLLED_IVDEP_FOR, copy, batmat::linalg::General, batmat::linalg::LowerTriangular, batmat::ops::rotl, batmat::ops::rotr, batmat::linalg::UpperTriangular.
Referenced by batmat::linalg::copy, batmat::linalg::copy, copy, batmat::linalg::detail::gemm_diag::gemm_diag, batmat::linalg::detail::gemmt, batmat::linalg::detail::gemv, batmat::linalg::detail::trmm.
void batmat::linalg::detail::copy::copy(view< const T, Abi, OA > A, view< T, Abi, OB > B)
References copy, batmat::linalg::General.
void batmat::linalg::detail::copy::copy(view< const T, Abi, OA > A, view< T, Abi, OB > B)
References batmat::ops::ColsRegTranspose, copy, batmat::foreach_chunked_merged, batmat::linalg::General, batmat::make_2d_lut, batmat::ops::RowsRegTranspose, batmat::ops::transpose.
CopyConfig batmat::linalg::detail::copy::apply_options(CopyConfig conf, Opts...)
References apply_options, batmat::linalg::get_mask, batmat::linalg::get_rotate, batmat::linalg::detail::copy::CopyConfig::mask, batmat::linalg::detail::copy::CopyConfig::rotate.
Referenced by apply_options, batmat::linalg::copy, batmat::linalg::copy.