batmat::linalg::micro_kernels::geqrf
index_t batmat::linalg::micro_kernels::geqrf::SizeR
Referenced by geqrf_diag_microkernel, geqrf_tail_microkernel.
index_t batmat::linalg::micro_kernels::geqrf::SizeS
const constinit auto batmat::linalg::micro_kernels::geqrf::microkernel_diag_lut
const constinit auto batmat::linalg::micro_kernels::geqrf::microkernel_full_lut
const constinit auto batmat::linalg::micro_kernels::geqrf::microkernel_tail_lut
const constinit auto batmat::linalg::micro_kernels::geqrf::microkernel_tail_lut_2
void batmat::linalg::micro_kernels::geqrf::geqrf_diag_microkernel(index_t k, triangular_accessor< T, Abi, SizeR< T, Abi > > W, uview< const T, Abi, OA > A, uview< T, Abi, OD > D) noexcept
References BATMAT_ASSUME, SizeR, UNROLL_FOR.
void batmat::linalg::micro_kernels::geqrf::geqrf_full_microkernel(index_t k, uview< const T, Abi, OA > A, uview< T, Abi, OD > D) noexcept
A (k×R) D (k×R).
References BATMAT_ASSUME, UNROLL_FOR.
void batmat::linalg::micro_kernels::geqrf::geqrf_tail_microkernel(index_t k, bool transposed, triangular_accessor< const T, Abi, SizeR< T, Abi > > W, uview< const T, Abi, OA > A, uview< T, Abi, OD > D, uview< const T, Abi, OB > B) noexcept
References BATMAT_ASSUME, SizeR, UNROLL_FOR.
std::pair< index_t, index_t > batmat::linalg::micro_kernels::geqrf::geqrf_W_size(view< T, Abi, OA > A)
Referenced by batmat::linalg::detail::geqrf, batmat::linalg::detail::geqrf_apply, geqrf_apply_register, geqrf_copy_register, batmat::linalg::geqrf_size_W.
void batmat::linalg::micro_kernels::geqrf::geqrf_copy_register(const view< const T, Abi, OA > A, const view< T, Abi, OD > D, const view< T, Abi > W) noexcept
Block hyperbolic Householder factorization update using register blocking.
This variant does not store the Householder representation W.
References batmat::Backward, BATMAT_ASSUME, batmat::foreach_chunked, geqrf_W_size.
Referenced by batmat::linalg::detail::geqrf.
void batmat::linalg::micro_kernels::geqrf::geqrf_apply_register(const view< const T, Abi, OA > A, const view< T, Abi, OD > D, const view< const T, Abi, OB > B, const view< const T, Abi > W, bool transposed) noexcept
Apply a block Householder transformation.
References batmat::Backward, BATMAT_ASSUME, batmat::foreach_chunked_merged, geqrf_apply_register, geqrf_W_size.
Referenced by batmat::linalg::detail::geqrf_apply, geqrf_apply_register.