batmat::linalg
void batmat::linalg::copy(VA &&A, VB &&B, Opts... opts)
B = A.
References BATMAT_ASSERT, copy.
void batmat::linalg::copy(Structured< VA, S > A, Structured< VB, S > B, Opts... opts)
B = A.
References BATMAT_ASSERT, copy, make_structured, batmat::linalg::Structured< M, S >::value.
void batmat::linalg::fill(simdified_value_t< VB > a, VB &&B)
B = A.
References fill.
void batmat::linalg::fill(simdified_value_t< VB > a, Structured< VB, S > B)
B = A.
References fill, make_structured, batmat::linalg::Structured< M, S >::value.
StorageOrder
using batmat::linalg::simdified_view_type = detail::simdified_view_type<std::remove_reference_t<V>>
Convert the given view or matrix type V (batmat::matrix::View or batmat::matrix::Matrix) to a batched view type using a deduced SIMD type.
This conversion takes place in the wrapper around the optimized implementations (which require views with a proper SIMD-compatible stride).
using batmat::linalg::simdified_view_t = typename simdified_view_type<V>::type
using batmat::linalg::simdified_value_t = typename detail::simdified_value<V>::type
using batmat::linalg::simdified_abi_t = typename detail::simdified_abi<V>::type
using batmat::linalg::simdified_multi_view_type = detail::simdified_multi_view_type<std::remove_reference_t<V>>
using batmat::linalg::simdified_multi_view_t = typename simdified_multi_view_type<V>::type
using batmat::linalg::view = simd_view_types<std::remove_const_t<T>, Abi>::template view<T, Order>
using batmat::linalg::matrix = simd_view_types<std::remove_const_t<T>, Abi>::template matrix<T, Order>
using batmat::linalg::real_view = simd_view_types<real_t, Abi>::template view<const real_t, Order>
using batmat::linalg::mut_real_view = simd_view_types<real_t, Abi>::template view<real_t, Order>
track_zeros_t<Z> batmat::linalg::track_zeros
with_shift_A_t<I> batmat::linalg::with_shift_A
with_rotate_B_t<I> batmat::linalg::with_rotate_B
with_rotate_C_t<I> batmat::linalg::with_rotate_C
with_rotate_D_t<I> batmat::linalg::with_rotate_D
with_mask_D_t<I> batmat::linalg::with_mask_D
std::optional<int> batmat::linalg::shift_A
Referenced by batmat::linalg::detail::apply_gemm_options, batmat::linalg::detail::apply_gemv_options.
std::optional<int> batmat::linalg::shift_A< T, Ts... >
std::optional<int> batmat::linalg::shift_A< with_shift_A_t< I >, Ts... >
std::optional<int> batmat::linalg::rotate_B
Referenced by batmat::linalg::detail::apply_gemm_options, batmat::linalg::detail::apply_gemv_options.
std::optional<int> batmat::linalg::rotate_B< T, Ts... >
std::optional<int> batmat::linalg::rotate_B< with_rotate_B_t< I >, Ts... >
std::optional<int> batmat::linalg::rotate_C
Referenced by batmat::linalg::detail::apply_gemm_options, batmat::linalg::detail::apply_gemv_options.
std::optional<int> batmat::linalg::rotate_C< T, Ts... >
std::optional<int> batmat::linalg::rotate_C< with_rotate_C_t< I >, Ts... >
std::optional<int> batmat::linalg::rotate_D
Referenced by batmat::linalg::detail::apply_gemm_options, batmat::linalg::detail::apply_gemv_options.
std::optional<int> batmat::linalg::rotate_D< T, Ts... >
std::optional<int> batmat::linalg::rotate_D< with_rotate_D_t< I >, Ts... >
std::optional<int> batmat::linalg::mask_D
Referenced by batmat::linalg::detail::apply_gemm_options, batmat::linalg::detail::apply_gemv_options.
std::optional<int> batmat::linalg::mask_D< T, Ts... >
std::optional<int> batmat::linalg::mask_D< with_mask_D_t< I >, Ts... >
bool batmat::linalg::is_shift_opt
bool batmat::linalg::is_shift_opt< with_shift_A_t< I > >
bool batmat::linalg::is_shift_opt< with_rotate_B_t< I > >
bool batmat::linalg::is_shift_opt< with_rotate_C_t< I > >
bool batmat::linalg::is_shift_opt< with_rotate_D_t< I > >
bool batmat::linalg::is_shift_opt< with_mask_D_t< I > >
with_rotate_t<I> batmat::linalg::with_rotate
with_mask_t<I> batmat::linalg::with_mask
std::optional<int> batmat::linalg::get_rotate
Referenced by batmat::linalg::detail::copy::apply_options.
std::optional<int> batmat::linalg::get_rotate< T, Ts... >
std::optional<int> batmat::linalg::get_rotate< with_rotate_t< I >, Ts... >
std::optional<int> batmat::linalg::get_mask
Referenced by batmat::linalg::detail::copy::apply_options.
std::optional<int> batmat::linalg::get_mask< T, Ts... >
std::optional<int> batmat::linalg::get_mask< with_mask_t< I >, Ts... >
bool batmat::linalg::is_rotate_opt
bool batmat::linalg::is_rotate_opt< with_rotate_t< I > >
bool batmat::linalg::is_rotate_opt< with_mask_t< I > >
bool batmat::linalg::simdify_compatible
bool batmat::linalg::simdify_compatible< V, Vs... >
with_rotate_A_t<I> batmat::linalg::with_rotate_A
simdified_view_t< decltype(a)> batmat::linalg::simdify(simdifiable auto &&a)
Referenced by add_diag, axpby, axpby, axpy, axpy, clamp, clamp, clamp_resid, compress_masks, compress_masks_count, compress_masks_sqrt, compress_masks_sqrt, copy, copy, copy_diag, dot, fill, fill, for_each_elementwise, gemm_diag, gemm_diag_add, gemm_diag_sub, gemv, gemv_add, gemv_neg, gemv_sub, hadamard, hadamard, hyhound_diag, hyhound_diag, hyhound_diag_2, hyhound_diag_apply, hyhound_diag_apply, hyhound_diag_cyclic, hyhound_diag_riccati, hyhound_sign, hyhound_size_W, norm_2_squared, norms_all, potrf, potrf, scale, scale, symm_add, symv, symv_add, symv_neg, symv_sub, syomv, syomv_neg, syrk, syrk, syrk_add, syrk_add_potrf, syrk_diag, syrk_diag_add, syrk_diag_add_potrf, syrk_diag_sub, syrk_neg, syrk_neg, syrk_sub, syrk_sub_potrf, transform2_elementwise, transform_elementwise, transform_n_diag, transform_n_elementwise, trmm, trmm_add, trmm_neg, trmm_sub, trtri, trtri, weighted_norm_sq, weighted_norm_sq_diff.
simdified_multi_view_t< decltype(a)> batmat::linalg::simdify(simdifiable_multi auto &&a)
void batmat::linalg::simdify(const Structured< M, S > &)=delete
cached_uview< Order==StorageOrder::ColMajor ? Cols :Rows, T, Abi, Order > batmat::linalg::with_cached_access(const uview< T, Abi, Order > &o) noexcept
References with_cached_access.
Referenced by batmat::linalg::micro_kernels::gemm::gemm_copy_microkernel, batmat::linalg::micro_kernels::gemm_diag::gemm_diag_copy_microkernel, batmat::linalg::micro_kernels::gemv::gemv_copy_microkernel, batmat::linalg::micro_kernels::hyhound::hyhound_diag_diag_microkernel, batmat::linalg::micro_kernels::hyhound::hyhound_diag_full_microkernel, batmat::linalg::micro_kernels::hyhound::hyhound_diag_tail_microkernel, batmat::linalg::micro_kernels::potrf::potrf_copy_microkernel, batmat::linalg::micro_kernels::symv::symv_copy_microkernel, batmat::linalg::micro_kernels::syomv::syomv_microkernel, batmat::linalg::micro_kernels::trtri::trmm_microkernel, batmat::linalg::micro_kernels::potrf::trsm_copy_microkernel, batmat::linalg::micro_kernels::trsm::trsm_copy_microkernel, batmat::linalg::micro_kernels::trtri::trtri_copy_microkernel, with_cached_access, with_cached_access, with_cached_access.
cached_uview< Cols, T, Abi, StorageOrder::ColMajor > batmat::linalg::with_cached_access(const uview< T, Abi, StorageOrder::ColMajor > &o) noexcept
References with_cached_access.
uview< T, Abi, StorageOrder::RowMajor > batmat::linalg::with_cached_access(const uview< T, Abi, StorageOrder::RowMajor > &o) noexcept
References with_cached_access.
cached_uview< Rows, T, Abi, StorageOrder::RowMajor > batmat::linalg::with_cached_access(const uview< T, Abi, StorageOrder::RowMajor > &o) noexcept
References with_cached_access.
uview< T, Abi, StorageOrder::ColMajor > batmat::linalg::with_cached_access(const uview< T, Abi, StorageOrder::ColMajor > &o) noexcept
References with_cached_access.