function(batmat_at_least_O1 tgt)
    set(GCC_ISH $<OR:$<CXX_COMPILER_ID:GNU>,$<CXX_COMPILER_ID:Clang>,$<CXX_COMPILER_ID:AppleClang>>)
    target_compile_options(${tgt} PRIVATE "$<$<AND:$<CONFIG:Debug>,${GCC_ISH}>:-O1>")
endfunction()

function(batmat_codegen_micro_kernels tgt headers_target)

    set(SIGNS_gemm "false" "true")
    set(SIGNS_gemm-diag "false" "true")
    set(SIGNS_gemv "false" "true")
    set(SIGNS_symv "false" "true")
    set(SIGNS_syomv "false" "true")
    set(SIGNS_trsm "false")
    set(SIGNS_potrf "false" "true")
    set(SIGNS_trtri "false")
    set(SIGNS_hyhound "false" "true")
    set(SIGNS_geqrf "false")

    add_library(${tgt}-micro-kernels INTERFACE)
    list(APPEND BATMAT_CODEGEN_TARGETS ${tgt}-micro-kernels)
    set(OUT_DIR "${CMAKE_CURRENT_BINARY_DIR}/${tgt}/codegen")
    set(TPP_DIR "batmat/linalg/micro-kernels")

    function(batmat_add_micro_kernels op)
        add_library(${tgt}-micro-kernels-${op})
        batmat_at_least_O1(${tgt}-micro-kernels-${op})
        target_link_libraries(${tgt}-micro-kernels-${op} PRIVATE ${headers_target} warnings)
        target_precompile_headers(${tgt}-micro-kernels-${op} PRIVATE <${TPP_DIR}/${op}.tpp>)
        generate_export_header(${tgt}-micro-kernels-${op} BASE_NAME "${tgt}-${op}"
            EXPORT_FILE_NAME export/batmat/micro-kernels/${op}/export.h)
        target_sources(${tgt}-micro-kernels-${op} PUBLIC FILE_SET HEADERS
            BASE_DIRS ${CMAKE_CURRENT_BINARY_DIR}/export
            FILES ${CMAKE_CURRENT_BINARY_DIR}/export/batmat/micro-kernels/${op}/export.h)
        target_link_libraries(${tgt}-micro-kernels INTERFACE ${tgt}-micro-kernels-${op})
        if (CMAKE_CXX_COMPILER_ID MATCHES "Clang")
            target_compile_options(${tgt}-micro-kernels-${op} PRIVATE "-ffp-contract=fast")
        endif()
        set_target_properties(${tgt}-micro-kernels-${op} PROPERTIES UNITY_BUILD_MODE "GROUP")
        list(APPEND BATMAT_CODEGEN_TARGETS ${tgt}-micro-kernels-${op})
        set(BATMAT_CODEGEN_TARGETS ${BATMAT_CODEGEN_TARGETS} PARENT_SCOPE)
    endfunction()

    macro(instantiate_gemm out T Abi Conf OA OB OC OD)
        string(APPEND ${out} "template BATMAT_LINALG_GEMM_EXPORT void gemm_copy_register<${T}, ${Abi}, ${Conf}, ${OA}, ${OB}, ${OC}, ${OD}>(view<const ${T}, ${Abi}, ${OA}> A, view<const ${T}, ${Abi}, ${OB}> B, std::optional<view<const ${T}, ${Abi}, ${OC}>> C, view<${T}, ${Abi}, ${OD}> D) noexcept;\n")
        string(APPEND ${out} "template BATMAT_LINALG_GEMM_EXPORT const constinit decltype(detail::gemm_copy_lut<${T}, ${Abi}, ${Conf}, ${OA}, ${OB}, ${OC}, ${OD}>) gemm_copy_lut<${T}, ${Abi}, ${Conf}, ${OA}, ${OB}, ${OC}, ${OD}>;\n")
    endmacro()

    macro(instantiate_gemm_diag out T Abi Conf OA OB OC OD)
        string(APPEND ${out} "template BATMAT_LINALG_GEMM_DIAG_EXPORT void gemm_diag_copy_register<${T}, ${Abi}, ${Conf}, ${OA}, ${OB}, ${OC}, ${OD}>(view<const ${T}, ${Abi}, ${OA}> A, view<const ${T}, ${Abi}, ${OB}> B, std::optional<view<const ${T}, ${Abi}, ${OC}>> C, view<${T}, ${Abi}, ${OD}> D, view<const ${T}, ${Abi}> diag) noexcept;\n")
    endmacro()

    macro(instantiate_gemv out T Abi Conf OA)
        string(APPEND ${out} "template BATMAT_LINALG_GEMV_EXPORT void gemv_copy_register<${T}, ${Abi}, ${Conf}, ${OA}>(view<const ${T}, ${Abi}, ${OA}> A, view<const ${T}, ${Abi}> B, std::optional<view<const ${T}, ${Abi}>> C, view<${T}, ${Abi}> D) noexcept;\n")
    endmacro()

    macro(instantiate_symv out T Abi Conf OA)
        string(APPEND ${out} "template BATMAT_LINALG_SYMV_EXPORT void symv_copy_register<${T}, ${Abi}, ${Conf}, ${OA}>(view<const ${T}, ${Abi}, ${OA}> A, view<const ${T}, ${Abi}> B, std::optional<view<const ${T}, ${Abi}>> C, view<${T}, ${Abi}> D) noexcept;\n")
    endmacro()

    macro(instantiate_syomv out T Abi Conf OA OB OD)
        string(APPEND ${out} "template BATMAT_LINALG_SYOMV_EXPORT void syomv_register<${T}, ${Abi}, ${Conf}, ${OA}, ${OB}, ${OD}>(view<const ${T}, ${Abi}, ${OA}> A, view<const ${T}, ${Abi}, ${OB}> B, view<${T}, ${Abi}, ${OD}> D) noexcept;\n")
    endmacro()

    macro(instantiate_hyhound out T Abi Conf OL OA)
        string(APPEND ${out} "template BATMAT_LINALG_HYHOUND_EXPORT void hyhound_diag_register<${T}, ${Abi}, ${Conf}, ${OL}, ${OA}>(view<${T}, ${Abi}, ${OL}> L, view<${T}, ${Abi}, ${OA}> A, view<const ${T}, ${Abi}> diag) noexcept;\n")
        string(APPEND ${out} "template BATMAT_LINALG_HYHOUND_EXPORT void hyhound_diag_register<${T}, ${Abi}, ${Conf}, ${OL}, ${OA}>(view<${T}, ${Abi}, ${OL}> L, view<${T}, ${Abi}, ${OA}> A, view<const ${T}, ${Abi}> diag, view<${T}, ${Abi}> W) noexcept;\n")
        string(APPEND ${out} "template BATMAT_LINALG_HYHOUND_EXPORT void hyhound_diag_apply_register<${T}, ${Abi}, ${Conf}, ${OL}, ${OA}>(view<${T}, ${Abi}, ${OL}> L, view<const ${T}, ${Abi}, ${OA}> Ain, view<${T}, ${Abi}, ${OA}> Aout, view<const ${T}, ${Abi}, ${OA}> B, view<const ${T}, ${Abi}> D, view<const ${T}, ${Abi}> W, index_t kA_in_offset) noexcept;\n")
    endmacro()

    macro(instantiate_hyhound_2 out T Abi Conf OL1 OA1 OL2 OA2)
        string(APPEND ${out} "template BATMAT_LINALG_HYHOUND_EXPORT void hyhound_diag_2_register<${T}, ${Abi}, ${Conf}, ${OL1}, ${OA1}, ${OL2}, ${OA2}>(view<${T}, ${Abi}, ${OL1}> L11, view<${T}, ${Abi}, ${OA1}> A1, view<${T}, ${Abi}, ${OL2}> L21, view<${T}, ${Abi}, ${OA2}> A2, view<const ${T}, ${Abi}> D) noexcept;\n")
        string(APPEND ${out} "template BATMAT_LINALG_HYHOUND_EXPORT void hyhound_diag_cyclic_register<${T}, ${Abi}, ${Conf}, ${OL1}, ${OA1}, ${OL2}, ${OA2}>(view<${T}, ${Abi}, ${OL1}> L11, view<${T}, ${Abi}, ${OA1}> A1, view<${T}, ${Abi}, ${OL2}> L21, view<const ${T}, ${Abi}, ${OA1}> A22, view<${T}, ${Abi}, ${OA1}> A2_out, view<${T}, ${Abi}, ${OA2}> L31, view<const ${T}, ${Abi}, ${OA1}> A31, view<${T}, ${Abi}, ${OA1}> A3_out, view<const ${T}, ${Abi}> D) noexcept;\n")
        string(APPEND ${out} "template BATMAT_LINALG_HYHOUND_EXPORT void hyhound_diag_riccati_register<${T}, ${Abi}, ${Conf}, ${OL1}, ${OA1}, ${OL2}, ${OA2}>(view<${T}, ${Abi}, ${OL1}> L11, view<${T}, ${Abi}, ${OA1}> A1, view<${T}, ${Abi}, ${OL1}> L21, view<const ${T}, ${Abi}, ${OA1}> A2, view<${T}, ${Abi}, ${OA1}> A2_out, view<${T}, ${Abi}, ${OL2}> Lu1, view<${T}, ${Abi}, ${OA2}> Au_out, view<const ${T}, ${Abi}> D, bool shift_A_out) noexcept;\n")
    endmacro()

    macro(instantiate_potrf out T Abi Conf OA OCD)
        string(APPEND ${out} "template BATMAT_LINALG_POTRF_EXPORT void potrf_copy_register<${T}, ${Abi}, ${Conf}, ${OA}, ${OCD}>(view<const ${T}, ${Abi}, ${OA}> A, view<const ${T}, ${Abi}, ${OCD}> C, view<${T}, ${Abi}, ${OCD}> D, ${T} regularization, diag_view_type<const ${T}, ${Abi}, ${Conf}> diag) noexcept;\n")
    endmacro()

    macro(instantiate_trsm out T Abi Conf OA OB OD)
        string(APPEND ${out} "template BATMAT_LINALG_TRSM_EXPORT void trsm_copy_register<${T}, ${Abi}, ${Conf}, ${OA}, ${OB}, ${OD}>(view<const ${T}, ${Abi}, ${OA}> A, view<const ${T}, ${Abi}, ${OB}> B, view<${T}, ${Abi}, ${OD}> D) noexcept;\n")
    endmacro()

    macro(instantiate_trtri out T Abi Conf OA OD)
        string(APPEND ${out} "template BATMAT_LINALG_TRTRI_EXPORT void trtri_copy_register<${T}, ${Abi}, ${Conf}, ${OA}, ${OD}>(view<const ${T}, ${Abi}, ${OA}> A, view<${T}, ${Abi}, ${OD}> D) noexcept;\n")
    endmacro()

    macro(instantiate_geqrf out T Abi Conf OA OD)
        string(APPEND ${out} "template BATMAT_LINALG_GEQRF_EXPORT void geqrf_copy_register<${T}, ${Abi}, ${Conf}, ${OA}, ${OD}>(view<const ${T}, ${Abi}, ${OA}> A, view<${T}, ${Abi}, ${OD}> D, view<${T}, ${Abi}> W) noexcept;\n")
    endmacro()

    macro(instantiate_geqrf_apply out T Abi Conf OA OD OB)
        string(APPEND ${out} "template BATMAT_LINALG_GEQRF_EXPORT void geqrf_apply_register<${T}, ${Abi}, ${Conf}, ${OA}, ${OD}, ${OB}>(view<const ${T}, ${Abi}, ${OA}> A, view<${T}, ${Abi}, ${OD}> D, view<const ${T}, ${Abi}, ${OB}> B, view<const ${T}, ${Abi}> W, bool transposed) noexcept;\n")
    endmacro()

    batmat_add_micro_kernels("gemm")
    batmat_add_micro_kernels("gemm-diag")
    batmat_add_micro_kernels("gemv")
    batmat_add_micro_kernels("symv")
    batmat_add_micro_kernels("syomv")
    batmat_add_micro_kernels("hyhound")
    batmat_add_micro_kernels("potrf")
    batmat_add_micro_kernels("trsm")
    batmat_add_micro_kernels("trtri")
    batmat_add_micro_kernels("geqrf")

    foreach(DType_ IN LISTS BATMAT_DTYPES)
        string(TOUPPER "${DType_}" DTypeU)
        string(REPLACE "std_" "std::" DType "${DType_}")
        foreach(VL IN LISTS BATMAT_VECTOR_LENGTHS_${DTypeU})
            set(Abi "datapar::deduced_abi<${DType}, ${VL}>")
            # Compute the shifts for this vector length
            set(shifts "")
            set(s 1)
            while(s LESS VL)
                list(APPEND shifts "${s}" "-${s}")
                math(EXPR s "${s} << 1")
            endwhile()

            # GEMM, TRMM, GEMMT, LAUUM, etc.
            macro(batmat_instantiate_gemm_like name struc_config)
                # No shifts
                set(op "gemm")
                set(op_ "gemm")
                foreach(Negate "false" "true")
                    foreach(OA "ColMajor" "RowMajor")
                        set(instantiations "")
                        foreach(OB "ColMajor" "RowMajor")
                            foreach(OC "ColMajor" "RowMajor")
                                set(Conf ".negate=${Negate}, ${struc_config}")
                                instantiate_gemm(instantiations "${DType}" "${Abi}" "{${Conf}}" "${OA}" "${OB}" "${OC}" "${OC}")
                            endforeach()
                        endforeach()
                        configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/inst.cpp.in" "${OUT_DIR}/${name}-${DType_}-${VL}-${Negate}-${OA}.cpp" @ONLY)
                        target_sources(${tgt}-micro-kernels-${op} PRIVATE "${OUT_DIR}/${name}-${DType_}-${VL}-${Negate}-${OA}.cpp")
                        set_source_files_properties("${OUT_DIR}/${name}-${DType_}-${VL}-${Negate}-${OA}.cpp" PROPERTIES UNITY_GROUP "${VL}-${DType_}-${Negate}-${OA}-gemm")
                    endforeach()
                endforeach()
                if (VL GREATER 1)
                    # Shift A and B
                    foreach(Negate "false" "true")
                        foreach(OA "ColMajor" "RowMajor")
                            set(instantiations "")
                            foreach(OB "ColMajor" "RowMajor")
                                foreach(OC "ColMajor" "RowMajor")
                                    foreach(shift -1 1)
                                        set(Conf ".negate=${Negate}, .shift_A=${shift}, ${struc_config}")
                                        instantiate_gemm(instantiations "${DType}" "${Abi}" "{${Conf}}" "${OA}" "${OB}" "${OC}" "${OC}")
                                        set(Conf ".negate=${Negate}, .rotate_B=${shift}, ${struc_config}")
                                        instantiate_gemm(instantiations "${DType}" "${Abi}" "{${Conf}}" "${OA}" "${OB}" "${OC}" "${OC}")
                                    endforeach()
                                endforeach()
                            endforeach()
                            configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/inst.cpp.in" "${OUT_DIR}/${name}-shift-ab-${DType_}-${VL}-${Negate}-${OA}.cpp" @ONLY)
                            target_sources(${tgt}-micro-kernels-${op} PRIVATE "${OUT_DIR}/${name}-shift-ab-${DType_}-${VL}-${Negate}-${OA}.cpp")
                            set_source_files_properties("${OUT_DIR}/${name}-shift-ab-${DType_}-${VL}-${Negate}-${OA}.cpp" PROPERTIES UNITY_GROUP "${VL}-${DType_}-${Negate}-${OA}-gemm-shift-ab")
                        endforeach()
                    endforeach()
                    # Shift C and D
                    foreach(Negate "false" "true")
                        foreach(OA "ColMajor" "RowMajor")
                            foreach(OB "ColMajor" "RowMajor")
                                foreach(OC "ColMajor" "RowMajor")
                                    set(instantiations "")
                                    foreach(shift IN LISTS shifts)
                                        set(Conf ".negate=${Negate}, .rotate_C=${shift}, .rotate_D=${shift}, .mask_D=0, ${struc_config}")
                                        instantiate_gemm(instantiations "${DType}" "${Abi}" "{${Conf}}" "${OA}" "${OB}" "${OC}" "${OC}")
                                        set(Conf ".negate=${Negate}, .rotate_C=${shift}, .rotate_D=${shift}, .mask_D=${shift}, ${struc_config}")
                                        instantiate_gemm(instantiations "${DType}" "${Abi}" "{${Conf}}" "${OA}" "${OB}" "${OC}" "${OC}")
                                    endforeach()
                                    configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/inst.cpp.in" "${OUT_DIR}/${name}-shift-cd-${DType_}-${VL}-${Negate}-${OA}-${OB}-${OC}.cpp" @ONLY)
                                    target_sources(${tgt}-micro-kernels-${op} PRIVATE "${OUT_DIR}/${name}-shift-cd-${DType_}-${VL}-${Negate}-${OA}-${OB}-${OC}.cpp")
                                    set_source_files_properties("${OUT_DIR}/${name}-shift-cd-${DType_}-${VL}-${Negate}-${OA}-${OB}-${OC}.cpp" PROPERTIES UNITY_GROUP "${VL}-${DType_}-${Negate}-${OA}-${OB}-${OC}-gemm-shift-cd")
                                endforeach()
                            endforeach()
                        endforeach()
                    endforeach()
                endif()
            endmacro()
            batmat_instantiate_gemm_like("gemm" "")
            batmat_instantiate_gemm_like("trmm-la" ".struc_A=LowerTriangular")
            batmat_instantiate_gemm_like("trmm-ua" ".struc_A=UpperTriangular")
            batmat_instantiate_gemm_like("trmm-lb" ".struc_B=LowerTriangular")
            batmat_instantiate_gemm_like("trmm-ub" ".struc_B=UpperTriangular")
            batmat_instantiate_gemm_like("gemmt-l" ".struc_C=LowerTriangular")
            batmat_instantiate_gemm_like("gemmt-u" ".struc_C=UpperTriangular")
            batmat_instantiate_gemm_like("trtrtr-l" ".struc_A=LowerTriangular, .struc_B=LowerTriangular, .struc_C=LowerTriangular")
            batmat_instantiate_gemm_like("trtrtr-u" ".struc_A=UpperTriangular, .struc_B=UpperTriangular, .struc_C=UpperTriangular")
            batmat_instantiate_gemm_like("lauum-ull" ".struc_A=UpperTriangular, .struc_B=LowerTriangular, .struc_C=LowerTriangular")  # L = LᵀL
            batmat_instantiate_gemm_like("lauum-ulu" ".struc_A=UpperTriangular, .struc_B=LowerTriangular, .struc_C=UpperTriangular")  # U = UUᵀ
            batmat_instantiate_gemm_like("lauum-lul" ".struc_A=LowerTriangular, .struc_B=UpperTriangular, .struc_C=LowerTriangular")  # L = LLᵀ
            batmat_instantiate_gemm_like("lauum-luu" ".struc_A=LowerTriangular, .struc_B=UpperTriangular, .struc_C=UpperTriangular")  # U = UᵀU

            # GEMM with diagonal scaling
            macro(batmat_instantiate_gemm_diag name struc_config)
                set(op "gemm-diag")
                set(op_ "gemm_diag")
                foreach(Negate "false" "true")
                    set(instantiations "")
                    foreach(OA "ColMajor" "RowMajor")
                        foreach(OB "ColMajor" "RowMajor")
                            foreach(OC "ColMajor" "RowMajor")
                                foreach(Tz "true" "false")
                                    set(Conf ".negate=${Negate}, .track_zeros=${Tz}, ${struc_config}")
                                    instantiate_gemm_diag(instantiations "${DType}" "${Abi}" "{${Conf}}" "${OA}" "${OB}" "${OC}" "${OC}")
                                endforeach()
                            endforeach()
                        endforeach()
                    endforeach()
                    configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/inst.cpp.in" "${OUT_DIR}/${name}-${DType_}-${VL}-${Negate}.cpp" @ONLY)
                    target_sources(${tgt}-micro-kernels-${op} PRIVATE "${OUT_DIR}/${name}-${DType_}-${VL}-${Negate}.cpp")
                    set_source_files_properties("${OUT_DIR}/${name}-${DType_}-${VL}-${Negate}.cpp" PROPERTIES UNITY_GROUP "${VL}-${DType_}-${Negate}-gemm-diag")
                endforeach()
            endmacro()
            batmat_instantiate_gemm_diag("gemm-diag" "")
            batmat_instantiate_gemm_diag("gemmt-diag-l" ".struc_C=LowerTriangular")
            batmat_instantiate_gemm_diag("gemmt-diag-u" ".struc_C=UpperTriangular")

            # GEMV
            macro(batmat_instantiate_gemv_like name struc_config)
                # No shifts
                set(op "gemv")
                set(op_ "gemv")
                set(instantiations "")
                foreach(OA "ColMajor" "RowMajor")
                    foreach(Negate "false" "true")
                        set(Conf ".negate=${Negate}, ${struc_config}")
                        instantiate_gemv(instantiations "${DType}" "${Abi}" "{${Conf}}" "${OA}")
                    endforeach()
                endforeach()
                configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/inst.cpp.in" "${OUT_DIR}/${name}-${DType_}-${VL}.cpp" @ONLY)
                target_sources(${tgt}-micro-kernels-${op} PRIVATE "${OUT_DIR}/${name}-${DType_}-${VL}.cpp")
                set_source_files_properties("${OUT_DIR}/${name}-${DType_}-${VL}.cpp" PROPERTIES UNITY_GROUP "${VL}-${DType_}-gemv")
                if (VL GREATER 1)
                    # Shift A and B
                    set(instantiations "")
                    foreach(OA "ColMajor" "RowMajor")
                        foreach(Negate "false" "true")
                            foreach(shift -1 1)
                                set(Conf ".negate=${Negate}, .shift_A=${shift}, ${struc_config}")
                                instantiate_gemv(instantiations "${DType}" "${Abi}" "{${Conf}}" "${OA}")
                                set(Conf ".negate=${Negate}, .rotate_B=${shift}, ${struc_config}")
                                instantiate_gemv(instantiations "${DType}" "${Abi}" "{${Conf}}" "${OA}")
                            endforeach()
                        endforeach()
                    endforeach()
                    configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/inst.cpp.in" "${OUT_DIR}/${name}-shift-ab-${DType_}-${VL}.cpp" @ONLY)
                    target_sources(${tgt}-micro-kernels-${op} PRIVATE "${OUT_DIR}/${name}-shift-ab-${DType_}-${VL}.cpp")
                    set_source_files_properties("${OUT_DIR}/${name}-shift-ab-${DType_}-${VL}.cpp" PROPERTIES UNITY_GROUP "${VL}-${DType_}-gemv-shift-ab")
                    # Shift C and D
                    set(instantiations "")
                    foreach(OA "ColMajor" "RowMajor")
                        foreach(Negate "false" "true")
                            foreach(shift IN LISTS shifts)
                                set(Conf ".negate=${Negate}, .rotate_C=${shift}, .rotate_D=${shift}, .mask_D=0, ${struc_config}")
                                instantiate_gemv(instantiations "${DType}" "${Abi}" "{${Conf}}" "${OA}")
                                set(Conf ".negate=${Negate}, .rotate_C=${shift}, .rotate_D=${shift}, .mask_D=${shift}, ${struc_config}")
                                instantiate_gemv(instantiations "${DType}" "${Abi}" "{${Conf}}" "${OA}")
                            endforeach()
                        endforeach()
                    endforeach()
                    configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/inst.cpp.in" "${OUT_DIR}/${name}-shift-cd-${DType_}-${VL}.cpp" @ONLY)
                    target_sources(${tgt}-micro-kernels-${op} PRIVATE "${OUT_DIR}/${name}-shift-cd-${DType_}-${VL}.cpp")
                    set_source_files_properties("${OUT_DIR}/${name}-shift-cd-${DType_}-${VL}.cpp" PROPERTIES UNITY_GROUP "${VL}-${DType_}-gemv-shift-cd")
                endif()
            endmacro()
            batmat_instantiate_gemv_like("gemv" "")

            # SYMV
            macro(batmat_instantiate_symv_like name struc_config)
                # No shifts
                set(op "symv")
                set(op_ "symv")
                set(instantiations "")
                foreach(OA "ColMajor" "RowMajor")
                    foreach(Negate "false" "true")
                        set(Conf ".negate=${Negate}, ${struc_config}")
                        instantiate_symv(instantiations "${DType}" "${Abi}" "{${Conf}}" "${OA}")
                    endforeach()
                endforeach()
                configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/inst.cpp.in" "${OUT_DIR}/${name}-${DType_}-${VL}.cpp" @ONLY)
                target_sources(${tgt}-micro-kernels-${op} PRIVATE "${OUT_DIR}/${name}-${DType_}-${VL}.cpp")
                set_source_files_properties("${OUT_DIR}/${name}-${DType_}-${VL}.cpp" PROPERTIES UNITY_GROUP "${VL}-${DType_}-symv")
            endmacro()
            batmat_instantiate_symv_like("symv-l" ".struc_A=LowerTriangular")
            batmat_instantiate_symv_like("symv-u" ".struc_A=UpperTriangular")

            # SYOMV
            macro(batmat_instantiate_syomv_like name struc_config)
                # No shifts
                set(op "syomv")
                set(op_ "syomv")
                set(instantiations "")
                foreach(OA "ColMajor" "RowMajor")
                    foreach(OB "ColMajor" "RowMajor")
                        foreach(OD "ColMajor" "RowMajor")
                            foreach(Negate "false" "true")
                                set(Conf ".negate=${Negate}, ${struc_config}")
                                instantiate_syomv(instantiations "${DType}" "${Abi}" "{${Conf}}" "${OA}" "${OB}" "${OD}")
                            endforeach()
                        endforeach()
                    endforeach()
                endforeach()
                configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/inst.cpp.in" "${OUT_DIR}/${name}-${DType_}-${VL}.cpp" @ONLY)
                target_sources(${tgt}-micro-kernels-${op} PRIVATE "${OUT_DIR}/${name}-${DType_}-${VL}.cpp")
                set_source_files_properties("${OUT_DIR}/${name}-${DType_}-${VL}.cpp" PROPERTIES UNITY_GROUP "${VL}-${DType_}-symv")
            endmacro()
            batmat_instantiate_syomv_like("syomv-l" ".struc_A=LowerTriangular")
            # batmat_instantiate_syomv_like("syomv-u" ".struc_A=UpperTriangular")  # TODO

            # HYH
            macro(batmat_instantiate_hyhound name struc_config)
                set(op "hyhound")
                set(op_ "hyhound")
                foreach(SignOnly "false" "true")
                    set(instantiations "")
                    foreach(OL "ColMajor" "RowMajor")
                        foreach(OA "ColMajor" "RowMajor")
                            set(Conf ".sign_only=${SignOnly}, ${struc_config}")
                            instantiate_hyhound(instantiations "${DType}" "${Abi}" "{${Conf}}" "${OL}" "${OA}")
                        endforeach()
                    endforeach()
                    configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/inst.cpp.in" "${OUT_DIR}/${name}-${DType_}-${VL}-${SignOnly}.cpp" @ONLY)
                    target_sources(${tgt}-micro-kernels-${op} PRIVATE "${OUT_DIR}/${name}-${DType_}-${VL}-${SignOnly}.cpp")
                    set_source_files_properties("${OUT_DIR}/${name}-${DType_}-${VL}-${SignOnly}.cpp" PROPERTIES UNITY_GROUP "${VL}-${DType_}-${SignOnly}-hyhound")
                endforeach()
            endmacro()
            batmat_instantiate_hyhound("hyhound" "")
            macro(batmat_instantiate_hyhound_2 name struc_config)
                set(op "hyhound")
                set(op_ "hyhound")
                foreach(SignOnly "false" "true")
                    set(instantiations "")
                    foreach(OL1 "ColMajor" "RowMajor")
                        foreach(OA1 "ColMajor" "RowMajor")
                            foreach(OL2 "ColMajor" "RowMajor")
                                foreach(OA2 "ColMajor" "RowMajor")
                                    set(Conf ".sign_only=${SignOnly}, ${struc_config}")
                                    instantiate_hyhound_2(instantiations "${DType}" "${Abi}" "{${Conf}}" "${OL1}" "${OA1}" "${OL2}" "${OA2}")
                                endforeach()
                            endforeach()
                        endforeach()
                    endforeach()
                    configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/inst.cpp.in" "${OUT_DIR}/${name}-${DType_}-${VL}-${SignOnly}.cpp" @ONLY)
                    target_sources(${tgt}-micro-kernels-${op} PRIVATE "${OUT_DIR}/${name}-${DType_}-${VL}-${SignOnly}.cpp")
                    set_source_files_properties("${OUT_DIR}/${name}-${DType_}-${VL}-${SignOnly}.cpp" PROPERTIES UNITY_GROUP "${VL}-${DType_}-${SignOnly}-hyhound")
                endforeach()
            endmacro()
            batmat_instantiate_hyhound_2("hyhound2" "")

            # POTRF
            macro(batmat_instantiate_potrf name struc_config)
                set(op "potrf")
                set(op_ "potrf")
                foreach(Negate "false" "true")
                    foreach(Diag "none" "diag" "diag_sign_only")
                        set(instantiations "")
                        foreach(OA "ColMajor" "RowMajor")
                            foreach(OCD "ColMajor" "RowMajor")
                                set(Conf ".negate_A=${Negate}, .diag_A=KernelConfig::${Diag}, ${struc_config}")
                                instantiate_potrf(instantiations "${DType}" "${Abi}" "{${Conf}}" "${OA}" "${OCD}")
                            endforeach()
                        endforeach()
                        configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/inst.cpp.in" "${OUT_DIR}/${name}-${DType_}-${VL}-${Negate}-${Diag}.cpp" @ONLY)
                        target_sources(${tgt}-micro-kernels-${op} PRIVATE "${OUT_DIR}/${name}-${DType_}-${VL}-${Negate}-${Diag}.cpp")
                        set_source_files_properties("${OUT_DIR}/${name}-${DType_}-${VL}-${Negate}-${Diag}.cpp" PROPERTIES UNITY_GROUP "${VL}-${DType_}-${Negate}-${Diag}-potrf")
                    endforeach()
                endforeach()
            endmacro()
            batmat_instantiate_potrf("potrf-l" ".struc_C=LowerTriangular")
            # batmat_instantiate_potrf("potrf-u" ".struc_C=UpperTriangular")  # TODO

            # TRSM
            macro(batmat_instantiate_trsm name struc_config)
                set(op "trsm")
                set(op_ "trsm")
                foreach(OA "ColMajor" "RowMajor")
                    set(instantiations "")
                    foreach(OB "ColMajor" "RowMajor")
                        foreach(OD "ColMajor" "RowMajor")
                            set(Conf "${struc_config}, .rotate_B=0")
                            instantiate_trsm(instantiations "${DType}" "${Abi}" "{${Conf}}" "${OA}" "${OB}" "${OD}")
                            foreach(shift IN LISTS shifts)
                                set(Conf "${struc_config}, .rotate_B=${shift}")
                                instantiate_trsm(instantiations "${DType}" "${Abi}" "{${Conf}}" "${OA}" "${OB}" "${OD}")
                            endforeach()
                        endforeach()
                    endforeach()
                    configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/inst.cpp.in" "${OUT_DIR}/${name}-${DType_}-${VL}-${OA}.cpp" @ONLY)
                    target_sources(${tgt}-micro-kernels-${op} PRIVATE "${OUT_DIR}/${name}-${DType_}-${VL}-${OA}.cpp")
                    set_source_files_properties("${OUT_DIR}/${name}-${DType_}-${VL}-${OA}.cpp" PROPERTIES UNITY_GROUP "${VL}-${DType_}-${OA}-trsm")
                endforeach()
            endmacro()
            batmat_instantiate_trsm("trsm-l" ".struc_A=LowerTriangular")
            batmat_instantiate_trsm("trsm-u" ".struc_A=UpperTriangular")

            # TRTRI
            macro(batmat_instantiate_trtri name struc_config)
                set(op "trtri")
                set(op_ "trtri")
                set(instantiations "")
                foreach(OA "ColMajor" "RowMajor")
                    foreach(OD "ColMajor" "RowMajor")
                        set(Conf "${struc_config}")
                        instantiate_trtri(instantiations "${DType}" "${Abi}" "{${Conf}}" "${OA}" "${OD}")
                    endforeach()
                endforeach()
                configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/inst.cpp.in" "${OUT_DIR}/${name}-${DType_}-${VL}.cpp" @ONLY)
                target_sources(${tgt}-micro-kernels-${op} PRIVATE "${OUT_DIR}/${name}-${DType_}-${VL}.cpp")
                set_source_files_properties("${OUT_DIR}/${name}-${DType_}-${VL}.cpp" PROPERTIES UNITY_GROUP "${VL}-${DType_}-trtri")
            endmacro()
            batmat_instantiate_trtri("trtri-l" ".struc=LowerTriangular")
            # batmat_instantiate_trtri("trtri-u" ".struc=UpperTriangular")  # TODO

            # GEQRF
            macro(batmat_instantiate_geqrf name struc_config)
                set(op "geqrf")
                set(op_ "geqrf")
                set(instantiations "")
                foreach(OA "ColMajor" "RowMajor")
                    foreach(OD "ColMajor" "RowMajor")
                        set(Conf "${struc_config}")
                        instantiate_geqrf(instantiations "${DType}" "${Abi}" "{${Conf}}" "${OA}" "${OD}")
                        foreach(OB "ColMajor" "RowMajor")
                            instantiate_geqrf_apply(instantiations "${DType}" "${Abi}" "{${Conf}}" "${OA}" "${OD}" "${OB}")
                        endforeach()
                    endforeach()
                endforeach()
                configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/inst.cpp.in" "${OUT_DIR}/${name}-${DType_}-${VL}.cpp" @ONLY)
                target_sources(${tgt}-micro-kernels-${op} PRIVATE "${OUT_DIR}/${name}-${DType_}-${VL}.cpp")
                set_source_files_properties("${OUT_DIR}/${name}-${DType_}-${VL}.cpp" PROPERTIES UNITY_GROUP "${VL}-${DType_}-geqrf")
            endmacro()
            batmat_instantiate_geqrf("geqrf" "")

        endforeach()
    endforeach()

    set(BATMAT_CODEGEN_TARGETS ${BATMAT_CODEGEN_TARGETS} PARENT_SCOPE)
endfunction()
