batmat::matrix::Matrix
batmat::matrix::Matrix< T, I, S, D, O, A >::Matrix()=default
batmat::matrix::Matrix< T, I, S, D, O, A >::Matrix(layout_type layout)
batmat::matrix::Matrix< T, I, S, D, O, A >::Matrix(layout_type layout, uninitialized_t init)
batmat::matrix::Matrix< T, I, S, D, O, A >::Matrix(plain_layout_type p)
batmat::matrix::Matrix< T, I, S, D, O, A >::Matrix(plain_layout_type p, uninitialized_t init)
batmat::matrix::Matrix< T, I, S, D, O, A >::Matrix(const Matrix &o)
Copy the values from another matrix.
batmat::matrix::Matrix< T, I, S, D, O, A >::Matrix(Matrix &&o) noexcept
Matrix & batmat::matrix::Matrix< T, I, S, D, O, A >::operator=(Matrix &&o) noexcept
Cheap move assignment. No data is copied.
batmat::matrix::Matrix< T, I, S, D, O, A >::~Matrix()
void batmat::matrix::Matrix< T, I, S, D, O, A >::resize(layout_type new_layout)
Resize the matrix to a new layout, reallocating if the padded size changes.
Referenced by batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::assign_from_view.
value_type & batmat::matrix::Matrix< T, I, S, D, O, A >::operator()(index_type l, index_type r, index_type c)
Access a single element at layer l, row r and column c.
const value_type & batmat::matrix::Matrix< T, I, S, D, O, A >::operator()(index_type l, index_type r, index_type c) const
Access a single element at layer l, row r and column c.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::batch(index_type b)
Access a batch of batch_size() layers, starting at batch index b (i.e.
starting at layer b * batch_size()).
auto batmat::matrix::Matrix< T, I, S, D, O, A >::batch(index_type b) const
Access a batch of batch_size() layers, starting at batch index b (i.e.
starting at layer b * batch_size()).
auto batmat::matrix::Matrix< T, I, S, D, O, A >::batch_dyn(index_type b)
Same as batch(), but returns a view with a dynamic batch size.
If the total depth is not a multiple of the batch size, the last batch will have a smaller size.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::batch_dyn(index_type b) const
Same as batch(), but returns a view with a dynamic batch size.
If the total depth is not a multiple of the batch size, the last batch will have a smaller size.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::middle_batches(index_type b, index_type n, index_type stride=1)
Get a view of n batches starting at batch b, with a stride of stride layers.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::middle_batches(index_type b, index_type n, index_type stride=1) const
Get a view of n batches starting at batch b, with a stride of stride layers.
guanaqo::MatrixView< T, I, standard_stride_type, O > batmat::matrix::Matrix< T, I, S, D, O, A >::operator()(index_type l)
Access a single layer l as a non-batched view.
guanaqo::MatrixView< const T, I, standard_stride_type, O > batmat::matrix::Matrix< T, I, S, D, O, A >::operator()(index_type l) const
Access a single layer l as a non-batched view.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::first_layers(N n)
Get a view of the first n layers. Note that n can be a compile-time constant.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::first_layers(N n) const
Get a view of the first n layers. Note that n can be a compile-time constant.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::middle_layers(index_type l, N n)
Get a view of n layers starting at layer l.
Note that n can be a compile-time constant. l % batch_size() == 0 (i.e. the starting layer must be at the start of a batch).
auto batmat::matrix::Matrix< T, I, S, D, O, A >::middle_layers(index_type l, N n) const
Get a view of n layers starting at layer l.
Note that n can be a compile-time constant. l % batch_size() == 0 (i.e. the starting layer must be at the start of a batch).
value_type * batmat::matrix::Matrix< T, I, S, D, O, A >::data()
Get a pointer to the first element of the first layer.
Referenced by batmat::matrix::data, batmat::matrix::data.
const value_type * batmat::matrix::Matrix< T, I, S, D, O, A >::data() const
Get a pointer to the first element of the first layer.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::begin()
Iterate linearly (in storage order) over all elements of the view.
has_full_outer_stride() (i.e. no padding within layers). has_full_layer_stride() (i.e. no padding between batches).
auto batmat::matrix::Matrix< T, I, S, D, O, A >::begin() const
Iterate linearly (in storage order) over all elements of the view.
has_full_outer_stride() (i.e. no padding within layers). has_full_layer_stride() (i.e. no padding between batches).
auto batmat::matrix::Matrix< T, I, S, D, O, A >::end()
Sentinel for begin().
auto batmat::matrix::Matrix< T, I, S, D, O, A >::end() const
Sentinel for begin().
layout_type batmat::matrix::Matrix< T, I, S, D, O, A >::layout() const
Referenced by batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::operator=.
index_type batmat::matrix::Matrix< T, I, S, D, O, A >::size() const
Total number of elements in the view (excluding padding).
index_type batmat::matrix::Matrix< T, I, S, D, O, A >::padded_size() const
Total number of elements in the view (including all padding).
Referenced by batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::resize.
depth_type batmat::matrix::Matrix< T, I, S, D, O, A >::depth() const
Number of layers in the view (i.e. depth).
Referenced by batmat::matrix::depth.
index_type batmat::matrix::Matrix< T, I, S, D, O, A >::ceil_depth() const
The depth rounded up to a multiple of the batch size.
index_type batmat::matrix::Matrix< T, I, S, D, O, A >::num_batches() const
Number of batches in the view, i.e. ceil_depth() / batch_size().
index_type batmat::matrix::Matrix< T, I, S, D, O, A >::rows() const
Number of rows of the matrices.
Referenced by batmat::matrix::rows.
index_type batmat::matrix::Matrix< T, I, S, D, O, A >::cols() const
Number of columns of the matrices.
Referenced by batmat::matrix::cols.
index_type batmat::matrix::Matrix< T, I, S, D, O, A >::outer_size() const
The size of the outer dimension, i.e.
the number of columns for column-major storage, or the number of rows for row-major storage.
index_type batmat::matrix::Matrix< T, I, S, D, O, A >::inner_size() const
The size of the inner dimension, i.e.
the number of rows for column-major storage, or the number of columns for row-major storage.
index_type batmat::matrix::Matrix< T, I, S, D, O, A >::outer_stride() const
Outer stride of the matrices (leading dimension in BLAS parlance).
Should be multiplied by the batch size to get the actual number of elements.
Referenced by batmat::matrix::outer_stride.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::inner_stride() const
The inner stride of the matrices.
Should be multiplied by the batch size to get the actual number of elements.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::row_stride() const
The row stride of the matrices, i.e.
the distance between elements in consecutive rows in a given column. Should be multiplied by the batch size to get the actual number of elements.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::col_stride() const
The column stride of the matrices, i.e.
the distance between elements in consecutive columns in a given row. Should be multiplied by the batch size to get the actual number of elements.
index_type batmat::matrix::Matrix< T, I, S, D, O, A >::layer_stride() const
The layer stride, i.e.
the distance between the first layer of one batch and the first layer of the next batch. Should be multiplied by the batch size to get the actual number of elements.
bool batmat::matrix::Matrix< T, I, S, D, O, A >::has_full_layer_stride() const
Whether the layer_stride() == outer_stride() * outer_size().
bool batmat::matrix::Matrix< T, I, S, D, O, A >::has_full_outer_stride() const
Whether the outer_stride() == inner_stride() * inner_size().
bool batmat::matrix::Matrix< T, I, S, D, O, A >::has_full_inner_stride() const
Whether the inner_stride() == 1. Always true.
batch_size_type batmat::matrix::Matrix< T, I, S, D, O, A >::batch_size() const
The batch size, i.e. the number of layers in each batch. Equals the inner stride.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::reshaped(index_type rows, index_type cols)
Reshape the view to the given dimensions. The total size should not change.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::reshaped(index_type rows, index_type cols) const
Reshape the view to the given dimensions. The total size should not change.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::top_rows(index_type n)
Get a view of the first n rows.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::top_rows(index_type n) const
Get a view of the first n rows.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::left_cols(index_type n)
Get a view of the first n columns.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::left_cols(index_type n) const
Get a view of the first n columns.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::bottom_rows(index_type n)
Get a view of the last n rows.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::bottom_rows(index_type n) const
Get a view of the last n rows.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::right_cols(index_type n)
Get a view of the last n columns.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::right_cols(index_type n) const
Get a view of the last n columns.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::middle_rows(index_type r, index_type n)
Get a view of n rows starting at row r.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::middle_rows(index_type r, index_type n) const
Get a view of n rows starting at row r.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::middle_rows(index_type r, index_type n, index_type stride)
Get a view of n rows starting at row r.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::middle_rows(index_type r, index_type n, index_type stride) const
Get a view of n rows starting at row r.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::middle_cols(index_type c, index_type n)
Get a view of n columns starting at column c.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::middle_cols(index_type c, index_type n) const
Get a view of n columns starting at column c.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::middle_cols(index_type c, index_type n, index_type stride)
Get a view of n columns starting at column c.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::middle_cols(index_type c, index_type n, index_type stride) const
Get a view of n columns starting at column c.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::top_left(index_type nr, index_type nc)
Get a view of the top-left nr by nc block of the matrices.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::top_left(index_type nr, index_type nc) const
Get a view of the top-left nr by nc block of the matrices.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::top_right(index_type nr, index_type nc)
Get a view of the top-right nr by nc block of the matrices.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::top_right(index_type nr, index_type nc) const
Get a view of the top-right nr by nc block of the matrices.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::bottom_left(index_type nr, index_type nc)
Get a view of the bottom-left nr by nc block of the matrices.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::bottom_left(index_type nr, index_type nc) const
Get a view of the bottom-left nr by nc block of the matrices.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::bottom_right(index_type nr, index_type nc)
Get a view of the bottom-right nr by nc block of the matrices.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::bottom_right(index_type nr, index_type nc) const
Get a view of the bottom-right nr by nc block of the matrices.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::block(index_type r, index_type c, index_type nr, index_type nc)
Get a view of the nr by nc block of the matrices starting at row r and column c.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::block(index_type r, index_type c, index_type nr, index_type nc) const
Get a view of the nr by nc block of the matrices starting at row r and column c.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::transposed()
Get a transposed view of the matrices.
Note that the data itself is not modified, the returned view simply accesses the same data with rows and column indices swapped.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::transposed() const
Get a transposed view of the matrices.
Note that the data itself is not modified, the returned view simply accesses the same data with rows and column indices swapped.
Matrix & batmat::matrix::Matrix< T, I, S, D, O, A >::operator=(const Matrix &o)
Copy the values of another matrix, resizing if necessary.
Matrix & batmat::matrix::Matrix< T, I, S, D, O, A >::operator=(View< U, J, R, E, M, O > other)
Copy the values from a compatible view, resizing if necessary.
void batmat::matrix::Matrix< T, I, S, D, O, A >::set_constant(value_type t)
void batmat::matrix::Matrix< T, I, S, D, O, A >::add_to_diagonal(const value_type &t)
void batmat::matrix::Matrix< T, I, S, D, O, A >::negate()
void batmat::matrix::Matrix< T, I, S, D, O, A >::copy_values(const Other &other)
Matrix & batmat::matrix::Matrix< T, I, S, D, O, A >::operator+=(View< U, J, R, E, M, O > other)
view_type batmat::matrix::Matrix< T, I, S, D, O, A >::view()
Returns the same view. For consistency with Matrix.
Referenced by batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::Matrix, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::add_to_diagonal, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::as_const, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::assign_from_view, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::batch, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::batch, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::batch_dyn, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::batch_dyn, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::batch_size, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::begin, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::begin, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::block, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::block, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::bottom_left, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::bottom_left, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::bottom_right, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::bottom_right, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::bottom_rows, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::bottom_rows, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::ceil_depth, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::col_stride, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::cols, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::copy_values, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::data, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::data, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::depth, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::end, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::end, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::first_layers, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::first_layers, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::has_full_inner_stride, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::has_full_layer_stride, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::has_full_outer_stride, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::inner_size, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::inner_stride, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::layer_stride, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::left_cols, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::left_cols, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::middle_batches, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::middle_batches, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::middle_cols, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::middle_cols, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::middle_cols, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::middle_cols, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::middle_layers, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::middle_layers, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::middle_rows, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::middle_rows, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::middle_rows, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::middle_rows, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::negate, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::num_batches, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::operator const_view_type, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::operator guanaqo::MatrixView< const S, index_t, standard_stride_type, O >, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::operator guanaqo::MatrixView< S, index_t, standard_stride_type, O >, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::operator View< const S, index_t, simd_stride_t, index_t, index_t, O >, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::operator View< const S, index_t, simd_stride_t, integral_value_type_t< index_t >, DefaultStride, O >, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::operator View< S, index_t, simd_stride_t, index_t, index_t, O >, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::operator View< S, index_t, simd_stride_t, integral_value_type_t< index_t >, DefaultStride, O >, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::operator view_type, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::operator(), batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::operator(), batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::operator(), batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::operator(), batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::operator+=, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::outer_size, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::outer_stride, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::padded_size, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::reshaped, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::reshaped, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::right_cols, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::right_cols, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::row_stride, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::rows, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::set_constant, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::size, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::top_left, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::top_left, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::top_right, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::top_right, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::top_rows, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::top_rows, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::transposed, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::transposed.
const_view_type batmat::matrix::Matrix< T, I, S, D, O, A >::view() const
Returns the same view. For consistency with Matrix.
auto batmat::matrix::Matrix< T, I, S, D, O, A >::as_const() const
Explicit conversion to a const view.
batmat::matrix::Matrix< T, I, S, D, O, A >::operator view_type()
batmat::matrix::Matrix< T, I, S, D, O, A >::operator const_view_type() const
batmat::matrix::Matrix< T, I, S, D, O, A >::operator View< T, I, S, D, I, O >()
batmat::matrix::Matrix< T, I, S, D, O, A >::operator View< const T, I, S, D, I, O >() const
batmat::matrix::Matrix< T, I, S, D, O, A >::operator View< T, I, S, integral_value_type_t< D >, DefaultStride, O >()
batmat::matrix::Matrix< T, I, S, D, O, A >::operator View< const T, I, S, integral_value_type_t< D >, DefaultStride, O >() const
batmat::matrix::Matrix< T, I, S, D, O, A >::operator guanaqo::MatrixView< T, I, standard_stride_type, O >()
batmat::matrix::Matrix< T, I, S, D, O, A >::operator guanaqo::MatrixView< const T, I, standard_stride_type, O >() const
using batmat::matrix::Matrix< T, I, S, D, O, A >::view_type = View<T, I, S, D, DefaultStride, O>
using batmat::matrix::Matrix< T, I, S, D, O, A >::const_view_type = typename view_type::const_view_type
using batmat::matrix::Matrix< T, I, S, D, O, A >::layout_type = typename view_type::layout_type
using batmat::matrix::Matrix< T, I, S, D, O, A >::plain_layout_type = typename layout_type::PlainLayout
using batmat::matrix::Matrix< T, I, S, D, O, A >::value_type = T
using batmat::matrix::Matrix< T, I, S, D, O, A >::index_type = typename layout_type::index_type
using batmat::matrix::Matrix< T, I, S, D, O, A >::batch_size_type = typename layout_type::batch_size_type
using batmat::matrix::Matrix< T, I, S, D, O, A >::depth_type = typename layout_type::depth_type
using batmat::matrix::Matrix< T, I, S, D, O, A >::standard_stride_type = typename layout_type::standard_stride_type
using batmat::matrix::Matrix< T, I, S, D, O, A >::alignment_type = A
StorageOrder batmat::matrix::Matrix< T, I, S, D, O, A >::storage_order
bool batmat::matrix::Matrix< T, I, S, D, O, A >::is_column_major
bool batmat::matrix::Matrix< T, I, S, D, O, A >::is_row_major
bool batmat::matrix::Matrix< T, I, S, D, O, A >::has_single_batch_at_compile_time
bool batmat::matrix::Matrix< T, I, S, D, O, A >::has_single_layer_at_compile_time
view_type batmat::matrix::Matrix< T, I, S, D, O, A >::view_
Referenced by batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::operator=.
static constexpr auto batmat::matrix::Matrix< T, I, S, D, O, A >::default_alignment(layout_type layout)
Referenced by batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::allocate, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::allocate, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::clear.
static auto batmat::matrix::Matrix< T, I, S, D, O, A >::allocate(layout_type layout)
Referenced by batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::operator=, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::resize.
static auto batmat::matrix::Matrix< T, I, S, D, O, A >::allocate(layout_type layout, uninitialized_t init)
void batmat::matrix::Matrix< T, I, S, D, O, A >::clear()
Referenced by batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::~Matrix, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::operator=, batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::resize.
void batmat::matrix::Matrix< T, I, S, D, O, A >::assign_from_view(View< U, J, R, E, M, O > other)
Referenced by batmat::matrix::Matrix< S, index_t, simd_stride_t, index_t, O, simd_align_t >::operator=.