var searchData=
[
  ['set_2dintersection_2ehpp_0',['set-intersection.hpp',['https://tttapa.github.io/guanaqo/1.0.0-alpha.28/Doxygen/set-intersection_8hpp.html',1,'']]],
  ['shift_2ehpp_1',['shift.hpp',['../shift_8hpp.html',1,'']]],
  ['simd_2ehpp_2',['simd.hpp',['../simd_8hpp.html',1,'']]],
  ['simdify_2ehpp_3',['simdify.hpp',['../simdify_8hpp.html',1,'']]],
  ['small_2dpotrf_2ehpp_4',['small-potrf.hpp',['../micro-kernels_2small-potrf_8hpp.html',1,'(Global Namespace)'],['../small-potrf_8hpp.html',1,'(Global Namespace)']]],
  ['small_2dpotrf_2etpp_5',['small-potrf.tpp',['../small-potrf_8tpp.html',1,'']]],
  ['span_2ehpp_6',['span.hpp',['https://tttapa.github.io/guanaqo/1.0.0-alpha.28/Doxygen/span_8hpp.html',1,'']]],
  ['sparse_2dops_2ehpp_7',['sparse-ops.hpp',['https://tttapa.github.io/guanaqo/1.0.0-alpha.28/Doxygen/sparse-ops_8hpp.html',1,'']]],
  ['sparse_2ehpp_8',['sparse.hpp',['https://tttapa.github.io/guanaqo/1.0.0-alpha.28/Doxygen/sparse_8hpp.html',1,'']]],
  ['sparsity_2dconversions_2ehpp_9',['sparsity-conversions.hpp',['https://tttapa.github.io/guanaqo/1.0.0-alpha.28/Doxygen/sparsity-conversions_8hpp.html',1,'']]],
  ['sparsity_2ehpp_10',['sparsity.hpp',['https://tttapa.github.io/guanaqo/1.0.0-alpha.28/Doxygen/sparsity_8hpp.html',1,'']]],
  ['sqrt_2ehpp_11',['sqrt.hpp',['../sqrt_8hpp.html',1,'']]],
  ['sterf_2ehpp_12',['sterf.hpp',['../micro-kernels_2sterf_8hpp.html',1,'(Global Namespace)'],['../sterf_8hpp.html',1,'(Global Namespace)']]],
  ['sterf_2etpp_13',['sterf.tpp',['../sterf_8tpp.html',1,'']]],
  ['storage_2ehpp_14',['storage.hpp',['../storage_8hpp.html',1,'']]],
  ['string_2dutil_2ehpp_15',['string-util.hpp',['https://tttapa.github.io/guanaqo/1.0.0-alpha.28/Doxygen/string-util_8hpp.html',1,'']]],
  ['stringify_2eh_16',['stringify.h',['https://tttapa.github.io/guanaqo/1.0.0-alpha.28/Doxygen/stringify_8h.html',1,'']]],
  ['structure_2ehpp_17',['structure.hpp',['../structure_8hpp.html',1,'']]],
  ['symm_2ehpp_18',['symm.hpp',['../symm_8hpp.html',1,'']]],
  ['symv_2ehpp_19',['symv.hpp',['../micro-kernels_2symv_8hpp.html',1,'(Global Namespace)'],['../symv_8hpp.html',1,'(Global Namespace)']]],
  ['symv_2etpp_20',['symv.tpp',['../symv_8tpp.html',1,'']]],
  ['syomv_2ehpp_21',['syomv.hpp',['../micro-kernels_2syomv_8hpp.html',1,'(Global Namespace)'],['../syomv_8hpp.html',1,'(Global Namespace)']]],
  ['syomv_2etpp_22',['syomv.tpp',['../syomv_8tpp.html',1,'']]],
  ['sytrd_2ehpp_23',['sytrd.hpp',['../micro-kernels_2sytrd_8hpp.html',1,'(Global Namespace)'],['../sytrd_8hpp.html',1,'(Global Namespace)']]],
  ['sytrd_2etpp_24',['sytrd.tpp',['../sytrd_8tpp.html',1,'']]]
];
